Repository typedb/typedb, pull requests merged in 2019-10, with the labels that each got.

#5458 Disable janus consistency checks
  server/src/server/session/SessionImpl.java
Labels: refactor

#5461 Fix CI by not deploying api package
  .circleci/config.yml
Labels: bug, build

#5457 Migrate test-assembly-windows-zip to CircleCI Windows
  .circleci/config.yml
  .circleci/windows/dependencies.config
  .circleci/windows/prepare.bat
  .circleci/windows/test-assembly.bat
  test/assembly/windows/README.md
  test/assembly/windows/setup-template.ps1
  test/assembly/windows/windows-zip.py
Labels: build, refactor

#5462 Fix RPM deployment test
  test/deployment/rpm/test.py
Labels: bug, build

#5463 Adapt to latest changes in assemble_(tar|zip)
  .circleci/config.yml
Labels: bug, build

#5464 Cleanup Maven deployment targets and jobs
  .circleci/config.yml
  common/BUILD
  concept/BUILD
  daemon/BUILD
  dependencies/graknlabs/dependencies.bzl
  server/BUILD
Labels: build, refactor

#5465 Refactor how version is provided for APT deployment
  .circleci/config.yml
  BUILD
  server/BUILD
Labels: bug, refactor

#5469 Re-expose attribtue cache builder
  server/src/server/session/SessionFactory.java
Labels: bug, refactor

#5468 Refactor how version is provided to deployment rules
  .circleci/config.yml
  BUILD
  server/BUILD
Labels: build, refactor

#5472 Use correct variable in //ci:test-cache
  .circleci/config.yml
Labels: bug, build

#5478 Integrate checking for unused Java dependencies
  .circleci/config.yml
  WORKSPACE
  kb/concept/util/BUILD
  test-integration/graql/reasoner/pattern/BUILD
  test-integration/graql/reasoner/query/BUILD
  test-integration/graql/reasoner/reasoning/BUILD
  test-integration/server/BUILD
  test-integration/server/session/BUILD
Labels: build, feature

#5479 Check for Java unused dependencies as part of `build` CI job
  .circleci/config.yml
Labels: build, refactor

#5477 Statistics for MetaTypes and Modify `compute count;` behavior
  common/exception/ErrorMessage.java
  concept/impl/ConceptObserver.java
  graql/executor/ComputeExecutor.java
  kb/concept/api/GraknConceptException.java
  kb/server/statistics/KeyspaceStatistics.java
  kb/server/statistics/UncomittedStatisticsDelta.java
  server/session/TransactionOLTP.java
  test-integration/graql/analytics/CountIT.java
  test-integration/graql/analytics/GraqlComputeIT.java
  test-integration/server/statistics/KeyspaceStatisticsIT.java
Labels: feature, refactor

#5484 Grpc threads optimisation
  server/BUILD
  server/ServerFactory.java
  server/rpc/SessionService.java
  server/session/SessionFactory.java
Labels: refactor
