Repository typedb/typedb, pull requests merged in 2019-04, with the labels that each got.

#5081 Remove conflicting metrics library and Cassandra-unit
  dependencies/maven/artifacts/com/codahale/metrics/BUILD
  dependencies/maven/artifacts/com/datastax/cassandra/BUILD
  dependencies/maven/artifacts/info/ganglia/gmetric4j/BUILD
  dependencies/maven/artifacts/org/apache/spark/BUILD
  dependencies/maven/artifacts/org/cassandraunit/BUILD
  dependencies/maven/artifacts/org/janusgraph/BUILD
  dependencies/maven/dependencies.bzl
  dependencies/maven/dependencies.yaml
Labels: bug

#5085 remove janusgraph-hbase and janusgraph-es from dependencies
  dependencies/maven/artifacts/org/apache/httpcomponents/BUILD
  dependencies/maven/artifacts/org/elasticsearch/client/BUILD
  dependencies/maven/artifacts/org/janusgraph/BUILD
  dependencies/maven/dependencies.bzl
  dependencies/maven/dependencies.yaml
Labels: refactor

#5088 Remove janino dependency
  console/BUILD
  daemon/BUILD
  dependencies/maven/artifacts/org/codehaus/janino/BUILD
  dependencies/maven/dependencies.bzl
  dependencies/maven/dependencies.yaml
  server/BUILD
  server/conf/logback.xml
Labels: refactor

#5092 Uncomment assertions and remove debug from SubsumptionIT
  test-integration/graql/reasoner/query/SubsumptionIT.java
Labels: refactor

#5095 update spans use
  dependencies/graknlabs/dependencies.bzl
  server/src/graql/executor/QueryExecutor.java
  server/src/graql/executor/WriteExecutor.java
  server/src/graql/reasoner/DisjunctionIterator.java
  server/src/server/rpc/SessionService.java
  server/src/server/session/TransactionOLTP.java
Labels: refactor

#5091 Cleanup query exception handling
  common/exception/ErrorMessage.java
  console/test/GraknConsoleIT.java
  server/src/graql/exception/GraqlQueryException.java
  server/src/graql/executor/QueryExecutor.java
  server/src/graql/gremlin/GreedyTraversalPlan.java
  server/src/graql/reasoner/DisjunctionIterator.java
  server/src/graql/reasoner/atom/binary/AttributeAtom.java
  server/src/graql/reasoner/atom/binary/Binary.java
  server/src/graql/reasoner/atom/binary/IsaAtom.java
  server/src/graql/reasoner/atom/binary/RelationAtom.java
  server/src/graql/reasoner/atom/predicate/IdPredicate.java
  server/src/graql/reasoner/cache/SemanticCache.java
  server/src/graql/reasoner/query/CompositeQuery.java
  server/src/graql/reasoner/query/ReasonerQueries.java
  server/src/graql/reasoner/query/ReasonerQueryImpl.java
  server/src/graql/reasoner/utils/ReasonerUtils.java
  test-integration/graql/query/GraqlDefineIT.java
  test-integration/graql/query/GraqlDeleteIT.java
  test-integration/graql/query/QueryBuilderIT.java
  test-integration/graql/reasoner/query/AtomicQueryIT.java
  test-integration/graql/reasoner/query/NegationIT.java
  test-integration/graql/reasoner/query/QueryValidityIT.java
Labels: refactor

#5087 Query planner refactor 1
  server/src/graql/gremlin/GreedyTraversalPlan.java
  server/src/graql/gremlin/RelationTypeInference.java
  server/src/graql/gremlin/fragment/AbstractRolePlayerFragment.java
  server/src/graql/gremlin/fragment/Fragment.java
  server/src/graql/gremlin/fragment/InIsaFragment.java
  server/src/graql/gremlin/fragment/InPlaysFragment.java
  server/src/graql/gremlin/fragment/InRelatesFragment.java
  server/src/graql/gremlin/fragment/InSubFragment.java
  server/src/graql/gremlin/fragment/LabelFragment.java
  server/src/graql/gremlin/fragment/NeqFragment.java
  server/src/graql/gremlin/fragment/OutIsaFragment.java
  server/src/graql/gremlin/fragment/OutPlaysFragment.java
  server/src/graql/gremlin/fragment/OutRelatesFragment.java
  server/src/graql/gremlin/fragment/OutSubFragment.java
  server/src/graql/gremlin/fragment/ValueFragment.java
  server/src/graql/gremlin/spanningtree/Arborescence.java
  server/src/graql/gremlin/spanningtree/ChuLiuEdmonds.java
  server/src/graql/gremlin/spanningtree/EdgeQueueMap.java
  server/src/graql/gremlin/spanningtree/ExclusiveEdge.java
  server/src/graql/gremlin/spanningtree/graph/DenseWeightedGraph.java
  server/src/graql/gremlin/spanningtree/graph/DirectedEdge.java
  server/src/graql/gremlin/spanningtree/graph/Node.java
  server/src/graql/gremlin/spanningtree/graph/NodeId.java
  server/src/graql/gremlin/spanningtree/graph/SparseWeightedGraph.java
  server/src/graql/gremlin/spanningtree/graph/WeightedGraph.java
  server/src/graql/gremlin/spanningtree/util/Weighted.java
  server/test/graql/gremlin/spanningtree/ChuLiuEdmondsTest.java
  test-integration/graql/executor/IsaExplicitIT.java
  test-integration/graql/query/QueryPlannerIT.java
Labels: refactor

#5100 Convert types if possible on WRITE
  server/src/server/kb/concept/AttributeImpl.java
  server/src/server/kb/concept/Serialiser.java
  server/src/server/kb/concept/ValueConverter.java
  test-integration/graql/query/BUILD
  test-integration/graql/query/TypeConversionIT.java
Labels: feature

#5101 Query planner refactor 2
  server/src/graql/executor/QueryExecutor.java
  server/src/graql/gremlin/ArborescenceToPlan.java
  server/src/graql/gremlin/GreedyTraversalPlan.java
  server/src/graql/gremlin/NodesUtil.java
  server/src/graql/gremlin/RelationTypeInference.java
  server/src/graql/gremlin/fragment/AbstractRolePlayerFragment.java
  server/src/graql/gremlin/fragment/Fragment.java
  server/src/graql/gremlin/fragment/InIsaFragment.java
  server/src/graql/gremlin/fragment/InPlaysFragment.java
  server/src/graql/gremlin/fragment/InRelatesFragment.java
  server/src/graql/gremlin/fragment/InSubFragment.java
  server/src/graql/gremlin/fragment/OutIsaFragment.java
  server/src/graql/gremlin/fragment/OutPlaysFragment.java
  server/src/graql/gremlin/fragment/OutRelatesFragment.java
  server/src/graql/gremlin/fragment/OutSubFragment.java
  server/test/graql/gremlin/spanningtree/BUILD
  server/test/graql/gremlin/spanningtree/graph/DenseWeightedGraph.java
Labels: refactor

#5105 Remove unused dependencies
  dependencies/maven/artifacts/com/addthis/metrics/BUILD
  dependencies/maven/artifacts/com/google/appengine/BUILD
  dependencies/maven/artifacts/com/google/cloud/bigtable/BUILD
  dependencies/maven/artifacts/net/lingala/zip4j/BUILD
  dependencies/maven/artifacts/net/sf/jopt-simple/BUILD
  dependencies/maven/artifacts/org/apache/cassandra/BUILD
  dependencies/maven/artifacts/org/apache/hbase/BUILD
  dependencies/maven/artifacts/org/eclipse/jdt/core/compiler/BUILD
  dependencies/maven/artifacts/org/hibernate/BUILD
  dependencies/maven/artifacts/org/jboss/logging/BUILD
  dependencies/maven/artifacts/org/openjdk/jmh/BUILD
  dependencies/maven/artifacts/org/scala-lang/BUILD
  dependencies/maven/artifacts/org/scala-lang/modules/BUILD
  dependencies/maven/artifacts/org/sharegov/BUILD
  dependencies/maven/artifacts/org/slf4j/BUILD
  dependencies/maven/dependencies.bzl
  dependencies/maven/dependencies.yaml
  server/BUILD
  server/src/server/kb/concept/SchemaConceptImpl.java
Labels: refactor

#5109 Order deletes - remove relations first
  server/src/graql/executor/QueryExecutor.java
Labels: bug

#5112 Removing unused code in Cache
  common/config/ConfigKey.java
  server/conf/grakn.properties
  server/src/server/kb/cache/Cache.java
  server/src/server/kb/cache/CacheOwner.java
  server/src/server/kb/concept/ElementFactory.java
  server/src/server/kb/structure/VertexElement.java
  server/src/server/keyspace/KeyspaceManager.java
  server/src/server/session/SessionFactory.java
  server/src/server/session/SessionImpl.java
  server/src/server/session/TransactionOLTP.java
  server/src/server/session/cache/KeyspaceCache.java
  server/src/server/session/cache/TransactionCache.java
Labels: refactor

#5103 Query planner refactor 3
  server/src/graql/exception/GraqlQueryException.java
  server/src/graql/executor/QueryExecutor.java
  server/src/graql/executor/property/ValueExecutor.java
  server/src/graql/gremlin/ConjunctionQuery.java
  server/src/graql/gremlin/GreedyTreeTraversal.java
  server/src/graql/gremlin/NodesUtil.java
  server/src/graql/gremlin/TraversalPlanner.java
  server/src/graql/gremlin/fragment/AbstractRolePlayerFragment.java
  server/src/graql/gremlin/fragment/EdgeFragment.java
  server/src/graql/gremlin/fragment/Fragment.java
  server/src/graql/gremlin/fragment/InIsaFragment.java
  server/src/graql/gremlin/fragment/InPlaysFragment.java
  server/src/graql/gremlin/fragment/InRelatesFragment.java
  server/src/graql/gremlin/fragment/InSubFragment.java
  server/src/graql/gremlin/fragment/NotInternalFragment.java
  server/src/graql/gremlin/fragment/OutIsaFragment.java
  server/src/graql/gremlin/fragment/OutPlaysFragment.java
  server/src/graql/gremlin/fragment/OutRelatesFragment.java
  server/src/graql/gremlin/fragment/OutRolePlayerFragment.java
  server/src/graql/gremlin/fragment/OutSubFragment.java
  server/src/graql/reasoner/cache/StructuralCache.java
  server/src/graql/reasoner/plan/GraqlTraversalPlanner.java
  server/test/graql/gremlin/GraqlTraversalTest.java
  test-integration/graql/executor/IsaExplicitIT.java
  test-integration/graql/query/BUILD
  test-integration/graql/query/GraqlGetIT.java
  test-integration/graql/query/GraqlInsertIT.java
  test-integration/graql/query/QueryPlannerIT.java
  test-integration/graql/query/QueryValidityIT.java
  test-integration/graql/query/pattern/PatternIT.java
  test-integration/graql/reasoner/query/BUILD
Labels: refactor

#5117 Remove stacktrace from GraqlQueryException
  common/exception/GraknException.java
  server/src/graql/exception/GraqlQueryException.java
Labels: refactor

#5114 Use Janus element IDs to identify concepts
  server/resources/indices-composite.properties
  server/src/graql/analytics/ClusterMemberMapReduce.java
  server/src/graql/analytics/ConnectedComponentVertexProgram.java
  server/src/graql/analytics/ConnectedComponentsVertexProgram.java
  server/src/graql/analytics/DegreeDistributionMapReduce.java
  server/src/graql/analytics/KCoreVertexProgram.java
  server/src/graql/analytics/ShortestPathVertexProgram.java
  server/src/graql/analytics/Utility.java
  server/src/graql/executor/ComputeExecutor.java
  server/src/graql/gremlin/fragment/Fragments.java
  server/src/graql/gremlin/fragment/IdFragment.java
  server/src/graql/reasoner/atom/binary/RelationAtom.java
  server/src/server/kb/Schema.java
  server/src/server/kb/concept/ConceptImpl.java
  server/src/server/kb/concept/ConceptVertex.java
  server/src/server/kb/concept/ElementFactory.java
  server/src/server/kb/concept/RelationEdge.java
  server/src/server/kb/concept/RelationReified.java
  server/src/server/kb/concept/RelationTypeImpl.java
  server/src/server/kb/concept/ThingImpl.java
  server/src/server/kb/concept/TypeImpl.java
  server/src/server/kb/structure/AbstractElement.java
  server/src/server/kb/structure/EdgeElement.java
  server/src/server/kb/structure/ElementId.java
  server/src/server/kb/structure/Shard.java
  server/src/server/kb/structure/VertexElement.java
  server/src/server/session/TransactionOLTP.java
  server/test/graql/gremlin/fragment/InPlaysFragmentTest.java
  server/test/graql/gremlin/fragment/OutPlaysFragmentTest.java
  test-integration/graql/reasoner/reasoning/TypeGenerationIT.java
  test-integration/graql/reasoner/stubs/typeDerivationRelationsWithDirect.gql
  test-integration/server/kb/concept/RelationIT.java
  test-integration/server/kb/structure/EdgeIT.java
Labels: feature

#5121 Fix insert and delete same relation in one transaction bug
  server/src/server/kb/concept/ElementFactory.java
  server/src/server/kb/concept/RelationEdge.java
  server/src/server/kb/concept/RelationReified.java
  server/src/server/kb/concept/RelationTypeImpl.java
  server/src/server/kb/concept/ThingImpl.java
  test-integration/server/kb/BUILD
  test-integration/server/kb/TransactionIT.java
  test-integration/server/kb/concept/EntityIT.java
Labels: bug

#5128 Synchronize Graql - Extended Label grammar and renamed `asUserDefined`
  dependencies/graknlabs/dependencies.bzl
  server/src/graql/executor/QueryExecutor.java
  server/src/graql/executor/WriteExecutor.java
  server/src/graql/executor/property/HasAttributeExecutor.java
  server/src/graql/executor/property/HasAttributeTypeExecutor.java
  server/src/graql/executor/property/IsaExecutor.java
  server/src/graql/executor/property/PlaysExecutor.java
  server/src/graql/executor/property/RelatesExecutor.java
  server/src/graql/executor/property/RelationExecutor.java
  server/src/graql/executor/property/SubExecutor.java
  server/src/graql/executor/property/TypeExecutor.java
  server/src/graql/gremlin/sets/LabelFragmentSet.java
  server/src/graql/reasoner/atom/Atom.java
  server/src/graql/reasoner/atom/AtomicBase.java
  server/src/graql/reasoner/atom/AtomicFactory.java
  server/src/graql/reasoner/atom/binary/AttributeAtom.java
  server/src/graql/reasoner/atom/binary/Binary.java
  server/src/graql/reasoner/atom/binary/IsaAtom.java
  server/src/graql/reasoner/atom/binary/OntologicalAtom.java
  server/src/graql/reasoner/atom/binary/RelationAtom.java
  server/src/graql/reasoner/atom/predicate/IdPredicate.java
  server/src/graql/reasoner/atom/predicate/NeqValuePredicate.java
  server/src/graql/reasoner/atom/predicate/ValuePredicate.java
  server/src/graql/reasoner/rule/InferenceRule.java
  server/src/graql/reasoner/utils/ReasonerUtils.java
  test-integration/graql/reasoner/benchmark/BenchmarkBigIT.java
  test-integration/graql/reasoner/benchmark/BenchmarkSmallIT.java
  test-integration/graql/reasoner/pattern/RelationPattern.java
Labels: feature, refactor

#5132 Restrict the token patterns for type labels and ID values
  concept/printer/StringPrinter.java
  dependencies/graknlabs/dependencies.bzl
  test-integration/graql/analytics/GraqlComputeIT.java
  test-integration/graql/query/QueryValidityIT.java
  test-integration/graql/reasoner/GeoInferenceIT.java
  test-integration/graql/reasoner/atomic/AtomicUnificationIT.java
  test-integration/graql/reasoner/atomic/RuleApplicabilityIT.java
  test-integration/graql/reasoner/atomic/TypeInferenceIT.java
  test-integration/graql/reasoner/benchmark/BenchmarkBigIT.java
  test-integration/graql/reasoner/benchmark/BenchmarkSmallIT.java
  test-integration/graql/reasoner/cache/QueryCacheIT.java
  test-integration/graql/reasoner/pattern/AttributePattern.java
  test-integration/graql/reasoner/pattern/TypePattern.java
  test-integration/graql/reasoner/query/AtomicQueryEquivalenceIT.java
  test-integration/graql/reasoner/query/ExplanationIT.java
  test-integration/graql/reasoner/query/NegationIT.java
  test-integration/graql/reasoner/query/QueryIT.java
  test-integration/graql/reasoner/query/ResolutionPlanIT.java
  test-integration/graql/reasoner/reasoning/VariableRolesIT.java
  test-integration/graql/reasoner/resources/recursion/same-generation.gql
  test-integration/graql/reasoner/resources/recursion/tail-recursion.gql
  test-integration/graql/reasoner/resources/recursion/transitivity.gql
  test-integration/graql/reasoner/stubs/explanations.gql
  test-integration/server/kb/RuleIT.java
Labels: bug, refactor

#5130 Cross-type subsumption fixes
  server/src/graql/reasoner/atom/binary/AttributeAtom.java
  server/src/graql/reasoner/atom/binary/Binary.java
  server/src/graql/reasoner/atom/binary/IsaAtom.java
  server/src/graql/reasoner/cache/SemanticCache.java
  server/src/graql/reasoner/query/ReasonerAtomicQuery.java
  server/src/graql/reasoner/unifier/UnifierType.java
  test-integration/graql/reasoner/pattern/QueryPattern.java
  test-integration/graql/reasoner/query/AtomicQueryUnificationIT.java
  test-integration/graql/reasoner/query/ExplanationIT.java
  test-integration/graql/reasoner/query/SubsumptionIT.java
Labels: bug

#5134 Require type directedness to be equal when determining subsumption
  server/src/graql/reasoner/atom/binary/Binary.java
  server/src/graql/reasoner/cache/SemanticCache.java
  server/src/graql/reasoner/unifier/UnifierComparison.java
  server/src/graql/reasoner/unifier/UnifierType.java
  test-integration/graql/reasoner/query/SubsumptionIT.java
Labels: bug

#5133 Add cross-type tests for finding RULE unifiers
  test-integration/graql/reasoner/query/AtomicQueryUnificationIT.java
Labels: feature

#5137 Remove single redundant method
  server/src/graql/gremlin/fragment/OutIsaFragment.java
Labels: refactor

#5139 Add benchmark:master to sync-dependencies
  .circleci/config.yml
Labels: feature

#5142 Do not persist inferred concepts
  server/src/server/session/TransactionOLTP.java
  server/src/server/session/cache/TransactionCache.java
  test-integration/server/kb/TransactionIT.java
Labels: bug

#5143 Shutdown Server even when there are still client connections open
  server/src/graql/executor/QueryExecutor.java
  server/src/graql/gremlin/GraqlTraversal.java
  server/src/server/Grakn.java
  server/src/server/ServerFactory.java
  server/src/server/rpc/SessionService.java
  server/src/server/session/TransactionOLTP.java
  test-end-to-end/distribution/BUILD
  test-end-to-end/distribution/GraknGraqlCommandsE2E.java
  test-integration/rule/GraknTestServer.java
Labels: bug
