Repository typedb/typedb, pull requests merged in 2019-06, with the labels that each got.

#5224 introduce attributeMap and remove graphLock
  server/src/server/deduplicator/AttributeDeduplicator.java
  server/src/server/kb/concept/AttributeTypeImpl.java
  server/src/server/keyspace/KeyspaceManager.java
  server/src/server/rpc/SessionService.java
  server/src/server/session/SessionFactory.java
  server/src/server/session/SessionImpl.java
  server/src/server/session/TransactionOLTP.java
  server/src/server/session/cache/TransactionCache.java
  test-end-to-end/BUILD
  test-end-to-end/deduplicator/AttributeDeduplicatorE2E.java
  test-end-to-end/distribution/BUILD
  test-end-to-end/distribution/ConcurrencyE2E.java
  test-integration/rule/GraknTestServer.java
  test-integration/server/BUILD
  test-integration/server/session/BUILD
  test-integration/server/session/cache/KeyspaceCacheIT.java
Labels: bug, refactor

#5229 Minor cleanup in TransactionOLTP
  server/src/server/session/TransactionOLTP.java
Labels: refactor

#5232 Optimise instance count updates
  server/src/server/statistics/KeyspaceStatistics.java
  server/src/server/statistics/UncomittedStatisticsDelta.java
  test-integration/server/statistics/KeyspaceStatisticsIT.java
  test-integration/server/statistics/UncomittedStatisticsDeltaIT.java
Labels: refactor

#5234 Ensure concept counts are not decremented multiple times on deletion
  server/src/server/kb/concept/RelationEdge.java
  server/src/server/kb/concept/ThingImpl.java
  server/src/server/statistics/KeyspaceStatistics.java
  test-integration/server/kb/concept/AttributeIT.java
  test-integration/server/statistics/KeyspaceStatisticsIT.java
  test-integration/server/statistics/UncomittedStatisticsDeltaIT.java
Labels: refactor

#5237 Remove inferred flag from inferred concepts when committing
  server/src/graql/executor/WriteExecutor.java
  test-integration/server/kb/TransactionIT.java
Labels: bug

#5239 Temporarily ignore flaky test
  test-integration/graql/reasoner/query/ResolutionPlanIT.java
Labels: refactor

#5240 Optimise atom materialise
  server/src/graql/reasoner/atom/Atom.java
  server/src/graql/reasoner/atom/binary/AttributeAtom.java
  server/src/graql/reasoner/atom/binary/IsaAtom.java
  server/src/graql/reasoner/atom/binary/RelationAtom.java
  server/src/graql/reasoner/cache/MultilevelSemanticCache.java
  server/src/graql/reasoner/cache/QueryCacheBase.java
  server/src/graql/reasoner/cache/SemanticCache.java
  server/src/graql/reasoner/cache/SimpleQueryCache.java
  server/src/graql/reasoner/state/AtomicState.java
  test-end-to-end/client-java/ClientJavaE2E.java
Labels: refactor

#5241 Remove old query cache implementation
  server/src/graql/reasoner/cache/SemanticCache.java
  server/src/graql/reasoner/cache/SimpleQueryCache.java
  server/src/graql/reasoner/cache/SimpleQueryCacheBase.java
  server/src/graql/reasoner/query/QueryAnswers.java
  server/src/graql/reasoner/rule/RuleUtils.java
  server/src/graql/reasoner/utils/ReasonerUtils.java
Labels: refactor

#5244 Fix the deploy-github CI job bug by installing missing dependencies
  .circleci/config.yml
Labels: build

#5247 Expose Grakn/Cassandra logs as CI build artifacts
  .circleci/config.yml
  test/assembly/docker.py
  test/assembly/windows/windows-zip.py
  test/deployment/rpm.py
Labels: build, feature

#5251 Fix exposing Grakn logs as build artifacts
  .circleci/config.yml
  test/assembly/windows/windows-zip.py
Labels: bug, build

#5250 Differentiate between atoms with and without relation variable when computing equivalence
  server/src/graql/reasoner/atom/binary/AttributeAtom.java
  test-integration/graql/reasoner/pattern/AttributePattern.java
  test-integration/graql/reasoner/query/AtomicQueryUnificationIT.java
  test-integration/graql/reasoner/query/SubsumptionIT.java
Labels: bug

#5252 Fix exposing Grakn/Cassandra logs as build artifacts
  .circleci/config.yml
  test/assembly/windows/windows-zip.py
Labels: bug, build

#5254 Ensure materialised answers are in cache when checking for answer existence
  server/src/graql/reasoner/atom/Atom.java
  server/src/graql/reasoner/cache/SemanticCache.java
  server/src/graql/reasoner/state/AtomicState.java
  test-integration/graql/reasoner/ReasoningIT.java
  test-integration/graql/reasoner/stubs/BUILD
  test-integration/graql/reasoner/stubs/duplicateMaterialisation.gql
Labels: bug

#5257 Add read through attributesMap in a thread safe way
  server/src/server/deduplicator/AttributeDeduplicator.java
Labels: bug

#5256 Make sure we do not discard rules if negation block contains types without instances
  server/src/server/session/cache/RuleCache.java
  test-integration/graql/reasoner/query/NegationIT.java
  test-integration/graql/reasoner/stubs/negation.gql
Labels: bug

#5258 Make sure if we materialise symmetric relations we return all answer combinations
  server/src/graql/reasoner/atom/binary/RelationAtom.java
  server/src/graql/reasoner/state/AtomicState.java
  test-end-to-end/client-java/ClientJavaE2E.java
  test-integration/graql/reasoner/ReasoningIT.java
Labels: bug

#5246 Refactor attribute atom materialisation pt II
  server/src/graql/reasoner/atom/binary/AttributeAtom.java
  server/src/graql/reasoner/atom/binary/RelationAtom.java
  server/src/graql/reasoner/state/AtomicState.java
  test-integration/graql/reasoner/reasoning/AttributeAttachmentIT.java
  test-integration/graql/reasoner/stubs/resourceAttachment.gql
Labels: refactor

#5261 Explicitly set unifier type to RULE when checking materialised answers
  server/src/graql/reasoner/state/AtomicState.java
Labels: bug

#5245 Refactor reiteration condition
  server/src/graql/reasoner/DisjunctionIterator.java
  server/src/graql/reasoner/ResolutionIterator.java
  server/src/graql/reasoner/atom/binary/RelationAtom.java
  server/src/graql/reasoner/cache/AtomicQueryCacheBase.java
  server/src/graql/reasoner/cache/QueryCacheBase.java
  server/src/graql/reasoner/cache/SemanticCache.java
  server/src/graql/reasoner/query/CompositeQuery.java
  server/src/graql/reasoner/query/ReasonerQueryImpl.java
  server/src/graql/reasoner/query/ResolvableQuery.java
  server/src/graql/reasoner/rule/RuleUtils.java
  server/src/graql/reasoner/state/CompositeState.java
  server/src/graql/reasoner/utils/TarjanSCC.java
  test-integration/graql/reasoner/cache/QueryCacheIT.java
  test-integration/graql/reasoner/query/QueryIT.java
  test-integration/graql/reasoner/reasoning/RecursionIT.java
Labels: refactor

#5260 Farewell AttributeDeduplicator
  server/conf/grakn.properties
  server/src/server/Server.java
  server/src/server/ServerFactory.java
  server/src/server/deduplicator/AttributeDeduplicator.java
  server/src/server/deduplicator/AttributeDeduplicatorDaemon.java
  server/src/server/deduplicator/KeyspaceAttributeTriple.java
  server/src/server/deduplicator/queue/Attribute.java
  server/src/server/deduplicator/queue/InMemoryQueue.java
  server/src/server/deduplicator/queue/RocksDbQueueException.java
  server/src/server/exception/TemporaryWriteException.java
  server/src/server/kb/concept/AttributeImpl.java
  server/src/server/keyspace/KeyspaceManager.java
  server/src/server/rpc/SessionService.java
  server/src/server/session/SessionFactory.java
  server/src/server/session/SessionImpl.java
  server/src/server/session/TransactionOLTP.java
  server/src/server/session/cache/TransactionCache.java
  server/test/server/deduplicator/BUILD
  server/test/server/deduplicator/InMemoryQueueTest.java
  test-end-to-end/BUILD
  test-end-to-end/deduplicator/AttributeDeduplicatorE2EConstants.java
  test-end-to-end/deduplicator/BUILD
  test-end-to-end/distribution/AttributeUniquenessE2E.java
  test-end-to-end/distribution/BUILD
  test-end-to-end/distribution/ConcurrencyE2E.java
  test-integration/graql/query/TypeConversionIT.java
  test-integration/rule/GraknTestServer.java
  test-integration/server/AttributeUniquenessIT.java
  test-integration/server/BUILD
  test-integration/server/statistics/KeyspaceStatisticsIT.java
  test-integration/server/statistics/UncomittedStatisticsDeltaIT.java
Labels: bug, refactor

#5262 Update cache behaviour for queries with a unique answer
  server/src/graql/reasoner/atom/Atom.java
  server/src/graql/reasoner/atom/binary/AttributeAtom.java
  server/src/graql/reasoner/cache/AtomicQueryCacheBase.java
  server/src/graql/reasoner/cache/SemanticCache.java
  server/src/graql/reasoner/query/ReasonerAtomicQuery.java
  server/src/graql/reasoner/query/ReasonerQueryImpl.java
  test-integration/graql/reasoner/cache/QueryCacheIT.java
Labels: refactor

#5253 Make 'grakn server clean' command to clean the correct data directory as specified in grakn.properties
  daemon/executor/Storage.java
  test-end-to-end/distribution/GraknGraqlCommandsE2E.java
Labels: bug

#5266 Core Bugfixes
  server/src/graql/executor/QueryExecutor.java
  server/src/graql/gremlin/GraqlTraversal.java
  server/src/graql/gremlin/fragment/Fragment.java
  server/src/graql/gremlin/fragment/IdFragment.java
  server/src/graql/gremlin/fragment/OutIsaFragment.java
  server/src/graql/gremlin/fragment/OutRolePlayerFragment.java
  test-integration/graql/query/GraqlDeleteIT.java
  test-integration/graql/query/GraqlGetIT.java
Labels: bug

#5236 Server now connects to Storage by using Janusgraph Thrift Driver rather than Astyanax
  dependencies/maven/artifacts/com/netflix/astyanax/BUILD
  dependencies/maven/artifacts/info/ganglia/gmetric4j/BUILD
  dependencies/maven/artifacts/io/dropwizard/metrics/BUILD
  dependencies/maven/artifacts/org/apache/servicemix/bundles/BUILD
  dependencies/maven/artifacts/org/janusgraph/BUILD
  dependencies/maven/dependencies.bzl
  dependencies/maven/dependencies.yaml
  server/conf/grakn.properties
  server/resources/default-configs.properties
  server/src/server/rpc/SessionService.java
  server/src/server/session/JanusGraphFactory.java
Labels: don't merge

#5274 Fix creation and deletion of attributes bugs
  server/src/server/session/TransactionOLTP.java
  server/src/server/session/cache/TransactionCache.java
  test-integration/server/AttributeUniquenessIT.java
  test-integration/server/session/BUILD
  test-integration/server/session/cache/TransactionCacheIT.java
Labels: bug

#5280 Define atom conversion behaviours explicitly
  server/src/graql/reasoner/atom/Atom.java
  server/src/graql/reasoner/atom/binary/AttributeAtom.java
  server/src/graql/reasoner/atom/binary/RelationAtom.java
  test-integration/graql/reasoner/atomic/BUILD
  test-integration/graql/reasoner/atomic/ConversionIT.java
  test-integration/graql/reasoner/atomic/RoleInferenceIT.java
  test-integration/graql/reasoner/atomic/TypeInferenceIT.java
Labels: refactor

#5281 Number Comparison
  server/src/graql/executor/property/ValueExecutor.java
  server/src/graql/gremlin/GraqlTraversal.java
  server/src/graql/gremlin/sets/AttributeIndexFragmentSet.java
  test-integration/graql/query/BUILD
  test-integration/graql/query/NumberCastingIT.java
Labels: feature

#5282 Proper use of JanusTransaction
  server/src/server/kb/concept/ElementFactory.java
  server/src/server/keyspace/KeyspaceManager.java
  server/src/server/session/JanusGraphFactory.java
  server/src/server/session/SessionFactory.java
  server/src/server/session/SessionImpl.java
  server/src/server/session/TransactionOLTP.java
Labels: bug, refactor

#5283 Make e2e test large instead of medium
  test-end-to-end/distribution/BUILD
Labels: refactor

#5284 Deprioritise implicit labels
  console/printer/Printer.java
  server/src/graql/gremlin/TraversalPlanner.java
  server/src/graql/reasoner/state/VariableComparisonState.java
  test-integration/graql/query/QueryPlannerIT.java
Labels: refactor

#5259 Do not rewrite rule body variables
  server/src/graql/reasoner/rule/InferenceRule.java
Labels: refactor

#5292 Split //protocol to new repo: graknlabs/protocol
  .circleci/config.yml
  .github/CODEOWNERS
  WORKSPACE
  dependencies/graknlabs/dependencies.bzl
  protocol/BUILD
  protocol/LICENSE
  protocol/README.md
  protocol/keyspace/BUILD
  protocol/keyspace/Keyspace.proto
  protocol/session/Answer.proto
  protocol/session/BUILD
  protocol/session/Concept.proto
  protocol/session/Session.proto
  server/BUILD
Labels: refactor

#5291 Simplify attribute equivalence
  server/src/graql/reasoner/atom/binary/AttributeAtom.java
  server/src/graql/reasoner/atom/binary/Binary.java
  server/src/graql/reasoner/atom/binary/RelationAtom.java
  server/src/graql/reasoner/cache/MultilevelSemanticCache.java
  test-integration/graql/reasoner/graph/GenericSchemaGraph.java
  test-integration/graql/reasoner/pattern/AttributePattern.java
  test-integration/graql/reasoner/pattern/QueryPattern.java
  test-integration/graql/reasoner/query/AtomicQueryUnificationIT.java
  test-integration/graql/reasoner/query/SubsumptionIT.java
Labels: refactor

#5293 Cleanup code in TransactionOLTP and ElementFactory
  server/src/server/kb/concept/ElementFactory.java
  server/src/server/kb/concept/TypeImpl.java
  server/src/server/session/TransactionOLTP.java
Labels: refactor

#5295 Do no use locks when initialising system keyspace
  server/src/server/Server.java
  server/src/server/ServerFactory.java
  server/src/server/exception/GraknServerException.java
  server/src/server/keyspace/KeyspaceManager.java
  server/src/server/session/SessionFactory.java
  server/src/server/util/LockManager.java
  server/src/server/util/ServerLockManager.java
  server/test/server/util/BUILD
  server/test/server/util/LockManagerTest.java
  test-integration/rule/GraknTestServer.java
Labels: refactor

#5294 Correctly materialise implicit relations
  server/src/graql/reasoner/atom/binary/RelationAtom.java
  server/src/graql/reasoner/state/AtomicState.java
  test-integration/graql/reasoner/reasoning/AttributeAttachmentIT.java
Labels: bug

#5297 Rename graph to tx and remove unused error message
  common/exception/ErrorMessage.java
  server/src/graql/analytics/Utility.java
  server/src/graql/gremlin/fragment/AbstractFragment.java
  server/src/graql/gremlin/fragment/AttributeIndexFragment.java
  server/src/graql/gremlin/fragment/IdFragment.java
  server/src/graql/gremlin/fragment/InIsaFragment.java
  server/src/graql/gremlin/fragment/InPlaysFragment.java
  server/src/graql/gremlin/fragment/InRelatesFragment.java
  server/src/graql/gremlin/fragment/InSubFragment.java
  server/src/graql/gremlin/fragment/NeqFragment.java
  server/src/graql/gremlin/fragment/NotInternalFragment.java
  server/src/graql/gremlin/fragment/OutIsaFragment.java
  server/src/graql/gremlin/fragment/OutPlaysFragment.java
  server/src/graql/gremlin/fragment/OutRelatesFragment.java
  server/src/graql/gremlin/fragment/OutSubFragment.java
  server/src/graql/gremlin/fragment/RegexFragment.java
  server/src/graql/gremlin/fragment/ValueFragment.java
  server/src/graql/gremlin/sets/AttributeIndexFragmentSet.java
  server/src/graql/reasoner/atom/binary/RelationAtom.java
  server/src/graql/reasoner/atom/predicate/IdPredicate.java
  server/src/graql/reasoner/query/CompositeQuery.java
Labels: refactor
