Repository typedb/typedb, pull requests merged in 2019-05, with the labels that each got.

#5144 Terminate console gracefully on ctrl + c
  console/ConsoleSession.java
  console/GraknConsole.java
Labels: bug

#5152 Fix issues with unification of reflexive relations
  common/exception/ErrorMessage.java
  server/src/graql/exception/GraqlQueryException.java
  server/src/graql/reasoner/atom/Atom.java
  server/src/graql/reasoner/atom/binary/AttributeAtom.java
  server/src/graql/reasoner/atom/binary/Binary.java
  server/src/graql/reasoner/atom/binary/RelationAtom.java
  server/src/graql/reasoner/query/CompositeQuery.java
  server/src/graql/reasoner/query/ReasonerAtomicQuery.java
  server/src/graql/reasoner/query/ReasonerQuery.java
  server/src/graql/reasoner/query/ReasonerQueryImpl.java
  server/src/graql/reasoner/unifier/Unifier.java
  server/src/graql/reasoner/unifier/UnifierComparison.java
  server/src/graql/reasoner/unifier/UnifierImpl.java
  server/src/graql/reasoner/unifier/UnifierType.java
  server/src/graql/reasoner/utils/Pair.java
  server/src/graql/reasoner/utils/ReasonerUtils.java
  server/src/server/kb/concept/ConceptUtils.java
  test-integration/graql/reasoner/atomic/TypeInferenceIT.java
  test-integration/graql/reasoner/graph/BUILD
  test-integration/graql/reasoner/graph/GenericSchemaGraph.java
  test-integration/graql/reasoner/pattern/RelationPattern.java
  test-integration/graql/reasoner/query/AtomicQueryEquivalenceIT.java
  test-integration/graql/reasoner/query/AtomicQueryUnificationIT.java
  test-integration/graql/reasoner/query/SubsumptionIT.java
Labels: bug

#5151 Re-add Gremlin indexed nodes steps first
  server/src/graql/gremlin/GreedyTreeTraversal.java
  server/src/graql/gremlin/NodesUtil.java
  server/src/graql/gremlin/TraversalPlanner.java
  test-integration/graql/query/QueryPlannerIT.java
Labels: refactor

#5159 Dont start|stop server with wrong specific command
  daemon/GraknDaemon.java
  test-end-to-end/distribution/GraknGraqlCommandsE2E.java
Labels: bug

#5160 Remove expensive log call
  server/src/graql/reasoner/cache/SemanticCache.java
Labels: refactor

#5155 Refactor equivalence and unification of relation atoms
  server/src/graql/reasoner/atom/Atom.java
  server/src/graql/reasoner/atom/binary/RelationAtom.java
  server/src/graql/reasoner/cache/SemanticCache.java
  server/src/graql/reasoner/unifier/UnifierType.java
  server/src/graql/reasoner/utils/ReasonerUtils.java
  test-integration/graql/reasoner/ReasoningIT.java
  test-integration/graql/reasoner/graph/GenericSchemaGraph.java
  test-integration/graql/reasoner/pattern/RelationPattern.java
  test-integration/graql/reasoner/query/AtomicQueryEquivalenceIT.java
  test-integration/graql/reasoner/query/AtomicQueryUnificationIT.java
  test-integration/graql/reasoner/reasoning/VariableRolesIT.java
  test-integration/graql/reasoner/stubs/appendingRPs.gql
  test-integration/graql/reasoner/stubs/testSet29.gql
Labels: bug, refactor

#5167 Log exceptions from KeyspaceService
  server/src/server/rpc/KeyspaceService.java
Labels: bug

#5166 Fix editor command for Windows
  console/ConsoleSession.java
Labels: bug

#5158 Close session if client abruptly terminates connection
  server/src/server/rpc/SessionService.java
Labels: refactor

#5153 TransactionListener does not block on thread
  console/ConsoleSession.java
  dependencies/graknlabs/dependencies.bzl
  server/src/server/rpc/SessionService.java
Labels: feature, refactor

#5168 Refactor role compatibility checking when unifying relations
  server/src/graql/reasoner/atom/binary/RelationAtom.java
  server/src/graql/reasoner/unifier/UnifierComparison.java
  server/src/graql/reasoner/unifier/UnifierType.java
  test-integration/graql/reasoner/atomic/AtomicUnificationIT.java
  test-integration/graql/reasoner/query/SubsumptionIT.java
Labels: refactor

#5170 Differentiate semantic and query exceptions
  console/test/GraknConsoleIT.java
  server/src/graql/analytics/ConnectedComponentVertexProgram.java
  server/src/graql/analytics/CorenessVertexProgram.java
  server/src/graql/analytics/KCoreVertexProgram.java
  server/src/graql/exception/GraqlQueryException.java
  server/src/graql/exception/GraqlSemanticException.java
  server/src/graql/executor/ComputeExecutor.java
  server/src/graql/executor/ConceptBuilder.java
  server/src/graql/executor/QueryExecutor.java
  server/src/graql/executor/WriteExecutor.java
  server/src/graql/executor/property/AbstractExecutor.java
  server/src/graql/executor/property/HasAttributeTypeExecutor.java
  server/src/graql/executor/property/PropertyExecutor.java
  server/src/graql/executor/property/RelationExecutor.java
  server/src/graql/executor/property/ThenExecutor.java
  server/src/graql/executor/property/TypeExecutor.java
  server/src/graql/executor/property/ValueExecutor.java
  server/src/graql/executor/property/WhenExecutor.java
  server/src/graql/reasoner/atom/binary/AttributeAtom.java
  server/src/graql/reasoner/atom/binary/IsaAtom.java
  server/src/graql/reasoner/atom/binary/RelationAtom.java
  server/src/graql/reasoner/atom/predicate/IdPredicate.java
  server/src/graql/reasoner/plan/ResolutionPlan.java
  server/src/graql/reasoner/query/CompositeQuery.java
  server/src/server/rpc/ResponseBuilder.java
  test-integration/graql/analytics/ConnectedComponentIT.java
  test-integration/graql/analytics/CorenessIT.java
  test-integration/graql/analytics/GraqlComputeIT.java
  test-integration/graql/analytics/KCoreIT.java
  test-integration/graql/analytics/PathIT.java
  test-integration/graql/analytics/StatisticsIT.java
  test-integration/graql/query/GraqlDefineIT.java
  test-integration/graql/query/GraqlDeleteIT.java
  test-integration/graql/query/GraqlGetIT.java
  test-integration/graql/query/GraqlInsertIT.java
  test-integration/graql/query/GraqlUndefineIT.java
  test-integration/graql/query/QueryBuilderIT.java
  test-integration/graql/query/QueryErrorIT.java
  test-integration/graql/query/QueryValidityIT.java
  test-integration/graql/query/pattern/PatternIT.java
  test-integration/graql/reasoner/query/AtomicQueryIT.java
  test-integration/graql/reasoner/query/NegationIT.java
Labels: refactor

#5171 Fix issues when calculating semantic difference when roles are variable
  server/src/graql/reasoner/atom/binary/RelationAtom.java
  test-integration/graql/reasoner/query/SemanticDifferenceIT.java
Labels: bug

#5173 Correctly acknowledge role expansion answers
  server/src/graql/reasoner/state/AtomicState.java
  test-integration/graql/reasoner/ReasoningIT.java
  test-integration/graql/reasoner/cache/QueryCacheIT.java
Labels: bug

#5174 Fix issue with returned role variables
  server/src/graql/reasoner/atom/Atom.java
  server/src/graql/reasoner/atom/binary/AttributeAtom.java
  server/src/graql/reasoner/atom/binary/Binary.java
  server/src/graql/reasoner/atom/binary/IsaAtom.java
  server/src/graql/reasoner/atom/binary/RelationAtom.java
  server/src/graql/reasoner/utils/ReasonerUtils.java
  test-integration/graql/reasoner/query/AtomicQueryUnificationIT.java
Labels: bug

#5131 Enable query cache at tx level
  server/src/graql/reasoner/DisjunctionIterator.java
  server/src/graql/reasoner/ResolutionIterator.java
  server/src/graql/reasoner/cache/QueryCacheBase.java
  server/src/graql/reasoner/cache/SemanticCache.java
Labels: feature

#5178 Unignore previously flaky test in OntologicalQueryIT
  test-integration/graql/reasoner/query/BUILD
  test-integration/graql/reasoner/query/OntologicalQueryIT.java
  test-integration/graql/reasoner/resources/BUILD
  test-integration/graql/reasoner/resources/matchingTypesTest.gql
Labels: refactor

#5145 Allow reusing attributes in match-inserts
  server/src/graql/exception/GraqlSemanticException.java
  server/src/graql/executor/WriteExecutor.java
  server/src/graql/executor/property/IsaExecutor.java
  test-integration/graql/query/GraqlInsertIT.java
Labels: feature

#5180 Add implicit relation info if needed when materialising attributes
  server/src/graql/reasoner/atom/binary/AttributeAtom.java
  server/src/server/kb/concept/RelationImpl.java
  server/src/server/kb/concept/ThingImpl.java
  test-integration/graql/reasoner/reasoning/AttributeAttachmentIT.java
Labels: bug

#5184 Add a test to ensure we are not committing inferred attribute edges
  test-integration/server/kb/TransactionIT.java
Labels: refactor

#5183 Compute queries work again on Windows
  BUILD
  bin/grakn.bat
  server/BUILD
  server/services/hadoop/bin/winutils.exe
  test/common/GraknApplicationTest.java
Labels: bug

#5186 Make sure we do not return duplicate played roles
  server/src/server/kb/concept/TypeImpl.java
  test-integration/server/kb/concept/AttributeIT.java
Labels: refactor

#5189 Fix issue with unattaching attributes from relations
  server/src/server/kb/concept/RelationImpl.java
  server/src/server/kb/concept/RelationTypeImpl.java
  server/src/server/kb/concept/RoleImpl.java
  test-integration/server/kb/ValidateGlobalRulesIT.java
  test-integration/server/kb/concept/EntityIT.java
  test-integration/server/kb/concept/RelationIT.java
  test-integration/server/kb/structure/CastingIT.java
Labels: bug

#5190 Handle benchmark flag when parsing start command
  daemon/GraknDaemon.java
  test-end-to-end/distribution/DistributionE2EConstants.java
  test-end-to-end/distribution/GraknGraqlCommandsE2E.java
Labels: bug

#5194 Print also Grakn version together with Grakn logo
  daemon/GraknDaemon.java
  server/services/grakn/grakn-core-ascii.txt
Labels: feature

#5192 Make sure PID stored in pid files is actually bound to a Grakn process
  daemon/GraknDaemon.java
  daemon/executor/Executor.java
  daemon/executor/Server.java
  daemon/executor/Storage.java
Labels: bug

#5172 Cache distribution test results
  .circleci/config.yml
Labels: build, feature

#5188 Deploy Grakn Docker image with latest tag
  .bazelrc
  BUILD
  bin/workspace_status.sh
Labels: bug, build

#5199 Cleanup atomic tests
  test-integration/graql/reasoner/atomic/AtomicEquivalenceIT.java
  test-integration/graql/reasoner/atomic/AtomicUnificationIT.java
  test-integration/graql/reasoner/atomic/BUILD
  test-integration/graql/reasoner/atomic/RoleInferenceIT.java
Labels: refactor

#5197 Cache pattern and vars for query and optimise conditional in RelationAtom
  server/src/graql/reasoner/atom/binary/RelationAtom.java
  server/src/graql/reasoner/query/ReasonerQueryImpl.java
Labels: refactor

#5195 Optimise QueryCache query completion acking
  server/src/graql/reasoner/ResolutionIterator.java
  server/src/graql/reasoner/query/ReasonerAtomicQuery.java
  server/src/graql/reasoner/state/AtomicState.java
  server/src/graql/reasoner/state/ResolutionState.java
  test-integration/graql/reasoner/cache/QueryCacheIT.java
Labels: refactor

#5201 Fix possible missing ValuePredicate vars in attribute atoms
  server/src/graql/reasoner/atom/binary/AttributeAtom.java
  test-integration/graql/reasoner/query/BUILD
  test-integration/graql/reasoner/query/QueryIT.java
Labels: bug

#5204 Fix concurrent modification issue in query cache
  server/src/graql/reasoner/cache/SemanticCache.java
Labels: bug

#5205 Lock graph when attribute deduplicator needs to merge attributes
  server/src/server/deduplicator/AttributeDeduplicator.java
  server/src/server/kb/concept/AttributeTypeImpl.java
  server/src/server/session/SessionImpl.java
  test-integration/server/BUILD
Labels: bug

#5203 Statistics 1.1 - improve ValueFragment starting point cost estimate efficiency
  server/src/graql/gremlin/fragment/ValueFragment.java
  test-integration/graql/query/BUILD
  test-integration/graql/query/GraqlGetIT.java
Labels: refactor

#5206 Add logback file for console distribution
  console/BUILD
  console/conf/logback.xml
Labels: bug

#5207 Dedicated conf folder for console and server
  BUILD
  bin/grakn
  bin/grakn.bat
  console/BUILD
  daemon/GraknDaemon.java
  server/BUILD
  test-end-to-end/client-java/ClientJavaE2EConstants.java
  test-end-to-end/deduplicator/AttributeDeduplicatorE2EConstants.java
  test-end-to-end/distribution/DistributionE2EConstants.java
  test-end-to-end/distribution/GraknGraqlCommandsE2E.java
Labels: refactor

#5209 Remove guava and autovalue dependencies from common package
  common/BUILD
  common/config/Config.java
  common/config/ConfigKey.java
  common/http/SimpleURI.java
  common/util/CommonUtil.java
  console/BUILD
  console/ConsoleSession.java
  console/GraknConsole.java
  console/test/GraknConsoleIT.java
  dependencies/graknlabs/dependencies.bzl
  server/src/graql/executor/ComputeExecutor.java
  server/src/graql/executor/QueryExecutor.java
  server/src/graql/executor/property/RelationExecutor.java
  server/src/graql/gremlin/ConjunctionQuery.java
  server/src/graql/gremlin/GraqlTraversal.java
  server/src/graql/gremlin/TraversalPlanner.java
  server/src/graql/gremlin/sets/RolePlayerFragmentSet.java
  server/src/graql/reasoner/atom/binary/IsaAtom.java
  test-integration/graql/reasoner/benchmark/BenchmarkBigIT.java
  test-integration/rule/GraknTestServer.java
  test-integration/server/session/cache/KeyspaceCacheIT.java
  test-integration/server/statistics/KeyspaceStatisticsIT.java
Labels: refactor

#5208 Use custom java toolchain from @graknlabs_build_tools
  .bazelrc
Labels: bug, build

#5210 QP Nodes - label propagation and count estimates
  server/src/graql/gremlin/GreedyTreeTraversal.java
  server/src/graql/gremlin/NodesUtil.java
  server/src/graql/gremlin/TraversalPlanner.java
  server/src/graql/gremlin/fragment/AbstractRolePlayerFragment.java
  server/src/graql/gremlin/fragment/AttributeIndexFragment.java
  server/src/graql/gremlin/fragment/EdgeFragment.java
  server/src/graql/gremlin/fragment/Fragment.java
  server/src/graql/gremlin/fragment/IdFragment.java
  server/src/graql/gremlin/fragment/InIsaFragment.java
  server/src/graql/gremlin/fragment/InPlaysFragment.java
  server/src/graql/gremlin/fragment/InRelatesFragment.java
  server/src/graql/gremlin/fragment/InSubFragment.java
  server/src/graql/gremlin/fragment/LabelFragment.java
  server/src/graql/gremlin/fragment/OutIsaFragment.java
  server/src/graql/gremlin/fragment/OutPlaysFragment.java
  server/src/graql/gremlin/fragment/OutRelatesFragment.java
  server/src/graql/gremlin/fragment/OutSubFragment.java
  server/src/graql/gremlin/fragment/ValueFragment.java
  server/src/graql/gremlin/spanningtree/graph/EdgeNode.java
  server/src/graql/gremlin/spanningtree/graph/IdNode.java
  server/src/graql/gremlin/spanningtree/graph/InstanceNode.java
  server/src/graql/gremlin/spanningtree/graph/Node.java
  server/src/graql/gremlin/spanningtree/graph/NodeId.java
  server/src/graql/gremlin/spanningtree/graph/SchemaNode.java
  server/src/graql/reasoner/rule/RuleUtils.java
  server/src/server/statistics/KeyspaceStatistics.java
  server/test/graql/gremlin/BUILD
  server/test/graql/gremlin/NodesUtilTest.java
  server/test/graql/gremlin/spanningtree/ChuLiuEdmondsTest.java
  test-integration/graql/reasoner/query/ResolutionPlanIT.java
  test-integration/server/statistics/KeyspaceStatisticsIT.java
Labels: feature

#5212 Statistics - track total Thing count
  server/src/graql/gremlin/spanningtree/graph/InstanceNode.java
  server/src/server/statistics/KeyspaceStatistics.java
  test-integration/server/statistics/KeyspaceStatisticsIT.java
Labels: feature

#5213 Fix logs
  common/config/Config.java
  daemon/executor/Server.java
  test-end-to-end/distribution/DistributionE2EConstants.java
  test-end-to-end/distribution/GraknGraqlCommands_WithARunningGraknE2E.java
Labels: bug

#5216 Update jackson dependencies to tackle security concerns
  daemon/executor/BUILD
  daemon/executor/Executor.java
  daemon/executor/Storage.java
  dependencies/maven/artifacts/com/fasterxml/jackson/module/BUILD
  dependencies/maven/dependencies.bzl
  dependencies/maven/dependencies.yaml
Labels: refactor

#5215 Fix `test-assembly-mac-zip` and `test-assembly-windows-zip` CI jobs
  .circleci/config.yml
  dependencies/graknlabs/dependencies.bzl
Labels: bug, build

#5217 Split version command
  console/GraknConsole.java
  console/test/GraknConsoleIT.java
  daemon/GraknDaemon.java
  test-end-to-end/distribution/GraknGraqlCommands_WithARunningGraknE2E.java
Labels: refactor

#5218 Cleanup unused errors and properties
  common/exception/ErrorMessage.java
  server/conf/grakn.properties
  server/src/server/exception/TransactionException.java
Labels: refactor

#5219 Persist inferred concepts if we explicitly ask to do so
  server/src/graql/executor/QueryExecutor.java
  server/src/graql/executor/WriteExecutor.java
  server/src/graql/executor/property/IsaExecutor.java
  server/src/server/kb/concept/ThingImpl.java
  server/src/server/session/TransactionOLTP.java
  server/src/server/session/cache/TransactionCache.java
  test-integration/server/kb/BUILD
  test-integration/server/kb/TransactionIT.java
Labels: refactor

#5221 Synchronized method in findUnsusedLocalPort in TestServer
  test-integration/rule/GraknTestServer.java
Labels: refactor

#5222 Include LICENSE and README.md in distribution
  BUILD
Labels: build, feature

#5223 Remove estimate for number of inferred concepts
  server/src/graql/gremlin/fragment/LabelFragment.java
  server/src/graql/reasoner/rule/RuleUtils.java
  test-integration/graql/reasoner/query/ResolutionPlanIT.java
Labels: refactor

#5225 Update AttributeDeduplicatorIT
  test-integration/server/AttributeDeduplicatorIT.java
  test-integration/server/BUILD
Labels: refactor

#5226 Refactor handling of value predicates
  common/exception/ErrorMessage.java
  server/src/graql/exception/GraqlQueryException.java
  server/src/graql/executor/property/HasAttributeExecutor.java
  server/src/graql/executor/property/ValueExecutor.java
  server/src/graql/reasoner/atom/Atom.java
  server/src/graql/reasoner/atom/AtomicFactory.java
  server/src/graql/reasoner/atom/binary/AttributeAtom.java
  server/src/graql/reasoner/atom/binary/Binary.java
  server/src/graql/reasoner/atom/predicate/NeqIdPredicate.java
  server/src/graql/reasoner/atom/predicate/NeqValuePredicate.java
  server/src/graql/reasoner/atom/predicate/ValuePredicate.java
  server/src/graql/reasoner/atom/predicate/VariablePredicate.java
  server/src/graql/reasoner/atom/predicate/VariableValuePredicate.java
  server/src/graql/reasoner/query/ReasonerAtomicQuery.java
  server/src/graql/reasoner/query/ReasonerQueryImpl.java
  server/src/graql/reasoner/state/VariableComparisonState.java
  server/src/graql/reasoner/utils/ReasonerUtils.java
  test-integration/graql/reasoner/reasoning/BUILD
  test-integration/graql/reasoner/reasoning/NeqValuePredicateIT.java
  test-integration/graql/reasoner/reasoning/VariableValuePredicateIT.java
Labels: refactor
