Repository typedb/typedb, pull requests merged in 2019-01, with the labels that each got.

#4780 Move RBE config to .bazelrc
  .bazelrc
  .circleci/config.yml
Labels: build, refactor

#4777 Build Linux distributions (deb, rpm)
  .circleci/config.yml
  BUILD
  WORKSPACE
  console/BUILD
  daemon/executor/Server.java
  daemon/executor/Storage.java
  dependencies/distribution/rpm/BUILD
  dependencies/distribution/rpm/grakn-core-bin.spec
  dependencies/distribution/rpm/grakn-core-console.spec
  dependencies/distribution/rpm/grakn-core-server.spec
  grakn
  server/BUILD
  server/conf/grakn.properties
  server/services/cassandra/cassandra.yaml
  test-end-to-end/deduplicator/AttributeDeduplicatorE2E.java
  test-end-to-end/distribution/GraknGraqlCommandsE2E.java
Labels: build, feature, v1.5

#4788 Put distributions into folders in archive; fix #4758
  .circleci/config.yml
  WORKSPACE
  test-end-to-end/client-java/ClientJavaE2EConstants.java
  test-end-to-end/deduplicator/AttributeDeduplicatorE2EConstants.java
  test-end-to-end/distribution/DistributionE2EConstants.java
Labels: build, v1.5

#4786 Use fixed deploy_rpm rule (now works on macOS)
  BUILD
  README.md
  WORKSPACE
  console/BUILD
  server/BUILD
Labels: build

#4792 Update readme for clients
  client-java/README.md
  client-nodejs/README.md
  client_python/README.md
Labels: refactor, v1.5

#4801 Configuration settings bug
  workbase/src/renderer/components/shared/Preferences.vue
Labels: bug, v1.5, workbase

#4808 Remove rule cache
  server/src/graql/internal/reasoner/cache/QueryCacheBase.java
  server/src/graql/internal/reasoner/cache/RuleCache.java
  server/src/graql/internal/reasoner/query/ReasonerAtomicQuery.java
Labels: refactor

#4807 Visualise Schema Concepts in the Visualiser
  workbase/src/renderer/components/SchemaDesign/SchemaUtils.js
  workbase/src/renderer/components/SchemaDesign/store/actions.js
  workbase/src/renderer/components/Visualiser/ContextMenu.vue
  workbase/src/renderer/components/Visualiser/Style.js
  workbase/src/renderer/components/Visualiser/VisualiserGraphBuilder.js
  workbase/src/renderer/components/shared/SharedUtils.js
Labels: feature, v1.5, workbase

#4805 run //workbase:tests-e2e in local mode temporarily until we make it work with RBE
  .circleci/config.yml
Labels: build, v1.6

#4813 Integrate RPM deployment
  BUILD
  WORKSPACE
  console/BUILD
  deployment.properties
  server/BUILD
Labels: build, feature, v1.5

#4812 Pattern negation pt 1.5 - unified negated pattern behaviour
  graql/grammar/Graql.g4
  server/src/graql/admin/Atomic.java
  server/src/graql/admin/ReasonerQuery.java
  server/src/graql/internal/executor/QueryExecutor.java
  server/src/graql/internal/reasoner/ResolutionIterator.java
  server/src/graql/internal/reasoner/atom/AtomicBase.java
  server/src/graql/internal/reasoner/atom/AtomicFactory.java
  server/src/graql/internal/reasoner/atom/NegatedAtomic.java
  server/src/graql/internal/reasoner/query/CompositeQuery.java
  server/src/graql/internal/reasoner/query/ReasonerQueries.java
  server/src/graql/internal/reasoner/query/ReasonerQueryImpl.java
  server/src/graql/internal/reasoner/state/CompositeState.java
  server/src/graql/internal/reasoner/utils/ReasonerUtils.java
  server/src/graql/parser/Parser.java
  server/src/graql/query/Graql.java
  server/src/graql/query/pattern/Conjunction.java
  server/src/graql/query/pattern/Disjunction.java
  server/src/graql/query/pattern/Negation.java
  server/src/graql/query/pattern/Pattern.java
  server/src/graql/query/pattern/statement/Statement.java
  server/src/graql/query/pattern/statement/StatementInstance.java
  server/src/graql/query/pattern/statement/StatementType.java
  server/src/server/kb/ValidateGlobalRules.java
  test-integration/graql/reasoner/query/NegationIT.java
  test-integration/graql/reasoner/stubs/BUILD
  test-integration/graql/reasoner/stubs/recipeTest.gql
Labels: feature, v1.5

#4823 Update link to distribution rules
  BUILD
  WORKSPACE
  client-nodejs/BUILD
  client_python/BUILD
  client_python/grakn/BUILD
  console/BUILD
  dependencies/maven/BUILD
  dependencies/maven/rules.bzl
  server/BUILD
Labels: build, v1.5

#4826 Remove //graql/java:graql deps
  graql/java/BUILD
Labels: build

#4829 Refactor Graql query language library - part 13
  server/src/graql/exception/GraqlQueryException.java
  server/src/graql/internal/executor/property/AbstractExecutor.java
  server/src/graql/internal/executor/property/DataTypeExecutor.java
  server/src/graql/internal/executor/property/HasAttributeExecutor.java
  server/src/graql/internal/executor/property/HasAttributeTypeExecutor.java
  server/src/graql/internal/executor/property/IdExecutor.java
  server/src/graql/internal/executor/property/NeqExecutor.java
  server/src/graql/internal/executor/property/PlaysExecutor.java
  server/src/graql/internal/executor/property/RegexExecutor.java
  server/src/graql/internal/executor/property/RelatesExecutor.java
  server/src/graql/internal/executor/property/ThenExecutor.java
  server/src/graql/internal/executor/property/TypeExecutor.java
  server/src/graql/internal/executor/property/ValueExecutor.java
  server/src/graql/internal/executor/property/WhenExecutor.java
  server/src/graql/internal/gremlin/ConjunctionQuery.java
  server/src/graql/internal/reasoner/plan/GraqlTraversalPlanner.java
  server/src/graql/query/pattern/property/HasAttributeTypeProperty.java
  server/src/graql/query/pattern/property/VarProperty.java
  server/src/graql/query/pattern/statement/Statement.java
  server/src/graql/query/pattern/statement/StatementInstance.java
  test-integration/graql/query/DefineQueryIT.java
Labels: refactor, v1.5

#4833 Refactor Graql query language library - part 14 (in progress)
  common/exception/ErrorMessage.java
  graql/java/exception/ErrorMessage.java
  graql/java/exception/GraqlException.java
  server/src/graql/admin/ReasonerQuery.java
  server/src/graql/answer/ConceptMap.java
  server/src/graql/exception/GraqlQueryException.java
  server/src/graql/internal/executor/QueryExecutor.java
  server/src/graql/internal/executor/property/HasAttributeTypeExecutor.java
  server/src/graql/internal/executor/property/RelationExecutor.java
  server/src/graql/internal/gremlin/ConjunctionQuery.java
  server/src/graql/internal/reasoner/atom/binary/RelationshipAtom.java
  server/src/graql/internal/reasoner/query/ReasonerQueries.java
  server/src/graql/query/DeleteQuery.java
  server/src/graql/query/GetQuery.java
  server/src/graql/query/InsertQuery.java
  server/src/graql/query/MatchClause.java
  server/src/graql/query/pattern/Conjunction.java
  server/src/graql/query/pattern/statement/Statement.java
  server/src/graql/query/pattern/statement/StatementInstance.java
  server/src/graql/query/pattern/statement/StatementType.java
  server/src/server/kb/ValidateGlobalRules.java
  server/src/server/session/TransactionOLTP.java
  server/test/graql/query/BUILD
  server/test/graql/query/ConceptMapTest.java
  test-integration/graql/query/AggregateQueryIT.java
  test-integration/graql/query/BUILD
  test-integration/graql/query/DeleteQueryIT.java
  test-integration/graql/query/InsertQueryIT.java
  test-integration/graql/query/QueryErrorIT.java
Labels: refactor, v1.5

#4843 Update @stackb_rules_proto back to upstream
  dependencies/compilers/dependencies.bzl
Labels: build
