Repository typedb/typedb, pull requests merged in 2019-09, with the labels that each got.

#5397 Remove tx.stream cycles from reasoner
  server/src/graql/executor/QueryExecutor.java
  server/src/graql/reasoner/DisjunctionIterator.java
  server/src/graql/reasoner/query/ReasonerQueryImpl.java
Labels: bug

#5398 Increase server and client storage frame size
  common/config/ConfigKey.java
  server/conf/grakn.properties
  server/src/server/session/JanusGraphFactory.java
Labels: refactor

#5395 Refactor definition and application of semantic difference
  server/src/graql/reasoner/atom/Atom.java
  server/src/graql/reasoner/atom/binary/AttributeAtom.java
  server/src/graql/reasoner/atom/binary/RelationAtom.java
  server/src/graql/reasoner/cache/MultilevelSemanticCache.java
  server/src/graql/reasoner/cache/SemanticDifference.java
  server/src/graql/reasoner/query/ReasonerAtomicQuery.java
  server/src/graql/reasoner/unifier/UnifierType.java
  test-integration/graql/reasoner/query/SemanticDifferenceIT.java
Labels: refactor

#5403 Fix null pointer issue when retrieving meta implicit type hierarchy in RuleCache
  server/src/server/session/cache/RuleCache.java
  test-integration/graql/reasoner/atomic/RuleApplicabilityIT.java
Labels: bug

#5399 Console clean abort and startup failure cleanup
  console/ConsoleSession.java
  console/exception/GraknConsoleException.java
  console/test/BUILD
  console/test/GraknConsoleIT.java
Labels: refactor

#5405 Test Delete With Limit Correctness
  test-integration/graql/query/GraqlDeleteIT.java
Labels: bug, refactor

#5406 Accept relative paths in Grakn Console arguments
  bin/grakn
  daemon/executor/Storage.java
  server/conf/logback.xml
  test-end-to-end/distribution/GraknGraqlCommands_WithARunningGraknE2E.java
Labels: bug

#5413 Remove read lock when fetching specific attribute
  server/src/server/kb/concept/AttributeTypeImpl.java
Labels: refactor

#5415 Revert "remove read lock when fetching specific attribute (#5413)"
  server/src/server/kb/concept/AttributeTypeImpl.java
Labels: refactor

#5412 Re-implement and adapt type sharding to Grakn Core 1.5.x
  common/config/ConfigKey.java
  server/conf/grakn.properties
  server/src/server/kb/Schema.java
  server/src/server/session/SessionFactory.java
  server/src/server/session/SessionImpl.java
  server/src/server/session/TransactionOLTP.java
  server/src/server/session/cache/KeyspaceCache.java
  test-integration/resources/grakn-small-tx-cache.properties
  test-integration/rule/GraknTestServer.java
  test-integration/server/kb/BUILD
  test-integration/server/session/BUILD
  test-integration/server/session/TransactionOLTPIT.java
Labels: bug

#5417 Cache attributes within transaction
  server/src/server/kb/concept/AttributeTypeImpl.java
  server/src/server/session/cache/TransactionCache.java
  test-integration/server/session/cache/TransactionCacheIT.java
Labels: feature

#5416 Extracted //console and //bin to separate repos
  .circleci/config.yml
  BUILD
  WORKSPACE
  bin/BUILD
  bin/grakn
  bin/grakn-docker.sh
  bin/grakn.bat
  config/rpm/BUILD
  config/rpm/grakn-core-bin.spec
  config/rpm/grakn-core-console.spec
  console/BUILD
  console/ConsoleSession.java
  console/GraknConsole.java
  console/LICENSE
  console/VERSION
  console/conf/logback.xml
  console/exception/ErrorMessage.java
  console/exception/GraknConsoleException.java
  console/printer/Printer.java
  console/printer/StringPrinter.java
  console/templates/Version.java
  console/test/BUILD
  console/test/GraknConsoleIT.java
  console/test/file-(with-parentheses).gql
  console/test/invalid-data.cql
  dependencies/graknlabs/dependencies.bzl
  dependencies/maven/artifacts/jline/BUILD
  dependencies/maven/dependencies.bzl
  dependencies/maven/dependencies.yaml
  server/BUILD
  test-end-to-end/distribution/DistributionE2EConstants.java
Labels: refactor

#5418 Skip searching concepts to persist if no inferred concepts exist
  server/src/graql/executor/WriteExecutor.java
  server/src/server/session/cache/TransactionCache.java
Labels: refactor

#5419 Increase commit performance by optimising type sharding
  server/src/server/session/TransactionOLTP.java
  server/src/server/session/cache/KeyspaceCache.java
  server/src/server/statistics/UncomittedStatisticsDelta.java
  test-integration/server/session/TransactionOLTPIT.java
Labels: bug, don't merge

#5420 Use keyspace stats to fetch instance counts
  server/src/graql/executor/ComputeExecutor.java
  test-integration/graql/analytics/GraqlComputeIT.java
Labels: feature, refactor

#5425 Remove copying logs from Windows GCP machine
  .circleci/config.yml
  test/assembly/windows/windows-zip.py
Labels: bug, build

#5426 Install APT packages via Bazel
  .circleci/config.yml
  test-deployment/BUILD
  test-deployment/rules/BUILD
  test-deployment/rules/rules.bzl
  test-deployment/rules/templates/BUILD
  test-deployment/rules/templates/apt_install_command.py
Labels: bug, build

#5422 Optimise instance check in ComputeExecutor
  server/src/graql/executor/ComputeExecutor.java
  server/src/graql/executor/QueryExecutor.java
  server/src/graql/reasoner/DisjunctionIterator.java
  server/src/graql/reasoner/cache/StructuralCache.java
  server/src/graql/reasoner/query/ReasonerQueryImpl.java
  test-integration/server/session/TransactionOLTPIT.java
Labels: refactor

#5428 Fix flaky test related to type sharding in TransactionOLTPIT
  test-integration/server/session/TransactionOLTPIT.java
Labels: bug

#5432 Adapt to latest @graknlabs_bazel_distribution
  WORKSPACE
  config/rpm/grakn-core-server.spec
  dependencies/graknlabs/dependencies.bzl
Labels: bug, build

#5437 Prepare for bazel upgrade
  .bazelrc
Labels: bug, build

#5382 Get rid of DisjunctionIterator
  server/src/graql/executor/QueryExecutor.java
  server/src/graql/reasoner/DisjunctionIterator.java
  server/src/graql/reasoner/query/CompositeQuery.java
  server/src/graql/reasoner/query/ReasonerQueryImpl.java
  server/src/graql/reasoner/query/ResolvableQuery.java
  server/src/server/session/cache/RuleCache.java
  test-integration/graql/reasoner/BUILD
  test-integration/graql/reasoner/ReasoningIT.java
Labels: don't merge, refactor

#5439 Use release-validate-deps to ensure that Grakn depends on released versions of common, console, graql, and protocol
  .circleci/config.yml
Labels: build

#5443 Upgrade to latest @graknlabs_grakn_console
  dependencies/graknlabs/dependencies.bzl
Labels: bug, build

#5444 Disable release-validate-deps for console for until we fix the cyclic dependency
  .circleci/config.yml
Labels: build

#5446 Add release repository to test-deployment-apt and test-deployment-rpm
  .circleci/config.yml
  test/deployment/rpm/test.py
Labels: bug

#5448 Use port 587 instead of the default 25 for sending release-notification
  .circleci/config.yml
Labels: build

#5447 Adds the checkout step in release-notification
  .circleci/config.yml
Labels: build

#5449 Implement Custom Lazy Stream Merging
  dependencies/maven/artifacts/io/vavr/BUILD
  dependencies/maven/dependencies.bzl
  dependencies/maven/dependencies.yaml
  server/BUILD
  server/src/graql/executor/QueryExecutor.java
  server/src/graql/util/LazyMergingStream.java
  server/test/graql/util/BUILD
  server/test/graql/util/LazyMergingStreamTest.java
Labels: refactor

#5434 Transaction, Concept, Element refactor
  server/src/graql/executor/QueryExecutor.java
  server/src/graql/reasoner/ResolutionIterator.java
  server/src/server/kb/ValidateGlobalRules.java
  server/src/server/kb/Validator.java
  server/src/server/kb/concept/AttributeImpl.java
  server/src/server/kb/concept/AttributeTypeImpl.java
  server/src/server/kb/concept/ConceptImpl.java
  server/src/server/kb/concept/ConceptManager.java
  server/src/server/kb/concept/ElementFactory.java
  server/src/server/kb/concept/ElementUtils.java
  server/src/server/kb/concept/EntityImpl.java
  server/src/server/kb/concept/EntityTypeImpl.java
  server/src/server/kb/concept/RelationEdge.java
  server/src/server/kb/concept/RelationImpl.java
  server/src/server/kb/concept/RelationReified.java
  server/src/server/kb/concept/RelationTypeImpl.java
  server/src/server/kb/concept/RoleImpl.java
  server/src/server/kb/concept/RuleImpl.java
  server/src/server/kb/concept/SchemaConceptImpl.java
  server/src/server/kb/concept/ThingImpl.java
  server/src/server/kb/concept/TypeImpl.java
  server/src/server/kb/concept/ValueConverter.java
  server/src/server/kb/structure/AbstractElement.java
  server/src/server/kb/structure/Casting.java
  server/src/server/kb/structure/EdgeElement.java
  server/src/server/kb/structure/Shard.java
  server/src/server/kb/structure/VertexElement.java
  server/src/server/session/ConceptObserver.java
  server/src/server/session/SessionFactory.java
  server/src/server/session/SessionImpl.java
  server/src/server/session/TransactionOLTP.java
  server/src/server/session/cache/CacheProvider.java
  server/src/server/session/cache/KeyspaceSchemaCache.java
  server/src/server/session/cache/RuleCache.java
  server/src/server/session/cache/TransactionCache.java
  test-integration/server/kb/concept/EntityTypeIT.java
  test-integration/server/kb/concept/RelationIT.java
  test-integration/server/kb/structure/EdgeIT.java
  test-integration/server/session/BUILD
  test-integration/server/session/TransactionOLTPIT.java
  test-integration/server/session/cache/KeyspaceSchemaCacheIT.java
Labels: refactor

#5450 AtomicBase Equals Method Fix - Flaky Define test
  server/src/graql/reasoner/atom/AtomicBase.java
  test-integration/graql/reasoner/atomic/AtomicEquivalenceIT.java
Labels: bug

#5452 Fix CI by not specifying exact version of grakn-bin
  test/deployment/apt/templates/apt_install_command.py
Labels: bug, build

#5453 Agree to install packages (for non-interactive prompt)
  test/deployment/apt/templates/apt_install_command.py
Labels: bug, build

#5455 Fix EdgeIT Tests
  server/src/server/session/HadoopGraphFactory.java
  server/src/server/session/SessionImpl.java
  server/src/server/session/TransactionOLTP.java
  test-integration/rule/GraknTestServer.java
  test-integration/server/kb/structure/BUILD
  test-integration/server/kb/structure/EdgeIT.java
Labels: refactor
