Repository typedb/typedb, pull requests merged in 2019-11, with the labels that each got.

#5483 Retrievable Explanations
  common/exception/ErrorMessage.java
  concept/answer/Answer.java
  concept/answer/AnswerGroup.java
  concept/answer/ConceptList.java
  concept/answer/ConceptMap.java
  concept/answer/ConceptSet.java
  concept/answer/Explanation.java
  concept/answer/Numeric.java
  concept/answer/Void.java
  dependencies/graknlabs/dependencies.bzl
  graql/executor/QueryExecutorImpl.java
  graql/reasoner/ReasonerException.java
  graql/reasoner/cache/MultilevelSemanticCache.java
  graql/reasoner/cache/SemanticCache.java
  graql/reasoner/cache/StructuralCache.java
  graql/reasoner/explanation/JoinExplanation.java
  graql/reasoner/explanation/LookupExplanation.java
  graql/reasoner/explanation/RuleExplanation.java
  graql/reasoner/query/ReasonerAtomicQuery.java
  graql/reasoner/query/ReasonerQueryImpl.java
  graql/reasoner/state/AtomicState.java
  graql/reasoner/state/ConjunctiveState.java
  graql/reasoner/state/CumulativeState.java
  graql/reasoner/state/RoleExpansionState.java
  graql/reasoner/unifier/UnifierImpl.java
  kb/concept/util/ConceptUtils.java
  kb/server/Transaction.java
  server/rpc/ResponseBuilder.java
  server/rpc/SessionService.java
  server/session/TransactionOLTP.java
  test-integration/graql/analytics/GraqlComputeIT.java
  test-integration/graql/reasoner/cache/QueryCacheIT.java
  test-integration/graql/reasoner/query/ExplanationIT.java
  test-integration/server/GraknClientIT.java
Labels: feature, refactor

#5485 ConceptMap join refactor
  graql/reasoner/atom/binary/AttributeAtom.java
  graql/reasoner/atom/binary/IsaAtom.java
  graql/reasoner/atom/binary/RelationAtom.java
  graql/reasoner/cache/SemanticDifference.java
  graql/reasoner/state/AtomicState.java
  graql/reasoner/state/CumulativeState.java
  graql/reasoner/state/VariableComparisonState.java
  graql/test/answer/BUILD
  graql/test/answer/ConceptMapTest.java
  kb/concept/util/ConceptUtils.java
Labels: refactor

#5489 Revert Client-Java dependency origin and Expand Reasoner tests
  dependencies/graknlabs/dependencies.bzl
  test-integration/graql/reasoner/benchmark/BenchmarkBigIT.java
Labels: refactor

#5491 Fix key enforcement when dealing with concurrent txs
  concept/impl/ConceptObserver.java
  core/Schema.java
  kb/server/cache/TransactionCache.java
  server/ValidateGlobalRules.java
  server/session/TransactionOLTP.java
  test-integration/server/AttributeUniquenessIT.java
Labels: bug

#5494 Fix output filenames in README.md
  README.md
Labels: bug

#5497 Re use driver
  daemon/GraknDaemon.java
  dependencies/maven/artifacts/com/datastax/cassandra/BUILD
  dependencies/maven/artifacts/com/github/jnr/BUILD
  dependencies/maven/artifacts/org/ow2/asm/BUILD
  dependencies/maven/dependencies.bzl
  dependencies/maven/dependencies.yaml
  graph-hadoop/BUILD
  graph-hadoop/formats/cql/CqlBinaryInputFormat.java
  graph-hadoop/formats/cql/CqlBinaryRecordReader.java
  graph-hadoop/formats/cql/GraknCqlConfigHelper.java
  graph-hadoop/formats/cql/GraknCqlRecordReader.java
  graph-hadoop/formats/cql/GraknInputFormat.java
  graql/BUILD
  server/services/cassandra/cassandra.yaml
  test-integration/resources/cassandra-embedded.yaml
Labels: refactor

#5498 remove input native port
  common/config/ConfigKey.java
  graph-hadoop/BUILD
  graph-hadoop/config/JanusGraphHadoopConfiguration.java
  graph-hadoop/formats/cql/GraknInputFormat.java
  graph-hadoop/formats/util/input/JanusGraphHadoopSetupImpl.java
  server/ServerFactory.java
  server/conf/grakn.properties
  server/rpc/KeyspaceRequestsHandler.java
  server/session/HadoopGraphFactory.java
  server/session/JanusGraphFactory.java
  test-integration/rule/GraknTestServer.java
Labels: refactor

#5499 Dont start Cassandra Thrift server
  daemon/executor/Storage.java
  server/services/cassandra/cassandra.yaml
  test-integration/resources/cassandra-embedded.yaml
Labels: refactor

#5507 Replace unneed Gremlin noop step with a cheaper alternative
  graql/gremlin/fragment/Fragments.java
  graql/gremlin/fragment/IdFragment.java
  graql/gremlin/fragment/InIsaFragment.java
  graql/gremlin/fragment/OutIsaFragment.java
  graql/gremlin/fragment/OutRolePlayerFragment.java
Labels: refactor

#5511 Revise attribute merging mechanism
  concept/impl/AttributeTypeImpl.java
  concept/impl/ConceptManagerImpl.java
  concept/impl/ConceptObserver.java
  core/Schema.java
  kb/server/AttributeManager.java
  server/session/AttributeManagerImpl.java
  server/session/SessionImpl.java
  server/session/TransactionOLTP.java
  test-integration/server/AttributeUniquenessIT.java
  test-integration/server/kb/structure/EdgeIT.java
  test-integration/server/session/AttributeManagerIT.java
  test-integration/server/session/TransactionOLTPIT.java
Labels: feature

#5467 Tag dependency for @graknlabs_grakn_console
  .circleci/config.yml
Labels: bug, build

#5514 Fix RPM deployment test
  test/deployment/rpm/test.py
Labels: bug, build

#5515 Remove shard readlock
  concept/impl/ConceptManagerImpl.java
  kb/server/ShardManager.java
  server/session/SessionImpl.java
  server/session/ShardManagerImpl.java
  server/session/TransactionOLTP.java
  test-integration/server/kb/structure/EdgeIT.java
Labels: feature

#5519 Upgrade @io_bazel_rules_docker to latest version
  WORKSPACE
  dependencies/graknlabs/dependencies.bzl
Labels: bug, build
