Repository typedb/typedb, pull requests merged in 2019-08, with the labels that each got.

#5348 Fix comparisons of variable value predicates
  server/src/graql/reasoner/atom/predicate/Predicate.java
  server/src/graql/reasoner/atom/predicate/ValuePredicate.java
  server/src/graql/reasoner/atom/predicate/VariableValuePredicate.java
  test-integration/graql/reasoner/atomic/AtomicEquivalenceIT.java
Labels: bug

#5354 Make Core extensible by KGMS
  server/src/server/ServerFactory.java
  server/src/server/session/HadoopGraphFactory.java
  server/src/server/session/SessionFactory.java
  server/src/server/session/SessionImpl.java
  test-integration/rule/GraknTestServer.java
Labels: refactor

#5353 Moves version instructions to command usage of `grakn server`
  bin/grakn
  daemon/GraknDaemon.java
Labels: bug

#5359 Track inferred concepts separately to use them for determining persistence on commit
  server/src/graql/executor/WriteExecutor.java
  server/src/server/kb/concept/RelationEdge.java
  server/src/server/kb/concept/RelationReified.java
  server/src/server/kb/concept/ThingImpl.java
  server/src/server/kb/concept/TypeImpl.java
  server/src/server/session/TransactionOLTP.java
  server/src/server/session/cache/TransactionCache.java
  test-integration/server/session/cache/TransactionCacheIT.java
Labels: refactor

#5362 Remove unused keyspaceManager parameter
  server/src/server/ServerFactory.java
  server/src/server/keyspace/KeyspaceManager.java
  server/src/server/session/SessionFactory.java
  test-integration/rule/GraknTestServer.java
Labels: refactor

#5363 Remove ServerID helper class
  server/src/server/Server.java
  server/src/server/ServerFactory.java
  server/src/server/util/ServerID.java
  test-integration/rule/GraknTestServer.java
Labels: refactor

#5365 Add extra validation for copying attribute values in rules
  common/exception/ErrorMessage.java
  server/src/graql/reasoner/atom/binary/AttributeAtom.java
  test-integration/server/kb/BUILD
  test-integration/server/kb/RuleValidationIT.java
Labels: feature

#5366 Include subtypes when determining fruitless rules
  server/src/server/session/cache/RuleCache.java
  test-integration/graql/reasoner/cache/RuleCacheIT.java
Labels: bug

#5368 Make resolution logs not output redundant info
  server/src/graql/reasoner/state/AnswerPropagatorState.java
  server/src/graql/reasoner/state/AtomicState.java
  server/src/graql/reasoner/state/ConjunctiveState.java
Labels: refactor

#5367 Use keyspace statistics for determining whether a type has instances
  server/src/graql/reasoner/atom/Atom.java
  server/src/graql/reasoner/atom/binary/AttributeAtom.java
  server/src/server/session/cache/RuleCache.java
  test-integration/graql/reasoner/cache/RuleCacheIT.java
Labels: refactor

#5369 Do not use keyspace stats for determining instance existence
  server/src/server/session/cache/RuleCache.java
Labels: refactor

#5370 Switch back to cassandrathrift
  common/config/ConfigKey.java
  dependencies/maven/artifacts/com/clearspring/analytics/BUILD
  dependencies/maven/artifacts/com/eaio/uuid/BUILD
  dependencies/maven/artifacts/com/netflix/astyanax/BUILD
  dependencies/maven/artifacts/commons-pool/BUILD
  dependencies/maven/artifacts/io/vavr/BUILD
  dependencies/maven/artifacts/it/unimi/dsi/BUILD
  dependencies/maven/artifacts/org/apache/avro/BUILD
  dependencies/maven/artifacts/org/apache/cassandra/BUILD
  dependencies/maven/artifacts/org/apache/commons/BUILD
  dependencies/maven/artifacts/org/apache/hadoop/BUILD
  dependencies/maven/artifacts/org/apache/spark/BUILD
  dependencies/maven/artifacts/org/apache/thrift/BUILD
  dependencies/maven/artifacts/org/apache/tinkerpop/BUILD
  dependencies/maven/artifacts/org/codehaus/groovy/BUILD
  dependencies/maven/artifacts/org/codehaus/jettison/BUILD
  dependencies/maven/artifacts/org/janusgraph/BUILD
  dependencies/maven/artifacts/org/json4s/BUILD
  dependencies/maven/artifacts/org/scala-lang/BUILD
  dependencies/maven/artifacts/org/scala-lang/modules/BUILD
  dependencies/maven/artifacts/stax/BUILD
  dependencies/maven/dependencies.bzl
  dependencies/maven/dependencies.yaml
  server/BUILD
  server/conf/grakn.properties
  server/resources/default-OLAP-configs.properties
  server/src/server/ServerFactory.java
  server/src/server/session/JanusGraphFactory.java
  server/src/server/session/reader/GraknBinaryInputFormat.java
  server/src/server/session/reader/GraknCassandra3InputFormat.java
  server/src/server/session/reader/GraknCqlBridgeRecordReader.java
  test-integration/rule/GraknTestServer.java
Labels: refactor

#5371 Remove unimplemented KeyspaceService method
  server/src/server/rpc/KeyspaceService.java
Labels: refactor

#5372 Do not print success when failing at loading file
  console/ConsoleSession.java
  console/test/BUILD
  console/test/GraknConsoleIT.java
  console/test/invalid-data.cql
  test-integration/rule/GraknTestServer.java
Labels: bug

#5373 Look for non-trivial instance loops when determining whether reiteration is needed
  server/src/graql/reasoner/rule/RuleUtils.java
  test-integration/graql/reasoner/query/QueryIT.java
Labels: bug

#5375 Always infer types in queries
  server/src/graql/executor/QueryExecutor.java
  server/src/graql/reasoner/cache/StructuralCache.java
Labels: feature

#5376 CI job now waits for an existing apt process to finish before proceeding
  .circleci/config.yml
Labels: build

#5378 Remove grakn.properties GlobalOffline Configuration Options
  server/conf/grakn.properties
Labels: bug

#5379 Refactor keyspace service to allow extension
  server/src/server/ServerFactory.java
  server/src/server/rpc/KeyspaceRequestsHandler.java
  server/src/server/rpc/KeyspaceService.java
  server/src/server/rpc/ServerKeyspaceRequestsHandler.java
  test-integration/rule/GraknTestServer.java
Labels: refactor

#5380 Use persisted values when materialising attributes
  server/src/graql/reasoner/atom/binary/AttributeAtom.java
  test-integration/graql/query/NumberCastingIT.java
  test-integration/graql/reasoner/atomic/AtomicConversionIT.java
  test-integration/graql/reasoner/atomic/BUILD
  test-integration/graql/reasoner/query/MaterialisationIT.java
  test-integration/graql/reasoner/reasoning/AttributeAttachmentIT.java
  test-integration/graql/reasoner/resources/materialisationTest.gql
Labels: bug

#5381 Convert attribute values to persisted data type
  concept/type/AttributeType.java
  server/src/graql/exception/GraqlSemanticException.java
  server/src/graql/executor/property/HasAttributeExecutor.java
  server/src/graql/executor/property/value/ValueAssignment.java
  server/src/graql/executor/property/value/ValueComparison.java
  server/src/graql/executor/property/value/ValueOperation.java
  server/src/graql/reasoner/atom/Atomic.java
  server/src/graql/reasoner/atom/AtomicFactory.java
  server/src/graql/reasoner/atom/binary/AttributeAtom.java
  test-integration/graql/reasoner/atomic/AtomicEquivalenceIT.java
  test-integration/graql/reasoner/atomic/BUILD
  test-integration/graql/reasoner/query/AtomicQueryIT.java
  test-integration/graql/reasoner/query/BUILD
  test-integration/graql/reasoner/query/MaterialisationIT.java
  test-integration/graql/reasoner/resources/genericSchema.gql
  test-integration/server/kb/RuleValidationIT.java
Labels: refactor

#5383 Refactor parsing of ontological atoms
  server/src/graql/executor/property/HasAttributeTypeExecutor.java
  server/src/graql/executor/property/IsaExecutor.java
  server/src/graql/executor/property/PlaysExecutor.java
  server/src/graql/executor/property/RelatesExecutor.java
  server/src/graql/executor/property/SubExecutor.java
  server/src/graql/reasoner/DisjunctionIterator.java
  server/src/graql/reasoner/atom/binary/HasAtom.java
  server/src/graql/reasoner/atom/binary/IsaAtom.java
  server/src/graql/reasoner/atom/binary/OntologicalAtom.java
  server/src/graql/reasoner/atom/binary/PlaysAtom.java
  server/src/graql/reasoner/atom/binary/RelatesAtom.java
  server/src/graql/reasoner/atom/binary/SubAtom.java
  server/src/graql/reasoner/atom/property/DataTypeAtom.java
  server/src/graql/reasoner/atom/property/IsAbstractAtom.java
  server/src/graql/reasoner/atom/property/RegexAtom.java
  test-integration/graql/reasoner/query/AtomicQueryEquivalenceIT.java
Labels: bug

#5386 Fixed an issue where apt-wait may not be called in some jobs
  .circleci/config.yml
Labels: bug, refactor

#5387 Fix an issue in CI caused by the custom flag in the scp command
  test/assembly/windows/windows-zip.py
Labels: build

#5390 Exit with correct exit code on invalid args
  bin/grakn
Labels: bug

#5392 Open up classes, fields and methods needed by KGMS
  server/src/server/session/SessionFactory.java
Labels: refactor

#5393 Open up SharedKeyspaceData cleanup methods needed by KGMS
  server/src/server/session/SessionFactory.java
Labels: refactor

#5394 Fix issue with ids from negation block being propagated into the conjunction
  server/src/graql/reasoner/query/CompositeQuery.java
  test-integration/graql/reasoner/GeoInferenceIT.java
  test-integration/graql/reasoner/query/NegationIT.java
Labels: bug
