Repository typedb/typedb, pull requests merged in 2020-07, with the labels that each got.

#5808 Ensure that two double attributes inserted with the same long value create a single concept
  .circleci/config.yml
  concept/impl/AttributeTypeImpl.java
  concept/manager/ConceptListenerImpl.java
  concept/manager/ConceptManagerImpl.java
  concept/manager/ConceptNotificationChannelImpl.java
  core/AttributeValueConverter.java
  core/Schema.java
  graql/planning/gremlin/sets/AttributeIndexFragmentSet.java
  graql/reasoner/atom/binary/AttributeAtom.java
  graql/reasoner/atom/task/materialise/AttributeMaterialiser.java
  kb/concept/api/GraknConceptException.java
  kb/concept/manager/ConceptListener.java
  kb/concept/manager/ConceptNotificationChannel.java
  kb/graql/exception/GraqlSemanticException.java
  kb/server/cache/TransactionCache.java
  test/integration/concept/AttributeIT.java
  test/integration/graql/reasoner/atomic/AtomicEquivalenceIT.java
  test/integration/graql/reasoner/query/AtomicQueryIT.java
  test/integration/graql/reasoner/query/BUILD
Labels: priority: high, type: bug

#5810 BuildBuddy and beyond!
  .bazelrc
  .bazelversion
  .circleci/config.yml
  dependencies/graknlabs/dependencies.bzl
  dependencies/maven/artifacts.snapshot
Labels: priority: high, type: build

#5812 Update to new artifact rules
  .circleci/config.yml
  BUILD
  WORKSPACE
  config/rpm/grakn-core-all.spec
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/dependencies.bzl
  test/deployment/apt/templates/apt_install_command.py
Labels: priority: high, x: do not merge

#5816 Fix broken resolution tests due to outdated step definitions
  dependencies/graknlabs/dependencies.bzl
  test/behaviour/resolution/ResolutionSteps.java
Labels: type: bug

#5811 Allow tests to print stack traces
  common/exception/GraknException.java
  kb/graql/exception/GraqlSemanticException.java
  test/resources/logback.xml
Labels: priority: high, type: build

#5826 Migrate to updated @graknlabs_dependencies repo
  .bazelrc
  WORKSPACE
  dependencies/graknlabs/dependencies.bzl
  dependencies/maven/artifacts.snapshot
Labels: type: build

#5820 Catch all exceptions thrown in tracing client
  server/rpc/SessionService.java
Labels: type: bug

#5830 Cleanup WORKSPACE file
  WORKSPACE
Labels: priority: high, type: build

#5829 Migrate Type Hierarchy and Generation ITs to BDD tests
  .circleci/config.yml
  dependencies/graknlabs/dependencies.bzl
  test/behaviour/resolution/reasoner/type_generation/BUILD
  test/behaviour/resolution/reasoner/type_generation/TypeGenerationTest.java
  test/behaviour/resolution/reasoner/type_hierarchy/BUILD
  test/behaviour/resolution/reasoner/type_hierarchy/TypeHierarchyTest.java
  test/integration/graql/reasoner/reasoning/BUILD
  test/integration/graql/reasoner/reasoning/TypeGenerationIT.java
  test/integration/graql/reasoner/reasoning/TypeHierarchiesIT.java
  test/integration/graql/reasoner/stubs/BUILD
  test/integration/graql/reasoner/stubs/freshEntityDerivation.gql
  test/integration/graql/reasoner/stubs/freshEntityDerivationFromRelations.gql
  test/integration/graql/reasoner/stubs/freshRelationDerivation.gql
  test/integration/graql/reasoner/stubs/testSet13.gql
  test/integration/graql/reasoner/stubs/testSet19-recursive.gql
  test/integration/graql/reasoner/stubs/testSet19.gql
  test/integration/graql/reasoner/stubs/testSet20.gql
  test/integration/graql/reasoner/stubs/testSet21.gql
  test/integration/graql/reasoner/stubs/testSet8.gql
  test/integration/graql/reasoner/stubs/typeDerivation.gql
  test/integration/graql/reasoner/stubs/typeDerivationFromAttribute.gql
  test/integration/graql/reasoner/stubs/typeDerivationFromRelations.gql
  test/integration/graql/reasoner/stubs/typeDerivationRelationsWithDirect.gql
  test/integration/graql/reasoner/stubs/typeDerivationWithDirect.gql
Labels: priority: low, type: refactor

#5834 Upgrade grabl tracing verison
  dependencies/graknlabs/dependencies.bzl
Labels: type: build

#5832 Downgrade netty
  WORKSPACE
  dependencies/maven/artifacts.bzl
  dependencies/maven/artifacts.snapshot
Labels: priority: high, type: bug

#5836 Add overrides for grabl's transitive netty dependencies
  WORKSPACE
  dependencies/graknlabs/dependencies.bzl
  dependencies/maven/artifacts.snapshot
Labels: priority: high, type: build

#5846 Fix Docker image test
  test/assembly/docker.py
Labels: priority: high, type: bug, type: build

#5843 Refactor reasoner cache tests, RuleScalingIT and SubsumptionIT
  concept/util/ConceptUtils.java
  test/integration/graql/reasoner/atomic/RuleApplicabilityIT.java
  test/integration/graql/reasoner/benchmark/RuleScalingIT.java
  test/integration/graql/reasoner/cache/BUILD
  test/integration/graql/reasoner/cache/QueryCacheIT.java
  test/integration/graql/reasoner/cache/RuleCacheIT.java
  test/integration/graql/reasoner/cache/SemanticDifferenceIT.java
  test/integration/graql/reasoner/graph/BUILD
  test/integration/graql/reasoner/graph/GenericSchemaGraph.java
  test/integration/graql/reasoner/query/AtomicQueryEquivalenceIT.java
  test/integration/graql/reasoner/query/BUILD
  test/integration/graql/reasoner/query/GenerativeOperationalIT.java
  test/integration/graql/reasoner/query/QueryTestUtil.java
  test/integration/graql/reasoner/resources/BUILD
  test/integration/graql/reasoner/resources/genericSchemaRefactored.gql
Labels: priority: high, type: bug, type: refactor

#5827 Refactor atomic and benchmark Reasoner tests
  concept/impl/TypeImpl.java
  core/Schema.java
  graql/reasoner/atom/binary/RelationAtom.java
  graql/reasoner/atom/predicate/IdPredicate.java
  graql/reasoner/atom/task/relate/RelationSemanticProcessor.java
  graql/reasoner/atom/task/relate/TypeAtomSemanticProcessor.java
  graql/reasoner/query/ReasonerQueryFactory.java
  graql/reasoner/query/ReasonerQueryImpl.java
  graql/reasoner/unifier/UnifierComparison.java
  graql/reasoner/unifier/UnifierType.java
  kb/concept/api/Type.java
  kb/graql/reasoner/atom/Atomic.java
  server/ValidateGlobalRules.java
  server/session/TransactionProviderImpl.java
  test/integration/graql/reasoner/atomic/AtomicConversionIT.java
  test/integration/graql/reasoner/atomic/AtomicEquivalenceIT.java
  test/integration/graql/reasoner/atomic/AtomicUnificationIT.java
  test/integration/graql/reasoner/atomic/BUILD
  test/integration/graql/reasoner/atomic/RoleInferenceIT.java
  test/integration/graql/reasoner/atomic/RuleApplicabilityIT.java
  test/integration/graql/reasoner/atomic/TypeInferenceIT.java
  test/integration/graql/reasoner/benchmark/BenchmarkSmallIT.java
  test/integration/graql/reasoner/benchmark/RuleScalingIT.java
  test/integration/graql/reasoner/query/AtomicQueryEquivalenceIT.java
  test/integration/graql/reasoner/query/BUILD
  test/integration/graql/reasoner/query/GenerativeOperationalIT.java
  test/integration/graql/reasoner/resources/BUILD
  test/integration/graql/reasoner/resources/explicitOwnershipRelationApplicabilityTest.gql
  test/integration/graql/reasoner/resources/linearTransitivity.gql
  test/integration/graql/reasoner/resources/multiJoin.gql
  test/integration/graql/reasoner/resources/ruleApplicabilityTest.gql
  test/integration/graql/reasoner/resources/ruleApplicabilityTest2.gql
  test/integration/graql/reasoner/resources/typeInferenceTest.gql
  test/integration/graql/reasoner/resources/unificationWithTypesTest.gql
  test/integration/graql/reasoner/stubs/explanations.gql
  test/integration/server/ValidatorIT.java
  test/rule/TestTransactionProvider.java
Labels: priority: high, type: refactor

#5849 Fix Docker test to be compatible with both Python 2 and Python 3
  test/assembly/docker.py
Labels: priority: high, type: bug, type: build

#5853 Migrate OntologicalQueryIT to BDD
  .circleci/config.yml
  dependencies/graknlabs/dependencies.bzl
  test/behaviour/resolution/reasoner/schema_queries/BUILD
  test/behaviour/resolution/reasoner/schema_queries/SchemaQueriesTest.java
  test/integration/graql/reasoner/query/BUILD
  test/integration/graql/reasoner/query/OntologicalQueryIT.java
Labels: priority: low, type: refactor

#5858 Fix Docker test to wait fixed time
  test/assembly/docker.py
Labels: priority: high

#5838 Add migration export and import to 1.7
  .circleci/config.yml
  .gitignore
  VERSION
  concept/impl/TypeImpl.java
  daemon/BUILD
  daemon/GraknDaemon.java
  daemon/migrate/MigrationClient.java
  daemon/migrate/ProgressPrinter.java
  dependencies/maven/artifacts/com/google/protobuf/BUILD
  dependencies/maven/dependencies.bzl
  dependencies/maven/dependencies.yaml
  kb/concept/api/AttributeType.java
  kb/concept/api/EntityType.java
  kb/concept/api/RelationType.java
  kb/concept/api/Type.java
  server/BUILD
  server/ServerFactory.java
  server/migrate/AbstractJob.java
  server/migrate/Export.java
  server/migrate/Import.java
  server/migrate/Output.java
  server/migrate/OutputFile.java
  server/migrate/Schema.java
  server/migrate/proto/BUILD
  server/migrate/proto/data.proto
  server/migrate/proto/migrate.proto
  server/rpc/MigrateService.java
  server/session/TransactionImpl.java
  test-end-to-end/BUILD
  test-end-to-end/distribution/BUILD
  test-end-to-end/migration/BUILD
  test-end-to-end/migration/MigrationE2E.java
  test-end-to-end/migration/MigrationE2EConstants.java
  test-end-to-end/migration/data/schema-pt2.gql
  test-end-to-end/migration/data/schema.gql
  test-end-to-end/migration/data/schema_export_truth.gql
  test-end-to-end/migration/data/simulation.grakn
Labels: priority: high, type: feature

#5865 Collapse all behavour and integration tests into one CircleCI job
  .circleci/config.yml
  test/behaviour/debug/BUILD
Labels: type: build, type: refactor
