Repository typedb/typedb, pull requests merged in 2020-11, with the labels that each got.

#5890 changed all occurrences of "predicateVar" to "typeVar"
  graql/reasoner/atom/Atom.java
  graql/reasoner/atom/PropertyAtomicFactory.java
  graql/reasoner/atom/binary/AttributeAtom.java
  graql/reasoner/atom/binary/IsaAtom.java
  graql/reasoner/atom/binary/OntologicalAtom.java
  graql/reasoner/atom/binary/RelationAtom.java
  graql/reasoner/atom/binary/TypeAtom.java
  graql/reasoner/atom/predicate/NeqIdPredicate.java
  graql/reasoner/atom/predicate/ValuePredicate.java
  graql/reasoner/atom/predicate/VariablePredicate.java
  graql/reasoner/atom/predicate/VariableValuePredicate.java
  graql/reasoner/atom/task/infer/IsaTypeReasoner.java
  graql/reasoner/atom/task/infer/RelationTypeReasoner.java
  graql/reasoner/atom/task/relate/TypeAtomSemanticProcessor.java
  graql/reasoner/rule/InferenceRule.java
  test/integration/graql/reasoner/atomic/AtomicEquivalenceIT.java
  test/integration/graql/reasoner/query/AtomicQueryUnificationIT.java
Labels: type: refactor

#5895 Fix to Schema Export so that rules are also exported
  .circleci/config.yml
  server/migrate/Schema.java
  test/assembly/MigrationTest.java
  test/assembly/data/schema_export_truth.gql
Labels: type: bug

#5897 Add new configs that speed up JanusGraph
  server/conf/grakn.properties
Labels: priority: medium, type: bug
