Repository typedb/typedb, pull requests merged in 2020-12, with the labels that each got.

#5915 Implement statistics to integrate into query planner
  common/collection/Bytes.java
  graph/DataGraph.java
  graph/SchemaGraph.java
  graph/adjacency/impl/ThingAdjacencyImpl.java
  graph/adjacency/impl/TypeAdjacencyImpl.java
  graph/edge/impl/ThingEdgeImpl.java
  graph/iid/IndexIID.java
  graph/iid/VertexIID.java
  graph/util/Encoding.java
  graph/util/StatisticsBytes.java
  graph/util/Storage.java
  graph/vertex/impl/TypeVertexImpl.java
  rocks/RocksDatabase.java
  rocks/RocksStorage.java
  rocks/RocksTransaction.java
  test/integration/util/Util.java
  traversal/planner/PlannerEdge.java
Labels: type: feature

#5922 Type hinter cleanup
  logic/LogicManager.java
  logic/tool/TypeHinter.java
  rocks/RocksTransaction.java
Labels: type: refactor

#5916 Make DB Cache instead of SchemaGraph borrowable
  common/exception/ErrorMessage.java
  common/exception/GraknException.java
  graph/SchemaGraph.java
  rocks/RocksDatabase.java
  rocks/RocksTransaction.java
Labels: type: refactor

#5927 Remove ErrorMessage assertion error
  common/exception/ErrorMessage.java
  common/exception/GraknException.java
  rocks/RocksDatabase.java
Labels: type: bug

#5924 Update BDD resource clean up strategy
  dependencies/graknlabs/repositories.bzl
  test/behaviour/connection/ConnectionSteps.java
Labels: type: refactor

#5929 Fix attribute IID deserialization off-by-one bug
  graph/iid/VertexIID.java
Labels: type: bug

#5931 Type Hinter will no longer give abstract hints for Thing Variables
  logic/tool/TypeHinter.java
Labels: type: feature

#5930 Background counter thread only needs to run once on server starts
  rocks/RocksDatabase.java
Labels: type: refactor

#5934 Update enum casing in accordance with protocol
  dependencies/graknlabs/repositories.bzl
  server/rpc/concept/ConceptManagerHandler.java
  server/rpc/util/ResponseBuilder.java
Labels: priority: low, type: refactor

#5935 Fix issues with deploying Mac and Windows artifacts
  server/BUILD
Labels: priority: high, type: bug, type: build

#5923 Long lived rule cache and rule validation hooks
  Grakn.java
  common/cache/CommonCache.java
  common/exception/ErrorMessage.java
  graph/SchemaGraph.java
  graph/iid/IndexIID.java
  logic/LogicCache.java
  logic/LogicManager.java
  logic/Rule.java
  logic/Unification.java
  logic/concludable/ConcludableTest.java
  logic/concludable/ConjunctionConcludable.java
  logic/concludable/ThenConcludable.java
  logic/tool/TypeHinter.java
  pattern/constraint/thing/IsaConstraint.java
  pattern/constraint/type/SubConstraint.java
  rocks/RocksDatabase.java
  rocks/RocksTransaction.java
  server/rpc/TransactionRPC.java
  test/integration/BasicTest.java
  test/integration/QueryTest.java
  test/integration/logic/RuleTest.java
  test/integration/logic/TypeHinterTest.java
Labels: priority: high, type: refactor

#5937 Read buffered rules and persisted rules together
  graph/SchemaGraph.java
  logic/LogicCache.java
  logic/LogicManager.java
  logic/tool/TypeHinter.java
Labels: priority: high, type: bug

#5938 Adapt Homebrew deployment for 2.0
  config/brew/grakn-core.rb
Labels: priority: high, type: build

#5939 Fix bug of string length deserialization
  common/collection/Bytes.java
  graph/iid/VertexIID.java
Labels: type: bug

#5942 Make repeated fields pluralised in protocol
  dependencies/graknlabs/repositories.bzl
  server/rpc/concept/ThingHandler.java
  server/rpc/concept/TypeHandler.java
  server/rpc/query/QueryHandler.java
Labels: priority: low, type: refactor

#5943 Fix bug of string length deserialization
  common/collection/Bytes.java
Labels: type: bug

#5945 Fix bug of string length deserialization
  common/collection/Bytes.java
Labels: type: bug

#5946 Fix traversal scopes to return all combinations of role players
  test/behaviour/debug/bugs/high/invalid-casting.feature
  test/integration/traversal/TraversalTest2.java
  traversal/producer/GraphIterator.java
Labels: priority: blocker, type: bug

#5940 Allow importing data into 2.0
  common/exception/ErrorMessage.java
  server/BUILD
  server/GraknServer.java
  server/migrator/Importer.java
  server/migrator/MigratorClient.java
  server/migrator/ProgressPrinter.java
  server/migrator/proto/data.proto
  server/migrator/proto/migrator.proto
  server/rpc/MigratorRPCService.java
  server/util/ServerCommand.java
  server/util/ServerOptions.java
Labels: type: feature

#5947 Disable RBE
  .grabl/automation.yml
Labels: priority: blocker, type: build

#5936 TypeHints moved from Constraint Field to Variable Field
  logic/Rule.java
  logic/concludable/Concludable.java
  logic/concludable/ConjunctionConcludable.java
  logic/tool/TypeHinter.java
  pattern/constraint/thing/IsaConstraint.java
  pattern/constraint/type/SubConstraint.java
  pattern/variable/ThingVariable.java
  pattern/variable/Variable.java
  server/GraknServer.java
  server/util/ServerCommand.java
  test/behaviour/graql/GraqlSteps.java
  test/integration/logic/TypeHinterTest.java
Labels: type: feature

#5951 Force ErrorMessage static constants to all be loaded at bootup
  common/exception/ErrorMessage.java
  rocks/RocksGrakn.java
Labels: type: bug

#5953 Persist statistics snapshot into database
  graph/DataGraph.java
  graph/util/Encoding.java
  graph/util/StatisticsBytes.java
Labels: type: bug

#5954 TypeHints moved from Constraint Field to Variable Field
  logic/Rule.java
  logic/concludable/Concludable.java
  logic/tool/TypeHinter.java
  pattern/constraint/thing/IsaConstraint.java
  pattern/constraint/type/SubConstraint.java
  pattern/variable/ThingVariable.java
  pattern/variable/TypeVariable.java
  pattern/variable/Variable.java
  reasoner/resolution/MockTransaction.java
  reasoner/resolution/framework/Response.java
  server/GraknServer.java
  server/util/ServerCommand.java
  test/behaviour/graql/GraqlSteps.java
  test/integration/logic/TypeHinterTest.java
Labels: type: feature

#5958 Fix logic of setting abstract on attribute types
  common/exception/ErrorMessage.java
  concept/type/impl/AttributeTypeImpl.java
  dependencies/graknlabs/repositories.bzl
Labels: priority: high, type: bug

#5950 Identifier step changes
  dependencies/graknlabs/repositories.bzl
  test/behaviour/connection/database/BUILD
  test/behaviour/connection/database/DatabaseSteps.java
  test/behaviour/connection/session/BUILD
  test/behaviour/connection/session/SessionSteps.java
  test/behaviour/connection/transaction/BUILD
  test/behaviour/connection/transaction/TransactionSteps.java
  test/behaviour/debug/bugs/low/insert-bug.feature
  test/behaviour/debug/bugs/medium/previously-valid-queries.feature
  test/behaviour/debug/bugs/medium/query-planner-bug.feature
  test/behaviour/debug/bugs/medium/role-scoping.feature
  test/behaviour/graql/GraqlSteps.java
  test/behaviour/util/Util.java
Labels: type: refactor

#5944 Update @graknlabs_common which fixed a race condition bug in the actor library
  dependencies/graknlabs/repositories.bzl
Labels: type: bug

#5952 Allow 2.0 to dump currently defined schema and rules
  .grabl/automation.yml
  concept/type/AttributeType.java
  concept/type/EntityType.java
  concept/type/RelationType.java
  concept/type/RoleType.java
  concept/type/ThingType.java
  concept/type/Type.java
  concept/type/impl/AttributeTypeImpl.java
  concept/type/impl/EntityTypeImpl.java
  concept/type/impl/RelationTypeImpl.java
  concept/type/impl/RoleTypeImpl.java
  concept/type/impl/ThingTypeImpl.java
  concept/type/impl/TypeImpl.java
  server/BUILD
  server/GraknServer.java
  server/migrator/Exporter.java
  server/migrator/Importer.java
  server/migrator/MigratorClient.java
  server/migrator/ProgressPrinter.java
  server/migrator/Schema.java
  server/migrator/proto/migrator.proto
  server/rpc/MigratorRPCService.java
  server/util/ServerCommand.java
  test/integration/migrator/BUILD
  test/integration/migrator/MigratorTest.java
  test/integration/migrator/data.grakn
  test/integration/migrator/schema.gql
Labels: type: feature

#5933 Unification from Conjunction Concludables to Head Concludables
  logic/Rule.java
  logic/concludable/Concludable.java
  logic/concludable/ConjunctionConcludable.java
  logic/concludable/ThenConcludable.java
  pattern/constraint/thing/ValueConstraint.java
  pattern/constraint/type/SubConstraint.java
  pattern/variable/ThingVariable.java
  test/integration/logic/BUILD
  test/integration/logic/concludable/UnificationTest.java
Labels: type: feature

#5962 Schema Traversal Tests for Use in Type Resolver
  test/integration/traversal/BUILD
  test/integration/traversal/TraversalTest6.java
Labels: type: feature

#5963 Add bug for failing simulation
  test/integration/traversal/BUILD
  test/integration/traversal/TraversalTest7.java
Labels: type: bug

#5965 Build Java code to be compatible with older Java
  .bazelrc
Labels: priority: high, type: build

#5966 Enable Unification Test in Grabl Automation.
  .grabl/automation.yml
  test/integration/logic/BUILD
Labels: type: feature

#5957 Answer State Tracking
  logic/concludable/ConjunctionConcludable.java
  logic/transformer/Mapping.java
  logic/transformer/Unifier.java
  logic/transformer/VariableTransformer.java
  reasoner/ReasonerProducer.java
  reasoner/resolution/ResolutionRecorder.java
  reasoner/resolution/ResolverRegistry.java
  reasoner/resolution/answer/Aggregator.java
  reasoner/resolution/answer/AnswerState.java
  reasoner/resolution/answer/UnifyingAggregator.java
  reasoner/resolution/framework/Request.java
  reasoner/resolution/framework/ResolutionAnswer.java
  reasoner/resolution/resolver/ConcludableResolver.java
  reasoner/resolution/resolver/ConjunctionResolver.java
  reasoner/resolution/resolver/RootResolver.java
  reasoner/resolution/resolver/RuleResolver.java
  test/integration/logic/concludable/UnificationTest.java
  test/integration/reasoner/ResolutionTest.java
Labels: type: feature

#5960 Resolution Reiteration and rearchitect Resolvers
  reasoner/Reasoner.java
  reasoner/ReasonerProducer.java
  reasoner/resolution/ResolverRegistry.java
  reasoner/resolution/framework/Request.java
  reasoner/resolution/framework/ResolutionAnswer.java
  reasoner/resolution/framework/Resolver.java
  reasoner/resolution/framework/Response.java
  reasoner/resolution/framework/ResponseProducer.java
  reasoner/resolution/resolver/ConcludableResolver.java
  reasoner/resolution/resolver/ConjunctionResolver.java
  reasoner/resolution/resolver/RootResolver.java
  reasoner/resolution/resolver/RuleResolver.java
  test/integration/reasoner/BUILD
  test/integration/reasoner/ResolutionTest.java
Labels: type: feature

#5967 Added traversal test with performance bug
  server/migrator/Importer.java
  test/integration/traversal/BUILD
  test/integration/traversal/TraversalTest8.java
  test/integration/traversal/TraversalTest8/world2.data
  test/integration/traversal/TraversalTest8/world2.gql
Labels: type: bug

#5968 Fix check style
  test/integration/traversal/BUILD
  test/integration/traversal/TraversalTest8/world2.gql
Labels: type: bug

#5969 Propagate errors from our asynchronous producers to consumers
  common/exception/GraknException.java
  common/producer/BaseProducer.java
  common/producer/FilteredProducer.java
  common/producer/MappedProducer.java
  common/producer/Producer.java
  common/producer/ProducerBuffer.java
  test/integration/traversal/BUILD
  traversal/producer/GraphProducer.java
  traversal/producer/VertexProducer.java
Labels: type: bug

#5972 Resolve all labeled variables into `resolvedTypes`
  logic/tool/TypeResolver.java
  pattern/variable/Variable.java
  reasoner/Reasoner.java
  test/integration/logic/TypeResolverTest.java
Labels: priority: high, type: refactor

#5975 Traversal Tests
  test/integration/traversal/TraversalTest6.java
Labels: type: feature

#5976 Enable Type Resolver
  logic/BUILD
  logic/tool/TypeResolver.java
  pattern/BUILD
  pattern/constraint/type/AbstractConstraint.java
  pattern/constraint/type/RegexConstraint.java
  pattern/variable/TypeVariable.java
  reasoner/Reasoner.java
  test/behaviour/debug/debug.feature
  test/integration/logic/TypeResolverTest.java
  test/integration/logic/basic-schema.gql
  test/integration/traversal/TraversalTest6.java
Labels: type: feature

#5978 Implementation of Simple Type Resolving
  .grabl/automation.yml
  logic/LogicCache.java
  logic/tool/TypeResolver.java
  test/behaviour/debug/bugs/medium/query-planner-bug.feature
  test/behaviour/debug/debug.feature
  test/integration/logic/TypeResolverTest.java
Labels: type: feature

#5979 Fix deadlocks caused by recursive produce
  common/parameters/Options.java
  traversal/producer/GraphProducer.java
Labels: type: bug

#5983 Use debug logback configuration for flaky test
  .grabl/automation.yml
  common/test/logback.xml
  test/behaviour/concept/thing/attribute/BUILD
  test/behaviour/concept/thing/entity/BUILD
  test/behaviour/concept/thing/relation/BUILD
  test/behaviour/concept/type/attributetype/BUILD
  test/behaviour/concept/type/entitytype/BUILD
  test/behaviour/concept/type/relationtype/BUILD
  test/behaviour/concept/type/thingtype/BUILD
  test/behaviour/connection/database/BUILD
  test/behaviour/connection/session/BUILD
  test/behaviour/connection/transaction/BUILD
  test/behaviour/debug/BUILD
  test/behaviour/graql/explanation/language/BUILD
  test/behaviour/graql/explanation/reasoner/BUILD
  test/behaviour/graql/language/define/BUILD
  test/behaviour/graql/language/delete/BUILD
  test/behaviour/graql/language/get/BUILD
  test/behaviour/graql/language/insert/BUILD
  test/behaviour/graql/language/match/BUILD
  test/behaviour/graql/language/rule_validation/BUILD
  test/behaviour/graql/language/undefine/BUILD
  test/integration/BUILD
  test/integration/logic/BUILD
Labels: type: refactor

#5984 Remove specialised getSupertypes() implementation in AttributeTypeImpl
  concept/type/impl/AttributeTypeImpl.java
  concept/type/impl/ThingTypeImpl.java
Labels: type: bug

#5974 Adds support for "pluggable" architecture in //rocks package
  dependencies/graknlabs/repositories.bzl
  rocks/BUILD
  rocks/Factory.java
  rocks/RocksDatabase.java
  rocks/RocksDatabaseManager.java
  rocks/RocksFactory.java
  rocks/RocksGrakn.java
  rocks/RocksIterator.java
  rocks/RocksSession.java
  rocks/RocksStorage.java
  rocks/RocksTransaction.java
Labels: type: refactor
