Repository typedb/typedb, pull requests merged in 2020-06, with the labels that each got.

#5732 Update README to mention Bazelisk
  README.md
Labels: type: documentation

#5731 Re-enable copying attribute values across types
  graql/reasoner/atom/task/relate/AttributeSemanticProcessor.java
  graql/reasoner/atom/task/relate/TypeAtomSemanticProcessor.java
  test/integration/graql/reasoner/reasoning/AttributeAttachmentIT.java
  test/integration/graql/reasoner/stubs/resourceAttachment.gql
Labels: priority: blocker, type: bug

#5733 Add platform-specific instructions for installing Bazelisk
  README.md
Labels: type: documentation

#5728 Block gRPC request observer thread to get back-pressure
  .circleci/config.yml
  dependencies/graknlabs/dependencies.bzl
  server/rpc/SessionService.java
Labels: priority: high

#5739 Include protocol datetime instead of date
  dependencies/graknlabs/dependencies.bzl
  server/rpc/ConceptMethod.java
  server/rpc/ResponseBuilder.java
Labels: priority: high, type: refactor

#5740 Remove MutateTest
  .circleci/config.yml
  dependencies/graknlabs/dependencies.bzl
  test/behaviour/graql/language/mutate/BUILD
  test/behaviour/graql/language/mutate/MutateTest.java
Labels: priority: medium, type: refactor

#5744 Bump console dep to be 1.8 compatible
  dependencies/graknlabs/dependencies.bzl
  test/behaviour/graql/language/define/BUILD
  test/common/GraknApplicationTest.java
  test/integration/graql/reasoner/benchmark/BenchmarkBigIT.java
  test/integration/server/GraknClientIT.java
Labels: priority: blocker, type: refactor

#5747 Bump console dependency back to graknlabs
  dependencies/graknlabs/dependencies.bzl
Labels: priority: blocker, type: refactor

#5748 Discord badge added
  README.md
Labels: type: bug

#5751 Fix too eager query completeness acking for queries with negation
  graql/reasoner/ResolutionIterator.java
  test/integration/graql/reasoner/query/NegationIT.java
  test/integration/graql/reasoner/stubs/BUILD
  test/integration/graql/reasoner/stubs/negationCompleteness.gql
Labels: type: bug

#5756 Migrate define ITs to BDD v2
  test/integration/graql/query/GraqlDefineIT.java
Labels: priority: medium, type: refactor

#5757 Graceful session error on server restart
  common/exception/ErrorMessage.java
  kb/server/exception/SessionException.java
  server/rpc/ResponseBuilder.java
  server/rpc/SessionService.java
Labels: priority: medium, type: feature, type: refactor

#5761 Fixed implementation of Thing.keys(types)
  concept/impl/ThingImpl.java
Labels: type: bug

#5765 Update gRPC to 1.29.0
  dependencies/maven/artifacts/io/grpc/BUILD
  dependencies/maven/artifacts/io/netty/BUILD
  dependencies/maven/artifacts/io/opencensus/BUILD
  dependencies/maven/artifacts/io/perfmark/BUILD
  dependencies/maven/dependencies.bzl
  dependencies/maven/dependencies.yaml
Labels: priority: blocker, type: build

#5767 Fix test-assembly-windows-zip by adding python3 to path
  .circleci/config.yml
  .circleci/windows/prepare.bat
Labels: priority: blocker

#5768 Fix test-deployment-rpm due to missing python3 dependencies
  test/deployment/rpm/test.py
Labels: priority: high

#5764 Introduce Explanation Cache and Transaction Query `Explain` Option
  concept/answer/ConceptMap.java
  dependencies/graknlabs/dependencies.bzl
  graql/executor/BUILD
  graql/executor/ExecutorFactoryImpl.java
  graql/executor/QueryExecutorImpl.java
  kb/graql/executor/QueryExecutor.java
  kb/server/Transaction.java
  kb/server/cache/ExplanationCache.java
  server/cache/ExplanationCacheImpl.java
  server/rpc/RequestReader.java
  server/rpc/SessionService.java
  server/session/TransactionImpl.java
  server/session/TransactionProviderImpl.java
  test/behaviour/graql/GraqlSteps.java
  test/integration/graql/analytics/BUILD
  test/integration/graql/analytics/PathIT.java
  test/integration/graql/reasoner/query/BUILD
  test/integration/graql/reasoner/query/ExplanationIT.java
  test/integration/server/GraknClientIT.java
  test/rule/BUILD
  test/rule/TestTransactionProvider.java
Labels: priority: high, type: refactor

#5772 Bump Client-Java Deps
  dependencies/graknlabs/dependencies.bzl
Labels: priority: high, type: build

#5736 Merge changes from 1.7.2
  .circleci/config.yml
  server/rpc/SessionService.java
Labels: priority: high, type: refactor

#5782 Migrate Graql Insert ITs to BDD v2
  dependencies/graknlabs/dependencies.bzl
  test/behaviour/graql/GraqlSteps.java
  test/behaviour/graql/language/insert/BUILD
  test/integration/graql/query/GraqlInsertIT.java
Labels: priority: low, type: refactor

#5778 Update CI image to Ubuntu 16 and bump build tools
  .circleci/config.yml
  dependencies/graknlabs/dependencies.bzl
Labels: priority: high, type: build

#5776 Migrate Graql Delete ITs to BDD v2
  dependencies/graknlabs/dependencies.bzl
  test/behaviour/graql/GraqlSteps.java
  test/behaviour/graql/language/delete/BUILD
  test/integration/graql/query/GraqlDeleteIT.java
Labels: priority: low, type: refactor, x: do not merge

#5785 Migrate Graql Undefine ITs to BDD
  dependencies/graknlabs/dependencies.bzl
  test/behaviour/graql/GraqlSteps.java
  test/behaviour/graql/language/undefine/BUILD
  test/integration/graql/query/GraqlUndefineIT.java
Labels: priority: low, type: refactor

#5797 Migrate axiomatic tests to BDD
  .circleci/config.yml
  WORKSPACE
  dependencies/graknlabs/dependencies.bzl
  test/behaviour/graql/language/insert/BUILD
  test/integration/graql/executor/BUILD
  test/integration/graql/executor/DirectIsaIT.java
  test/integration/graql/executor/DirectSubIT.java
  test/integration/graql/query/BUILD
  test/integration/graql/query/NumberCastingIT.java
  test/integration/graql/query/QueryErrorIT.java
  test/integration/graql/query/QueryValidityIT.java
  test/integration/graql/query/pattern/PatternIT.java
Labels: priority: low, type: refactor
