Repository typedb/typedb, pull requests merged in 2020-05, with the labels that each got.

#5712 Collect `match` clause before execute `delete`
  concept/manager/ConceptListenerImpl.java
  graql/executor/QueryExecutorImpl.java
  test/integration/graql/query/GraqlDeleteIT.java
  test/integration/graql/query/GraqlGetIT.java
  test/integration/graql/query/GraqlInsertIT.java
Labels: type: refactor

#5713 Apply correct tx type for incoming RPC transaction requests
  server/rpc/SessionService.java
  test/integration/server/GraknClientIT.java
Labels: priority: blocker, type: bug

#5709 Explanation Fixes and Behaviour Changes
  concept/answer/ConceptMap.java
  concept/answer/Explanation.java
  graql/reasoner/cache/MultilevelSemanticCache.java
  graql/reasoner/cache/StructuralCache.java
  graql/reasoner/explanation/JoinExplanation.java
  graql/reasoner/explanation/LookupExplanation.java
  graql/reasoner/explanation/RuleExplanation.java
  graql/reasoner/query/ReasonerAtomicQuery.java
  graql/reasoner/query/ReasonerQueryImpl.java
  graql/reasoner/state/AtomicState.java
  graql/reasoner/state/RoleExpansionState.java
  test/integration/graql/reasoner/cache/QueryCacheIT.java
  test/integration/graql/reasoner/query/ExplanationIT.java
  test/integration/server/GraknClientIT.java
Labels: priority: high, type: bug

#5718 Revert VALUE_TYPE to DATA_TYPE
  concept/impl/AttributeTypeImpl.java
  concept/manager/ConceptManagerImpl.java
  core/Schema.java
  graql/planning/gremlin/fragment/ValueTypeFragment.java
  server/session/TransactionImpl.java
Labels: priority: blocker, type: bug

#5699 Fix issue with too eager subgoal propagation for queries with negation
  graql/reasoner/ResolutionIterator.java
  graql/reasoner/state/CompositeState.java
  test-integration/graql/reasoner/stubs/negationGoalPropagation.gql
  test/integration/graql/reasoner/query/NegationIT.java
  test/integration/graql/reasoner/stubs/BUILD
  test/integration/graql/reasoner/stubs/negationGoalPropagation.gql
Labels: type: bug

#5725 Fix test server hanging on startup
  test/rule/GraknTestStorage.java
Labels: priority: low, type: bug

#5729 Bump Graql Dependency and use `DateTime`
  core/AttributeSerialiser.java
  core/AttributeValueConverter.java
  core/Schema.java
  dependencies/graknlabs/dependencies.bzl
  graql/executor/property/ValueTypeExecutor.java
  graql/reasoner/atom/PropertyAtomicFactory.java
  graql/reasoner/atom/property/ValueTypeAtom.java
  kb/concept/api/AttributeType.java
  server/rpc/ResponseBuilder.java
  test/integration/concept/AttributeIT.java
  test/integration/concept/AttributeTypeIT.java
  test/integration/graql/graph/MovieGraph.java
  test/integration/graql/query/NumberCastingIT.java
  test/integration/graql/reasoner/atomic/AtomicEquivalenceIT.java
  test/integration/graql/reasoner/resources/genericSchema.gql
  test/integration/graql/reasoner/resources/materialisationTest.gql
  test/test-fixtures/basic-genealogy.gql
Labels: type: feature, type: refactor
