Repository typedb/typedb, pull requests merged in 2020-04, with the labels that each got.

#5657 Include rule in explanation
  dependencies/graknlabs/dependencies.bzl
  graql/reasoner/explanation/RuleExplanation.java
  graql/reasoner/state/AtomicState.java
  server/rpc/ResponseBuilder.java
  test-integration/graql/reasoner/cache/QueryCacheIT.java
  test-integration/server/GraknClientIT.java
Labels: type: feature

#5666 Role Subtype Unification Test
  graql/reasoner/atom/task/relate/RelationSemanticProcessor.java
  graql/reasoner/unifier/UnifierType.java
  test-integration/graql/reasoner/query/AtomicQueryUnificationIT.java
  test-integration/graql/reasoner/query/SemanticDifferenceIT.java
Labels: priority: medium, status: blocked, type: bug

#5667 Replace role PUT with role Append
  common/util/ListsUtil.java
  concept/impl/RelationEdge.java
  concept/impl/RelationImpl.java
  concept/impl/RelationReified.java
  concept/structure/ElementFactory.java
  concept/util/BUILD
  concept/util/ConceptUtils.java
  graql/executor/QueryExecutorImpl.java
  graql/reasoner/atom/Atom.java
  graql/reasoner/atom/binary/RelationAtom.java
  graql/reasoner/atom/task/materialise/RelationMaterialiser.java
  graql/reasoner/atom/task/relate/AttributeSemanticProcessor.java
  graql/reasoner/atom/task/relate/RelationSemanticProcessor.java
  graql/reasoner/atom/task/relate/TypeAtomSemanticProcessor.java
  graql/reasoner/cache/QueryCacheBase.java
  graql/reasoner/cache/SemanticDifference.java
  graql/reasoner/cache/VariableDefinition.java
  graql/reasoner/explanation/JoinExplanation.java
  graql/reasoner/query/ReasonerAtomicQuery.java
  graql/reasoner/query/ReasonerQueryImpl.java
  graql/reasoner/query/ResolvableQuery.java
  graql/reasoner/state/AtomicStateProducer.java
  graql/reasoner/state/PartialAtomicState.java
  graql/reasoner/tree/ResolutionTree.java
  graql/reasoner/utils/ReasonerUtils.java
  kb/concept/api/Relation.java
  kb/concept/api/RelationStructure.java
  server/rpc/ConceptMethod.java
  test-integration/concept/AttributeIT.java
  test-integration/graql/query/GraqlGetIT.java
  test-integration/graql/reasoner/ReasoningIT.java
  test-integration/graql/reasoner/cache/BUILD
  test-integration/graql/reasoner/cache/SemanticDifferenceIT.java
  test-integration/graql/reasoner/query/AtomicQueryUnificationIT.java
  test-integration/graql/reasoner/query/BUILD
  test-integration/graql/reasoner/query/NegationIT.java
  test-integration/graql/reasoner/reasoning/ValuePredicateIT.java
  test-integration/graql/reasoner/resources/ruleApplicabilityTest.gql
  test-integration/graql/reasoner/stubs/appendingRPs.gql
  test-integration/resources/logback.xml
  test-integration/server/GraknClientIT.java
Labels: priority: high, type: refactor

#5682 Update console dep
  dependencies/graknlabs/dependencies.bzl
Labels: priority: blocker, type: refactor

#5684 Upgrade Bazel to 3.0.0
  .bazelrc
  .bazelversion
  dependencies/graknlabs/dependencies.bzl
Labels: priority: high, type: build

#5685 CI fixes
  .circleci/config.yml
  .circleci/windows/dependencies.config
  .circleci/windows/test-assembly.bat
Labels: priority: high, type: build

#5679 Add support for "1-round-trip" execute queries
  dependencies/graknlabs/dependencies.bzl
  server/rpc/ConceptMethod.java
  server/rpc/ResponseBuilder.java
  server/rpc/SessionService.java
  test-end-to-end/distribution/ConcurrencyE2E.java
  test-integration/graql/reasoner/benchmark/BenchmarkBigIT.java
  test-integration/keyspace/KeyspaceStatisticsIT.java
  test-integration/server/GraknClientIT.java
Labels: priority: high, type: feature, type: refactor

#5686 remove all usage and references to old benchmark
  .circleci/config.yml
  WORKSPACE
  daemon/GraknDaemon.java
  dependencies/graknlabs/dependencies.bzl
  graql/executor/BUILD
  graql/executor/QueryExecutorImpl.java
  graql/executor/WriteExecutorImpl.java
  server/BUILD
  server/Grakn.java
  server/ServerFactory.java
  server/rpc/SessionService.java
  test-end-to-end/distribution/GraknGraqlCommandsE2E.java
  test-integration/graql/query/GraqlDeleteIT.java
Labels: type: refactor

#5687 Fix the path to bash.exe in test-assembly-windows-zip
  .circleci/windows/prepare.bat
  .circleci/windows/test-assembly.bat
Labels: type: build

#5688 Fix release validation for @graknlabs_console
  dependencies/graknlabs/dependencies.bzl
Labels: priority: blocker, type: bug, type: build

#5696 Fix attributes by value always erroring
  server/rpc/SessionService.java
Labels: priority: blocker

#5690 Deletes accept statements instead of variables
  common/exception/ErrorMessage.java
  concept/impl/RelationImpl.java
  concept/impl/RelationReified.java
  concept/impl/RelationTypeImpl.java
  concept/impl/ThingImpl.java
  concept/manager/ConceptListenerImpl.java
  concept/manager/ConceptNotificationChannelImpl.java
  dependencies/graknlabs/dependencies.bzl
  graql/executor/QueryExecutorImpl.java
  graql/executor/WriteExecutorImpl.java
  graql/executor/property/HasAttributeExecutor.java
  graql/executor/property/IdExecutor.java
  graql/executor/property/IsaExecutor.java
  graql/executor/property/PropertyExecutorFactoryImpl.java
  graql/executor/property/RelationExecutor.java
  graql/executor/property/ValueExecutor.java
  graql/reasoner/atom/task/relate/RelationSemanticProcessor.java
  graql/reasoner/query/ReasonerQueryImpl.java
  kb/concept/manager/ConceptListener.java
  kb/concept/manager/ConceptNotificationChannel.java
  kb/graql/exception/GraqlQueryException.java
  kb/graql/exception/GraqlSemanticException.java
  kb/graql/executor/property/PropertyExecutor.java
  kb/graql/executor/property/PropertyExecutorFactory.java
  test-end-to-end/client-java/ClientJavaE2E.java
  test-integration/graql/query/GraqlDeleteIT.java
  test-integration/graql/query/GraqlGetIT.java
  test-integration/graql/query/GraqlInsertIT.java
  test-integration/graql/query/NumberCastingIT.java
  test-integration/graql/query/QueryAdminIT.java
  test-integration/graql/query/QueryBuilderIT.java
  test-integration/graql/query/QueryErrorIT.java
  test-integration/server/AttributeUniquenessIT.java
  test-integration/server/GraknClientIT.java
  test-integration/server/session/TransactionIT.java
  test-integration/server/session/cache/TransactionCacheIT.java
Labels: priority: high, type: feature, type: refactor

#5707 Update circle ci file for incorrect behavior steps
  .circleci/config.yml
  dependencies/graknlabs/dependencies.bzl
  test/behaviour/graql/GraqlSteps.java
Labels: type: build, type: refactor
