Repository typedb/typedb, pull requests merged in 2020-01, with the labels that each got.

#5547 Upgrade grpc to 1.24.1
  .bazelversion
  dependencies/graknlabs/dependencies.bzl
  dependencies/maven/artifacts/com/google/android/BUILD
  dependencies/maven/artifacts/io/grpc/BUILD
  dependencies/maven/artifacts/io/netty/BUILD
  dependencies/maven/artifacts/io/opencensus/BUILD
  dependencies/maven/artifacts/io/perfmark/BUILD
  dependencies/maven/dependencies.bzl
  dependencies/maven/dependencies.yaml
  graql/analytics/BUILD
  graql/executor/BUILD
  graql/planning/BUILD
  graql/reasoner/BUILD
  server/BUILD
  test-integration/rule/BUILD
Labels: build

#5548 Upgrade dependencies
  dependencies/graknlabs/dependencies.bzl
Labels: build

#5552 Disable source code analysis by SonarCloud
  .circleci/config.yml
Labels: build

#5546 Correctly interpret type compatibility and playability when unifying queries
  graql/executor/QueryExecutorImpl.java
  graql/reasoner/atom/binary/Binary.java
  graql/reasoner/atom/binary/RelationAtom.java
  graql/reasoner/query/CompositeQuery.java
  graql/reasoner/query/ReasonerQueryImpl.java
  graql/reasoner/query/ResolvableQuery.java
  graql/reasoner/unifier/UnifierComparison.java
  graql/reasoner/unifier/UnifierType.java
  kb/graql/reasoner/atom/Atomic.java
  kb/graql/reasoner/query/ReasonerQuery.java
  test-integration/graql/reasoner/atomic/RuleApplicabilityIT.java
  test-integration/graql/reasoner/cache/RuleCacheIT.java
  test-integration/graql/reasoner/query/AtomicQueryUnificationIT.java
  test-integration/graql/reasoner/resources/ruleApplicabilityTest.gql
Labels: bug, refactor

#5556 Update Graql and Build Tools
  dependencies/graknlabs/dependencies.bzl
Labels: build

#5558 Fix rule overpruning when rules with negated patterns do not have instances
  concept/manager/ConceptListenerImpl.java
  graql/reasoner/cache/RuleCacheImpl.java
  kb/graql/reasoner/cache/RuleCache.java
  server/session/TransactionImpl.java
  test-integration/graql/reasoner/cache/RuleCacheIT.java
Labels: bug
