Repository typedb/typedb, pull requests merged in 2020-03, with the labels that each got.

#5611 Avoids running `sync-dependencies-snapshot` on user-facing repositories
  .circleci/config.yml
Labels: bug

#5612 Store labels instead of ids in atoms
  graql/reasoner/atom/Atom.java
  graql/reasoner/atom/PropertyAtomicFactory.java
  graql/reasoner/atom/binary/AttributeAtom.java
  graql/reasoner/atom/binary/Binary.java
  graql/reasoner/atom/binary/HasAtom.java
  graql/reasoner/atom/binary/IsaAtom.java
  graql/reasoner/atom/binary/IsaAtomBase.java
  graql/reasoner/atom/binary/OntologicalAtom.java
  graql/reasoner/atom/binary/PlaysAtom.java
  graql/reasoner/atom/binary/RelatesAtom.java
  graql/reasoner/atom/binary/RelationAtom.java
  graql/reasoner/atom/binary/SubAtom.java
  graql/reasoner/atom/binary/TypeAtom.java
  graql/reasoner/atom/task/convert/AttributeAtomConverter.java
  graql/reasoner/atom/task/convert/RelationAtomConverter.java
  graql/reasoner/atom/task/infer/RelationTypeReasoner.java
  graql/reasoner/query/ReasonerQueryImpl.java
  graql/reasoner/utils/ReasonerUtils.java
  kb/graql/reasoner/ReasonerCheckedException.java
  test-integration/graql/reasoner/query/BUILD
  test-integration/graql/reasoner/query/ResolutionPlanIT.java
Labels: refactor

#5615 Atom cleanup
  graql/reasoner/atom/Atom.java
  graql/reasoner/atom/AtomicBase.java
  graql/reasoner/atom/binary/AttributeAtom.java
  graql/reasoner/atom/binary/Binary.java
  graql/reasoner/atom/binary/IsaAtom.java
  graql/reasoner/atom/binary/IsaAtomBase.java
  graql/reasoner/atom/binary/OntologicalAtom.java
  graql/reasoner/atom/binary/RelationAtom.java
  graql/reasoner/atom/binary/TypeAtom.java
  graql/reasoner/atom/task/infer/IsaTypeReasoner.java
  graql/reasoner/atom/task/infer/RelationTypeReasoner.java
  graql/reasoner/atom/task/infer/TypeReasoner.java
  graql/reasoner/atom/task/materialise/AtomMaterialiser.java
  graql/reasoner/atom/task/materialise/AttributeMaterialiser.java
  graql/reasoner/atom/task/materialise/IsaMaterialiser.java
  graql/reasoner/atom/task/materialise/RelationMaterialiser.java
  graql/reasoner/atom/task/relate/AttributeSemanticProcessor.java
  graql/reasoner/atom/task/relate/BasicSemanticProcessor.java
  graql/reasoner/atom/task/relate/BinarySemanticProcessor.java
  graql/reasoner/atom/task/relate/RelationSemanticProcessor.java
  graql/reasoner/atom/task/relate/SemanticProcessor.java
  graql/reasoner/atom/task/validate/AtomValidator.java
  graql/reasoner/atom/task/validate/AttributeAtomValidator.java
  graql/reasoner/atom/task/validate/BasicAtomValidator.java
  graql/reasoner/atom/task/validate/RelationAtomValidator.java
  graql/reasoner/query/ReasonerAtomicQuery.java
  graql/reasoner/state/AtomicState.java
  kb/graql/reasoner/atom/Atomic.java
Labels: refactor

#5618 Flatten AttributeAtom
  graql/reasoner/atom/Atom.java
  graql/reasoner/atom/PropertyAtomicFactory.java
  graql/reasoner/atom/binary/AttributeAtom.java
  graql/reasoner/atom/binary/Binary.java
  graql/reasoner/atom/binary/IsaAtom.java
  graql/reasoner/atom/task/convert/AttributeAtomConverter.java
  graql/reasoner/atom/task/relate/AttributeSemanticProcessor.java
  graql/reasoner/atom/task/validate/AttributeAtomValidator.java
  graql/reasoner/rule/InferenceRule.java
  graql/reasoner/rule/RuleUtils.java
  kb/graql/reasoner/atom/Atomic.java
  test-integration/graql/reasoner/atomic/RuleApplicabilityIT.java
  test-integration/graql/reasoner/resources/ruleApplicabilityTest.gql
Labels: refactor

#5617 Improve validation and disallow more rule types
  common/exception/ErrorMessage.java
  graql/reasoner/atom/Atom.java
  graql/reasoner/atom/binary/AttributeAtom.java
  graql/reasoner/atom/binary/Binary.java
  graql/reasoner/atom/binary/IsaAtom.java
  graql/reasoner/atom/binary/OntologicalAtom.java
  graql/reasoner/atom/binary/RelationAtom.java
  graql/reasoner/atom/task/relate/AttributeSemanticProcessor.java
  graql/reasoner/atom/task/relate/BinarySemanticProcessor.java
  graql/reasoner/atom/task/validate/IsaAtomValidator.java
  graql/reasoner/unifier/UnifierType.java
  kb/graql/reasoner/ReasonerException.java
Labels: bug

#5619 Merge Binary and TypeAtom
  graql/reasoner/atom/binary/Binary.java
  graql/reasoner/atom/binary/IsaAtom.java
  graql/reasoner/atom/binary/OntologicalAtom.java
  graql/reasoner/atom/binary/TypeAtom.java
  graql/reasoner/atom/task/infer/IsaTypeReasoner.java
  graql/reasoner/atom/task/relate/AttributeSemanticProcessor.java
  graql/reasoner/atom/task/relate/RelationSemanticProcessor.java
  graql/reasoner/atom/task/relate/TypeAtomSemanticProcessor.java
Labels: refactor

#5622 Merge ontological atoms
  graql/reasoner/atom/AtomicBase.java
  graql/reasoner/atom/PropertyAtomicFactory.java
  graql/reasoner/atom/binary/HasAtom.java
  graql/reasoner/atom/binary/OntologicalAtom.java
  graql/reasoner/atom/binary/PlaysAtom.java
  graql/reasoner/atom/binary/RelatesAtom.java
  graql/reasoner/atom/binary/SubAtom.java
  graql/reasoner/atom/predicate/Predicate.java
Labels: refactor

#5620 Flatten RelationAtom
  graql/reasoner/atom/Atom.java
  graql/reasoner/atom/binary/AttributeAtom.java
  graql/reasoner/atom/binary/IsaAtom.java
  graql/reasoner/atom/binary/RelationAtom.java
  graql/reasoner/atom/task/convert/RelationAtomConverter.java
  graql/reasoner/atom/task/infer/RelationTypeReasoner.java
  graql/reasoner/atom/task/relate/RelationSemanticProcessor.java
  graql/reasoner/atom/task/validate/RelationAtomValidator.java
  graql/reasoner/query/ReasonerQueryImpl.java
  test-integration/graql/query/GraqlInsertIT.java
  test-integration/graql/query/pattern/PatternIT.java
Labels: refactor

#5625 Remove IsaAtomBase
  graql/reasoner/atom/binary/IsaAtom.java
  graql/reasoner/atom/binary/IsaAtomBase.java
  graql/reasoner/query/ReasonerQueryImpl.java
Labels: refactor

#5624 Cleanup atomic hashing
  graql/reasoner/atom/AtomicEquivalence.java
  graql/reasoner/atom/binary/RelationAtom.java
  graql/reasoner/atom/binary/TypeAtom.java
  graql/reasoner/atom/predicate/IdPredicate.java
  graql/reasoner/atom/predicate/Predicate.java
  graql/reasoner/atom/predicate/ValuePredicate.java
  graql/reasoner/atom/predicate/VariablePredicate.java
  graql/reasoner/atom/predicate/VariableValuePredicate.java
  graql/reasoner/atom/property/DataTypeAtom.java
  graql/reasoner/atom/property/IsAbstractAtom.java
  graql/reasoner/atom/property/RegexAtom.java
Labels: refactor

#5626 Remove BasicSemanticProcessor
  graql/reasoner/atom/Atom.java
  graql/reasoner/atom/AtomicUtil.java
  graql/reasoner/atom/binary/TypeAtom.java
  graql/reasoner/atom/task/relate/AttributeSemanticProcessor.java
  graql/reasoner/atom/task/relate/BasicSemanticProcessor.java
  graql/reasoner/atom/task/relate/TypeAtomSemanticProcessor.java
Labels: refactor

#5630 Do not parse patterns when converting attributes to isas
  graql/reasoner/atom/task/convert/AttributeAtomConverter.java
  graql/reasoner/query/ReasonerQueryImpl.java
Labels: refactor

#5627 Remove excess unification when comparing RelationAtoms
  graql/reasoner/atom/binary/RelationAtom.java
Labels: refactor

#5632 Fix simulation by updating dependencies
  dependencies/graknlabs/dependencies.bzl
Labels: bug

#5638 Fix nondeterministic query resolution by extending requiresReiteration
  graql/reasoner/query/ReasonerQueryImpl.java
Labels: bug

#5641 Fix and Implement Direct Sub
  graql/executor/QueryExecutorImpl.java
  graql/reasoner/atom/PropertyAtomicFactory.java
  graql/reasoner/atom/binary/OntologicalAtom.java
  kb/graql/executor/QueryExecutor.java
  test-integration/graql/executor/BUILD
  test-integration/graql/executor/DirectIsaIT.java
  test-integration/graql/executor/DirectSubIT.java
Labels: bug, refactor

#5636 Merge Query Execution Code Paths for Reasoning and Non-reasoning
  graql/executor/QueryExecutorImpl.java
  graql/reasoner/query/ResolvableQuery.java
  graql/reasoner/state/CompositeState.java
  test-integration/graql/executor/BUILD
  test-integration/graql/reasoner/cache/QueryCacheIT.java
  test-integration/graql/reasoner/query/QueryIT.java
Labels: bug

#5650 Add stricter rule validation for unplayable roles
  common/exception/ErrorMessage.java
  graql/reasoner/atom/task/validate/RelationAtomValidator.java
  test-end-to-end/client-java/ClientJavaE2E.java
  test-integration/server/RuleValidationIT.java
Labels: bug, refactor

#5655 Fix excessive rebuilding
  .bazelrc
Labels: bug, build

#5637 Add grabl tracing
  WORKSPACE
  daemon/GraknDaemon.java
  daemon/executor/Server.java
  dependencies/graknlabs/dependencies.bzl
  server/BUILD
  server/Grakn.java
  server/ServerFactory.java
  server/conf/logback.xml
  server/rpc/SessionService.java
Labels: feature

#5668 Add query profiler based on resolution tree
  graql/reasoner/ResolutionIterator.java
  graql/reasoner/state/AnswerPropagatorState.java
  graql/reasoner/state/AnswerState.java
  graql/reasoner/state/AtomicState.java
  graql/reasoner/state/JoinState.java
  graql/reasoner/state/ResolutionState.java
  graql/reasoner/state/RuleState.java
  graql/reasoner/tree/Node.java
  graql/reasoner/tree/NodeImpl.java
  graql/reasoner/tree/ResolutionTree.java
  graql/reasoner/tree/TreeWriter.java
Labels: type: feature

#5670 Make resolution query profiler output directional
  graql/reasoner/tree/TreeWriter.java
Labels: type: refactor

#5671 Validate resolution profiler answers
  common/exception/ErrorMessage.java
  graql/reasoner/ResolutionIterator.java
  graql/reasoner/state/AnswerPropagatorState.java
  graql/reasoner/state/AnswerState.java
  graql/reasoner/tree/NodeImpl.java
  graql/reasoner/tree/ResolutionTree.java
  kb/graql/reasoner/ReasonerException.java
  test-integration/graql/reasoner/BUILD
  test-integration/graql/reasoner/resources/BUILD
  test-integration/graql/reasoner/resources/logback.xml
Labels: type: refactor

#5673 Defer db completeness check in query cache when fetching
  graql/reasoner/cache/SemanticCache.java
  test-integration/graql/reasoner/cache/QueryCacheIT.java
Labels: type: refactor
