Repository typedb/typedb, pull requests merged in 2021-05, with the labels that each got.

#6317 Made fields and methods RocksDatabaseManager accessible to subclasses
  rocks/RocksDatabaseManager.java
  rocks/RocksTypeDB.java
  server/TypeDBServer.java
Labels: type: refactor

#6313 Rule redefinition deletes old rule completely
  logic/LogicManager.java
  query/Undefiner.java
Labels: priority: high, type: bug

#6324 Reduce OOM by reusing rocks iterators in write transactions
  rocks/RocksStorage.java
Labels: priority: high, type: bug

#6306 Restore ACID transactionality with Consistency Manager
  common/exception/ErrorMessage.java
  concept/thing/impl/ThingImpl.java
  dependencies/vaticle/repositories.bzl
  graph/Graph.java
  graph/ThingGraph.java
  graph/TypeGraph.java
  graph/common/Storage.java
  graph/edge/impl/ThingEdgeImpl.java
  graph/edge/impl/TypeEdgeImpl.java
  graph/structure/impl/RuleStructureImpl.java
  graph/vertex/impl/AttributeVertexImpl.java
  graph/vertex/impl/ThingVertexImpl.java
  graph/vertex/impl/TypeVertexImpl.java
  rocks/RocksDatabase.java
  rocks/RocksFactory.java
  rocks/RocksStorage.java
  rocks/RocksTransaction.java
  test/integration/BUILD
  test/integration/BasicTest.java
  test/integration/ConsistencyTest.java
Labels: priority: blocker, type: bug, type: feature

#6325 Upgrade @rules_antlr usage
  WORKSPACE
  dependencies/vaticle/repositories.bzl
Labels: type: build

#6329 Reintegrate reverted unification tests
  concept/thing/Thing.java
  logic/resolvable/Concludable.java
  logic/resolvable/Unifier.java
  test/integration/logic/resolvable/UnifyRelationConcludableTest.java
Labels: type: refactor

#6320 Concludable and Retrievable Subsumption Caching
  common/poller/AbstractPoller.java
  common/poller/FlatMappedPoller.java
  common/poller/Poller.java
  dependencies/vaticle/repositories.bzl
  logic/resolvable/Unifier.java
  reasoner/ExplanationProducer.java
  reasoner/resolution/Planner.java
  reasoner/resolution/ResolverRegistry.java
  reasoner/resolution/answer/AnswerState.java
  reasoner/resolution/answer/AnswerStateImpl.java
  reasoner/resolution/answer/AnswerStateTest.java
  reasoner/resolution/framework/AnswerCache.java
  reasoner/resolution/framework/RequestState.java
  reasoner/resolution/framework/Resolver.java
  reasoner/resolution/resolver/CompoundResolver.java
  reasoner/resolution/resolver/ConcludableResolver.java
  reasoner/resolution/resolver/ConclusionResolver.java
  reasoner/resolution/resolver/ConditionResolver.java
  reasoner/resolution/resolver/ConjunctionResolver.java
  reasoner/resolution/resolver/DisjunctionResolver.java
  reasoner/resolution/resolver/NegationResolver.java
  reasoner/resolution/resolver/RetrievableResolver.java
  reasoner/resolution/resolver/RootResolver.java
  test/integration/logic/resolvable/UnifyAttributeConcludableTest.java
  test/integration/logic/resolvable/UnifyHasConcludableTest.java
  test/integration/logic/resolvable/UnifyIsaConcludableTest.java
  test/integration/logic/resolvable/UnifyRelationConcludableTest.java
  test/integration/reasoner/resolution/PlannerTest.java
Labels: priority: high, type: feature, x: do not merge

#6330 Statistics background thread catches correct conflict codes
  rocks/RocksDatabase.java
  test/integration/BasicTest.java
Labels: priority: blocker, type: bug

#6328 Implement viewable byte array wrapper class
  common/collection/ByteArray.java
  common/collection/Bytes.java
  concept/ConceptManager.java
  concept/thing/Thing.java
  concept/thing/impl/ThingImpl.java
  concept/type/impl/ThingTypeImpl.java
  graph/ThingGraph.java
  graph/TypeGraph.java
  graph/adjacency/impl/ThingAdjacencyImpl.java
  graph/adjacency/impl/TypeAdjacencyImpl.java
  graph/common/Encoding.java
  graph/common/KeyGenerator.java
  graph/common/StatisticsBytes.java
  graph/common/Storage.java
  graph/edge/impl/ThingEdgeImpl.java
  graph/iid/EdgeIID.java
  graph/iid/IID.java
  graph/iid/IndexIID.java
  graph/iid/InfixIID.java
  graph/iid/PrefixIID.java
  graph/iid/StructureIID.java
  graph/iid/SuffixIID.java
  graph/iid/VertexIID.java
  graph/structure/impl/RuleStructureImpl.java
  graph/vertex/impl/TypeVertexImpl.java
  migrator/DataExporter.java
  migrator/DataImporter.java
  pattern/Conjunction.java
  pattern/constraint/thing/IIDConstraint.java
  pattern/variable/ThingVariable.java
  reasoner/resolution/framework/Resolver.java
  rocks/RocksDatabase.java
  rocks/RocksIterator.java
  rocks/RocksStorage.java
  server/common/RequestReader.java
  server/common/ResponseBuilder.java
  server/concept/ConceptService.java
  server/concept/ThingService.java
  test/behaviour/typeql/BUILD
  test/behaviour/typeql/TypeQLSteps.java
  test/integration/logic/resolvable/UnifyAttributeConcludableTest.java
  test/integration/logic/resolvable/UnifyHasConcludableTest.java
  test/integration/logic/resolvable/UnifyIsaConcludableTest.java
  test/integration/logic/resolvable/UnifyRelationConcludableTest.java
  traversal/Traversal.java
Labels: priority: high, type: refactor

#6332 Request reiteration status with explicit resolver messages
  .grabl/automation.yml
  dependencies/vaticle/repositories.bzl
  reasoner/ExplanationProducer.java
  reasoner/ReasonerProducer.java
  reasoner/resolution/ResolverRegistry.java
  reasoner/resolution/answer/AnswerState.java
  reasoner/resolution/answer/AnswerStateImpl.java
  reasoner/resolution/answer/AnswerStateTest.java
  reasoner/resolution/framework/AnswerCache.java
  reasoner/resolution/framework/ReiterationQuery.java
  reasoner/resolution/framework/RequestState.java
  reasoner/resolution/resolver/ConcludableResolver.java
  reasoner/resolution/resolver/RetrievableResolver.java
  reasoner/resolution/resolver/RootResolver.java
  test/integration/reasoner/resolution/ReiterationTest.java
Labels: priority: high, type: bug

#6334 Fix Homebrew deployment
  .grabl/automation.yml
Labels: priority: blocker, type: bug, type: build

#6337 Fix TypeDB formula name for Homebrew
  config/brew/typedb.rb
Labels: priority: blocker, type: bug, type: build

#6339 Simplify resolver answer cache execution flow
  reasoner/resolution/framework/AnswerCache.java
  reasoner/resolution/resolver/ConcludableResolver.java
  reasoner/resolution/resolver/RetrievableResolver.java
Labels: priority: medium, type: refactor

#6338 Unifiers include type requirements for all variables
  logic/resolvable/Concludable.java
  logic/resolvable/Unifier.java
  reasoner/resolution/framework/RequestState.java
  reasoner/resolution/resolver/ConcludableResolver.java
  test/integration/logic/resolvable/UnifyAttributeConcludableTest.java
  test/integration/logic/resolvable/UnifyHasConcludableTest.java
  test/integration/logic/resolvable/UnifyIsaConcludableTest.java
  test/integration/logic/resolvable/UnifyRelationConcludableTest.java
  test/integration/reasoner/ReasonerTest.java
Labels: priority: blocker
