Repository typedb/typedb, pull requests merged in 2021-11, with the labels that each got.

#6482 Update release notes script
  .grabl/automation.yml
  dependencies/vaticle/repositories.bzl
Labels: type: build, priority: blocker

#6479 Upgrade RocksDB to 6.21.1
  dependencies/maven/artifacts.bzl
  dependencies/maven/artifacts.snapshot
  dependencies/vaticle/repositories.bzl
  migrator/BUILD
  rocks/BUILD
  server/BUILD
Labels: type: build, priority: high

#6475 Validate and encode strings as UTF-8
  .grabl/automation.yml
  common/collection/ByteArray.java
  common/exception/ErrorMessage.java
  test/integration/BUILD
  test/integration/StringAttributeTest.java
Labels: type: bug, priority: blocker

#6483 Correctly apply multiple negations with the same variables
  dependencies/vaticle/repositories.bzl
  logic/Rule.java
  logic/resolvable/Concludable.java
  pattern/Conjunction.java
  pattern/Disjunction.java
  reasoner/Reasoner.java
Labels: type: bug, priority: high

#6485 Upgrade @vaticle_dependencies
  dependencies/vaticle/repositories.bzl
  test/integration/StringAttributeTest.java
Labels: type: build

#6484 Validate encoding version and compress encoding ranges
  common/exception/ErrorMessage.java
  graph/common/Encoding.java
  rocks/RocksDatabase.java
  rocks/RocksStorage.java
Labels: type: feature, priority: high

#6486 Clarify transaction consistency error messages
  common/exception/ErrorMessage.java
Labels: type: refactor, priority: medium
