Repository typedb/typedb, pull requests merged in 2021-06, with the labels that each got.

#6344 Disallow users from creating / accessing 'reserved' databases
  common/exception/ErrorMessage.java
  dependencies/vaticle/artifacts.bzl
  dependencies/vaticle/repositories.bzl
  rocks/RocksDatabaseManager.java
Labels: type: feature

#6351 Make RocksDatabaseManager not usable if it's already closed
  common/exception/ErrorMessage.java
  rocks/RocksDatabase.java
  rocks/RocksDatabaseManager.java
Labels: type: bug

#6352 Deploy artifacts that include Console
  .grabl/automation.yml
  BUILD
Labels: priority: blocker, type: build

#6363 Ensure that the RPC prefetch size is at least 1
  server/TransactionService.java
Labels: priority: medium, type: bug

#6364 RPC prefetch size must be least 1
  common/exception/ErrorMessage.java
  server/TransactionService.java
Labels: priority: medium, type: bug

#6366 Enable reasoner to handle reflexive relations
  logic/resolvable/Unifier.java
Labels: priority: high, type: bug

#6347 Type casting errors include type label
  concept/type/impl/TypeImpl.java
Labels: priority: medium, type: refactor

#6369 Delete and Insert queries are validated once rather than per answer
  dependencies/vaticle/repositories.bzl
  query/Deleter.java
  query/Inserter.java
  query/Updater.java
Labels: priority: medium, type: bug

#6375 Address RocksDB iterator assertion error due to no keys
  rocks/RocksStorage.java
Labels: priority: high, type: bug

#6373 Streamline statistics counting and fix ACID with no RocksDB writes
  graph/ThingGraph.java
  graph/common/Encoding.java
  graph/vertex/impl/AttributeVertexImpl.java
  rocks/RocksDatabase.java
  rocks/RocksStorage.java
Labels: priority: high, type: refactor

#6378 Allow tests to include anonymous identifiers in filter
  reasoner/Reasoner.java
  reasoner/ReasonerProducer.java
  reasoner/resolution/answer/AnswerState.java
  reasoner/resolution/answer/AnswerStateImpl.java
  reasoner/resolution/answer/AnswerStateTest.java
  test/integration/reasoner/resolution/ReiterationTest.java
  test/integration/reasoner/resolution/ResolutionTest.java
Labels: priority: high, type: refactor

#6341 Hugely reduce transaction memory usage
  concept/ConceptManager.java
  concept/thing/impl/AttributeImpl.java
  concept/thing/impl/EntityImpl.java
  concept/thing/impl/RelationImpl.java
  concept/thing/impl/RoleImpl.java
  concept/thing/impl/ThingImpl.java
  concept/type/impl/AttributeTypeImpl.java
  concept/type/impl/EntityTypeImpl.java
  concept/type/impl/RelationTypeImpl.java
  concept/type/impl/RoleTypeImpl.java
  concept/type/impl/ThingTypeImpl.java
  concept/type/impl/TypeImpl.java
  graph/ThingGraph.java
  graph/adjacency/ThingAdjacency.java
  graph/adjacency/impl/ThingAdjacencyImpl.java
  graph/edge/ThingEdge.java
  graph/edge/impl/ThingEdgeImpl.java
  graph/iid/IID.java
  graph/vertex/AttributeVertex.java
  graph/vertex/ThingVertex.java
  graph/vertex/TypeVertex.java
  graph/vertex/Vertex.java
  graph/vertex/impl/AttributeVertexImpl.java
  graph/vertex/impl/ThingVertexImpl.java
  graph/vertex/impl/TypeVertexImpl.java
  graph/vertex/impl/VertexImpl.java
  logic/Rule.java
  logic/resolvable/Concludable.java
  rocks/RocksStorage.java
  rocks/RocksTypeDB.java
  traversal/procedure/GraphProcedure.java
  traversal/procedure/ProcedureEdge.java
  traversal/procedure/ProcedureVertex.java
  traversal/procedure/VertexProcedure.java
Labels: priority: high, type: bug, type: refactor

#6380 Reduce traversal and resolver caches memory overhead
  common/cache/CommonCache.java
  logic/LogicCache.java
  logic/tool/TypeResolver.java
  traversal/Traversal.java
  traversal/TraversalCache.java
  traversal/TraversalEngine.java
  traversal/planner/GraphPlanner.java
  traversal/planner/Planner.java
Labels: priority: high, type: bug

#6385 Assert graph planner objective exists
  traversal/planner/GraphPlanner.java
Labels: priority: high, type: refactor

#6386 Overridable logger
  dependencies/vaticle/repositories.bzl
  rocks/RocksDatabase.java
  rocks/RocksSession.java
  rocks/RocksStorage.java
  rocks/RocksTypeDB.java
  server/TypeDBServer.java
Labels: priority: high, type: refactor
