Repository typedb/typedb, pull requests merged in 2021-03, with the labels that each got.

#6219 Rule materialisation lookups should use relation type
  logic/Rule.java
  reasoner/resolution/answer/AnswerState.java
  reasoner/resolution/framework/ResolutionTracer.java
  test/integration/reasoner/ReasonerTest.java
Labels: priority: high, type: bug

#6218 Remove offset and limit from reasoner
  reasoner/Reasoner.java
  reasoner/ReasonerProducer.java
  reasoner/resolution/ResolverRegistry.java
  reasoner/resolution/resolver/ConjunctionResolver.java
  reasoner/resolution/resolver/DisjunctionResolver.java
  reasoner/resolution/resolver/RootResolver.java
  test/integration/reasoner/ReasonerTest.java
  test/integration/reasoner/ReiterationTest.java
  test/integration/reasoner/ResolutionTest.java
Labels: priority: medium, type: bug

#6225 Type resolver marks non-schema queries as not coherent
  common/exception/ErrorMessage.java
  logic/Rule.java
  logic/tool/TypeResolver.java
  pattern/Conjunction.java
  pattern/Disjunction.java
  pattern/Negation.java
  reasoner/Reasoner.java
  test/integration/logic/TypeResolverTest.java
  test/integration/logic/resolvable/Util.java
  test/integration/reasoner/BUILD
  test/integration/reasoner/resolution/PlannerTest.java
  test/integration/reasoner/resolution/ReiterationTest.java
  test/integration/reasoner/resolution/ResolutionTest.java
  test/integration/reasoner/resolution/Util.java
Labels: priority: medium, type: refactor

#6229 Parallel configuration is available in all options
  common/parameters/Options.java
  dependencies/graknlabs/repositories.bzl
  server/rpc/common/RequestReader.java
Labels: priority: high

#6230 Fully remove rule indexes when undefining a rule
  graph/SchemaGraph.java
  reasoner/Reasoner.java
  rocks/RocksStorage.java
  test/integration/QueryTest.java
Labels: priority: high, type: bug

#6231 Fix rule satisfiability validation
  common/exception/ErrorMessage.java
  logic/Rule.java
  logic/resolvable/Concludable.java
  pattern/Conjunction.java
  pattern/variable/Variable.java
  test/integration/logic/BUILD
  test/integration/logic/RuleTest.java
  test/integration/logic/TypeResolverTest.java
  test/integration/logic/resolvable/UnifyRelationConcludableTest.java
  test/integration/reasoner/resolution/PlannerTest.java
Labels: priority: high, type: bug

#6234 Upgrade @graknlabs_dependencies to the latest one
  dependencies/graknlabs/repositories.bzl
Labels: priority: high, type: build

#6233 Prevent rare segfaults with storage read-write lock
  rocks/RocksStorage.java
Labels: priority: blocker, type: bug

#6239 Include the Type of each Thing sent over RPC
  dependencies/graknlabs/repositories.bzl
  server/common/ResponseBuilder.java
Labels: priority: high, type: feature

#6240 Use isX, not 'instanceof' to check type encodings
  logic/resolvable/Unifier.java
  migrator/Exporter.java
  migrator/SchemaExporter.java
  query/Definer.java
  query/Inserter.java
  query/Undefiner.java
  server/common/ResponseBuilder.java
  server/concept/TypeService.java
  test/behaviour/graql/GraqlSteps.java
Labels: priority: medium, type: refactor

#6242 Traversal must clear scoped roles when backtracking closures
  .grabl/automation.yml
  dependencies/graknlabs/repositories.bzl
  test/integration/traversal/BUILD
  test/integration/traversal/TraversalTest.java
  traversal/iterator/GraphIterator.java
Labels: priority: high, type: bug

#6238 Implement rule negation validation to prevent contradictions
  .grabl/automation.yml
  common/exception/ErrorMessage.java
  graph/SchemaGraph.java
  logic/LogicManager.java
  logic/Rule.java
  logic/resolvable/Concludable.java
  logic/tool/TypeResolver.java
  reasoner/resolution/ResolverRegistry.java
  reasoner/resolution/resolver/ConclusionResolver.java
  reasoner/resolution/resolver/ConditionResolver.java
  reasoner/resolution/resolver/ConjunctionResolver.java
  reasoner/resolution/resolver/DisjunctionResolver.java
  reasoner/resolution/resolver/RootResolver.java
  test/integration/BasicTest.java
  test/integration/logic/RuleTest.java
  test/integration/logic/TypeResolverTest.java
Labels: priority: high, type: feature

#6244 All conjunction resolvers deduplicate concept maps
  reasoner/resolution/resolver/ConditionResolver.java
  reasoner/resolution/resolver/ConjunctionResolver.java
  reasoner/resolution/resolver/RootResolver.java
Labels: priority: high, type: refactor

#6243 Optimise resolution of fully bound concludables
  reasoner/resolution/resolver/ConcludableResolver.java
  reasoner/resolution/resolver/ConditionResolver.java
  reasoner/resolution/resolver/ConjunctionResolver.java
  reasoner/resolution/resolver/NegationResolver.java
  reasoner/resolution/resolver/RootResolver.java
Labels: priority: high, type: feature

#6247 Upgrade @graknlabs_dependencies to the latest one
  dependencies/graknlabs/repositories.bzl
Labels: priority: high, type: build

#6251 Detect starting under incompatible Java version
  common/exception/ErrorMessage.java
  dependencies/graknlabs/repositories.bzl
  server/GraknServer.java
Labels: priority: high, type: bug

#6252 Bump Java version for macOS assembly test
  .circleci/config.yml
Labels: priority: low, type: bug, type: build

#6256 RPC Service Architecture Refactor
  .grabl/automation.yml
  Grakn.java
  common/parameters/Label.java
  concept/thing/Relation.java
  concept/thing/Thing.java
  concept/thing/impl/RelationImpl.java
  concept/thing/impl/ThingImpl.java
  dependencies/graknlabs/repositories.bzl
  migrator/proto/data.proto
  migrator/proto/migrator.proto
  server/GraknServer.java
  server/GraknService.java
  server/TransactionService.java
  server/common/RequestReader.java
  server/common/ResponseBuilder.java
  server/concept/ConceptService.java
  server/concept/ThingService.java
  server/concept/TypeService.java
  server/logic/LogicService.java
  server/logic/RuleService.java
  server/query/QueryService.java
Labels: priority: high, type: refactor

#6259 Refactor GraknServer to be open for extension
  server/GraknServer.java
  server/common/ServerCommand.java
  server/common/Util.java
Labels: type: refactor

#6254 Validate labels when creating Types
  concept/BUILD
  concept/type/impl/TypeImpl.java
  dependencies/graknlabs/repositories.bzl
Labels: priority: medium, type: feature

#6263 Always use the little endian to represent merge operator numbers
  common/collection/Bytes.java
Labels: type: bug

#6264 Introduce ByteMap to manage indexes in Encoding class
  graph/DataGraph.java
  graph/common/Encoding.java
Labels: type: bug, type: refactor

#6265 Implement Explanations
  concept/BUILD
  concept/answer/ConceptMap.java
  concept/thing/Thing.java
  concept/thing/impl/ThingImpl.java
  logic/Rule.java
  logic/resolvable/Concludable.java
  pattern/Conjunction.java
  pattern/ConjunctionTest.java
  pattern/variable/Variable.java
  query/BUILD
  query/QueryManager.java
  reasoner/ExplainablesManager.java
  reasoner/ExplanationProducer.java
  reasoner/Reasoner.java
  reasoner/ReasonerProducer.java
  reasoner/resolution/ResolutionRecorder.java
  reasoner/resolution/ResolverRegistry.java
  reasoner/resolution/answer/AnswerState.java
  reasoner/resolution/answer/AnswerStateImpl.java
  reasoner/resolution/answer/AnswerStateTest.java
  reasoner/resolution/answer/Explanation.java
  reasoner/resolution/answer/Mapping.java
  reasoner/resolution/framework/Request.java
  reasoner/resolution/framework/Resolver.java
  reasoner/resolution/framework/Response.java
  reasoner/resolution/framework/ResponseProducer.java
  reasoner/resolution/resolver/CompoundResolver.java
  reasoner/resolution/resolver/ConcludableResolver.java
  reasoner/resolution/resolver/ConclusionResolver.java
  reasoner/resolution/resolver/ConditionResolver.java
  reasoner/resolution/resolver/ConjunctionResolver.java
  reasoner/resolution/resolver/DisjunctionResolver.java
  reasoner/resolution/resolver/NegationResolver.java
  reasoner/resolution/resolver/RetrievableResolver.java
  reasoner/resolution/resolver/RootResolver.java
  test/integration/reasoner/BUILD
  test/integration/reasoner/ExplanationTest.java
  test/integration/reasoner/resolution/ReiterationTest.java
  test/integration/reasoner/resolution/ResolutionTest.java
Labels: priority: high, type: feature

#6266 Update behaviour, adding new Graql Match BDD steps
  dependencies/graknlabs/repositories.bzl
  test/behaviour/graql/GraqlSteps.java
Labels: priority: medium, type: refactor

#6271 Explanations rpc
  .grabl/automation.yml
  concept/answer/ConceptMap.java
  dependencies/graknlabs/repositories.bzl
  reasoner/BUILD
  reasoner/ExplainablesManager.java
  reasoner/resolution/answer/Mapping.java
  server/BUILD
  server/common/ResponseBuilder.java
  server/logic/RuleService.java
  server/query/QueryService.java
  test/integration/reasoner/ExplanationTest.java
  test/integration/reasoner/resolution/ResolutionTest.java
  traversal/common/Identifier.java
Labels: priority: high

#6272 Add Java 11+ requirement to README
  README.md
Labels: type: documentation

#6273 Disable reasoner/inference by default
  common/parameters/Options.java
  test/behaviour/connection/transaction/TransactionSteps.java
  test/integration/reasoner/ExplanationTest.java
  test/integration/reasoner/resolution/ReiterationTest.java
Labels: priority: high, type: refactor

#6274 Optimise RocksDB configuration for higher write throughput
  rocks/RocksGrakn.java
Labels: priority: high, type: feature

#6275 Fix constraint cloning error
  logic/resolvable/Retrievable.java
Labels: type: bug
