Repository typedb/typedb, pull requests merged in 2021-01, with the labels that each got.

#5985 Switch image back to default Ubuntu 20.04
  .grabl/automation.yml
Labels: type: build, type: refactor

#5973 Extract Retrievables from a Conjunction
  .grabl/automation.yml
  logic/BUILD
  logic/Rule.java
  logic/resolvable/Concludable.java
  logic/resolvable/Retrievable.java
  logic/resolvable/RetrievableTest.java
  pattern/constraint/thing/HasConstraint.java
  pattern/constraint/thing/IsConstraint.java
  pattern/constraint/thing/IsaConstraint.java
  pattern/constraint/thing/RelationConstraint.java
  pattern/constraint/thing/ValueConstraint.java
  pattern/constraint/type/IsConstraint.java
  pattern/constraint/type/OwnsConstraint.java
  pattern/constraint/type/PlaysConstraint.java
  pattern/constraint/type/RelatesConstraint.java
  pattern/constraint/type/SubConstraint.java
  pattern/variable/ThingVariable.java
  pattern/variable/TypeVariable.java
  pattern/variable/Variable.java
  reasoner/resolution/ResolverRegistry.java
  reasoner/resolution/resolver/ConcludableResolver.java
  reasoner/resolution/resolver/ResolvableResolver.java
  reasoner/resolution/resolver/RetrievableResolver.java
  reasoner/resolution/resolver/RootResolver.java
  reasoner/resolution/resolver/RuleResolver.java
  test/integration/logic/RuleTest.java
Labels: type: feature

#5977 Rearchitect Unifiers to include Requirements
  common/exception/ErrorMessage.java
  logic/Rule.java
  logic/resolvable/Concludable.java
  logic/resolvable/Resolvable.java
  logic/resolvable/Unifier.java
  logic/tool/ConstraintCopier.java
  logic/transformer/Unifier.java
  logic/transformer/VariableTransformer.java
  pattern/constraint/thing/RelationConstraint.java
  reasoner/Reasoner.java
  reasoner/ReasonerProducer.java
  reasoner/resolution/MockTransaction.java
  reasoner/resolution/ResolutionRecorder.java
  reasoner/resolution/ResolverRegistry.java
  reasoner/resolution/answer/AnswerState.java
  reasoner/resolution/answer/Mapping.java
  reasoner/resolution/framework/Request.java
  reasoner/resolution/resolver/ConcludableResolver.java
  reasoner/resolution/resolver/RootResolver.java
  reasoner/resolution/resolver/RuleResolver.java
  rocks/RocksTransaction.java
  test/integration/QueryTest.java
  test/integration/logic/BUILD
  test/integration/logic/TypeResolverTest.java
  test/integration/logic/resolvable/UnificationTest.java
  test/integration/logic/resolvable/UnifyAttributeConcludableTest.java
  test/integration/logic/resolvable/UnifyHasConcludableTest.java
  test/integration/logic/resolvable/UnifyIsaConcludableTest.java
  test/integration/logic/resolvable/UnifyRelationConcludableTest.java
  test/integration/reasoner/ResolutionTest.java
  traversal/common/Predicate.java
Labels: type: feature

#5989 RPC implementation for receiving match aggregate, match group, and match group aggregate queries
  dependencies/graknlabs/repositories.bzl
  server/rpc/query/QueryHandler.java
  server/rpc/util/ResponseBuilder.java
Labels: type: feature

#5991 Refine returning numerical results for match aggregate and match group aggregate queries
  concept/answer/ConceptMapGroup.java
  concept/answer/Numeric.java
  concept/answer/NumericGroup.java
  dependencies/graknlabs/repositories.bzl
  query/QueryManager.java
  server/rpc/query/QueryHandler.java
  server/rpc/util/ResponseBuilder.java
  test/behaviour/graql/GraqlSteps.java
Labels: type: feature

#5990 Close transaction on exception while iterating throw answers
  common/iterator/ErrorHandledIterator.java
  common/iterator/ResourceIterator.java
  concept/ConceptManager.java
  dependencies/graknlabs/repositories.bzl
  graph/GraphManager.java
  graph/util/Storage.java
  query/QueryManager.java
  reasoner/Reasoner.java
  rocks/RocksStorage.java
  test/behaviour/debug/bugs/async-bugs.feature
Labels: type: bug

#5992 Do not send super type in response when super type is null
  server/rpc/concept/TypeHandler.java
Labels: type: bug

#5994 Enable async producer for match queries
  traversal/producer/GraphProducer.java
Labels: type: bug

#5997 Bump @graknlabs_console artifact version
  dependencies/graknlabs/artifacts.bzl
Labels: priority: high, type: build

#5986 Suppress session timeout while transaction is open
  server/rpc/SessionRPC.java
Labels: priority: medium, type: bug

#5998 Conclusion refactor
  logic/BUILD
  logic/Rule.java
  logic/resolvable/Concludable.java
  logic/resolvable/ConcludableTest.java
  pattern/Conjunction.java
  test/integration/logic/RuleTest.java
  test/integration/logic/resolvable/UnifyAttributeConcludableTest.java
  test/integration/logic/resolvable/UnifyHasConcludableTest.java
  test/integration/logic/resolvable/UnifyIsaConcludableTest.java
  test/integration/logic/resolvable/UnifyRelationConcludableTest.java
Labels: type: refactor

#6004 Migrate Actor library from @graknlabs_common
  common/BUILD
  common/concurrent/ExecutorService.java
  common/concurrent/actor/Actor.java
  common/concurrent/actor/EventLoop.java
  common/concurrent/actor/EventLoopGroup.java
  dependencies/graknlabs/repositories.bzl
  reasoner/Reasoner.java
  reasoner/ReasonerProducer.java
  reasoner/resolution/ResolutionRecorder.java
  reasoner/resolution/ResolverRegistry.java
  reasoner/resolution/framework/Request.java
  reasoner/resolution/framework/ResolutionAnswer.java
  reasoner/resolution/framework/Resolver.java
  reasoner/resolution/resolver/ConcludableResolver.java
  reasoner/resolution/resolver/ResolvableResolver.java
  reasoner/resolution/resolver/RetrievableResolver.java
  reasoner/resolution/resolver/RootResolver.java
  reasoner/resolution/resolver/RuleResolver.java
  test/integration/reasoner/ResolutionTest.java
Labels: type: refactor

#5999 Fix concurrency bugs in async producer
  common/producer/BaseProducer.java
  common/producer/FilteredProducer.java
  common/producer/MappedProducer.java
  traversal/procedure/VertexProcedure.java
  traversal/producer/GraphProducer.java
Labels: type: bug

#6001 Create namespaced Encoding.Statistics and Encoding.Index
  graph/DataGraph.java
  graph/iid/IndexIID.java
  graph/util/Encoding.java
  graph/util/StatisticsBytes.java
Labels: priority: high, type: refactor

#6012 Fix async producer
  test/behaviour/graql/GraqlSteps.java
  traversal/producer/GraphProducer.java
Labels: type: bug

#5996 Rule materialisation
  concept/thing/Relation.java
  concept/thing/Thing.java
  concept/thing/impl/RelationImpl.java
  concept/thing/impl/RoleImpl.java
  concept/thing/impl/ThingImpl.java
  graph/DataGraph.java
  graph/adjacency/ThingAdjacency.java
  graph/adjacency/impl/ThingAdjacencyImpl.java
  graph/edge/ThingEdge.java
  graph/edge/impl/ThingEdgeImpl.java
  graph/vertex/impl/ThingVertexImpl.java
  logic/Rule.java
  reasoner/resolution/resolver/RuleResolver.java
  test/integration/logic/BUILD
  test/integration/logic/RuleTest.java
Labels: priority: high, type: feature

#6017 Fix stalling when closing transactions in parallel
  server/rpc/SessionRPC.java
Labels: priority: high, type: bug

#6019 Do not start new async producer job when not necessary
  traversal/producer/GraphProducer.java
  traversal/producer/VertexProducer.java
Labels: type: bug

#6018 Fixed Referable Class Typo
  dependencies/graknlabs/repositories.bzl
  pattern/variable/SystemReference.java
  pattern/variable/VariableRegistry.java
  traversal/common/Identifier.java
Labels: type: refactor

#6005 Always use scoped labels in role overrides in BDD
  dependencies/graknlabs/repositories.bzl
  test/behaviour/concept/type/thingtype/ThingTypeSteps.java
Labels: priority: low, type: refactor

#6025 Refactor of Concludable Relation Unifier
  logic/resolvable/Concludable.java
Labels: type: refactor

#6028 Outline unimplemented rule validation requirements
  logic/Rule.java
Labels: priority: blocker, type: documentation

#6024 In BDD, split Match step into Aggregate, Group etc
  dependencies/graknlabs/repositories.bzl
  test/behaviour/graql/GraqlSteps.java
Labels: priority: medium, type: refactor

#5993 Type resolver implemented directly with traversals
  common/exception/ErrorMessage.java
  common/test/BUILD
  common/test/Util.java
  graph/SchemaGraph.java
  logic/LogicCache.java
  logic/tool/TypeResolver.java
  pattern/variable/SystemReference.java
  pattern/variable/Variable.java
  reasoner/Reasoner.java
  test/behaviour/debug/bugs/BUILD
  test/behaviour/debug/bugs/TypeResolverTest.java
  test/behaviour/debug/bugs/type-resolver-bugs.feature
  test/integration/logic/BUILD
  test/integration/logic/TypeResolverTest.java
  traversal/Traversal.java
Labels: type: feature

#6036 Enable Graql Define tests in CI
  .grabl/automation.yml
  dependencies/graknlabs/repositories.bzl
Labels: priority: medium, type: build

#6037 Ignore failing Graql Define BDD test
  dependencies/graknlabs/repositories.bzl
Labels: priority: medium, type: build

#6039 Fix a bug causing ConcurrentModificationException
  traversal/producer/GraphProducer.java
Labels: type: bug

#6040 Type resolver will not run on schema queries
  dependencies/graknlabs/repositories.bzl
  logic/tool/TypeResolver.java
Labels: type: bug

#6014 Write schema transactions are exclusive
  common/concurrent/ManagedLock.java
  common/concurrent/ManagedReadWriteLock.java
  common/exception/GraknException.java
  common/producer/Producers.java
  concept/ConceptImpl.java
  concept/ConceptManager.java
  concept/thing/impl/ThingImpl.java
  concept/type/impl/AttributeTypeImpl.java
  concept/type/impl/RoleTypeImpl.java
  concept/type/impl/ThingTypeImpl.java
  concept/type/impl/TypeImpl.java
  graph/SchemaGraph.java
  reasoner/Reasoner.java
  rocks/RocksSession.java
  rocks/RocksTransaction.java
  test/behaviour/connection/ConnectionSteps.java
  test/integration/logic/TypeResolverTest.java
  test/integration/logic/resolvable/UnifyAttributeConcludableTest.java
  test/integration/logic/resolvable/UnifyHasConcludableTest.java
  test/integration/logic/resolvable/UnifyIsaConcludableTest.java
  test/integration/logic/resolvable/UnifyRelationConcludableTest.java
Labels: priority: high

#6015 Refactor Concludables to achieve proper unification
  logic/BUILD
  logic/Rule.java
  logic/resolvable/Concludable.java
  logic/resolvable/ConcludableTest.java
  logic/resolvable/Resolvable.java
  logic/resolvable/Retrievable.java
  logic/resolvable/RetrievableTest.java
  logic/tool/ConstraintCopier.java
  pattern/Conjunction.java
  pattern/constraint/Constraint.java
  pattern/constraint/thing/HasConstraint.java
  pattern/constraint/thing/IIDConstraint.java
  pattern/constraint/thing/IsConstraint.java
  pattern/constraint/thing/IsaConstraint.java
  pattern/constraint/thing/RelationConstraint.java
  pattern/constraint/thing/ValueConstraint.java
  pattern/constraint/type/AbstractConstraint.java
  pattern/constraint/type/IsConstraint.java
  pattern/constraint/type/LabelConstraint.java
  pattern/constraint/type/OwnsConstraint.java
  pattern/constraint/type/PlaysConstraint.java
  pattern/constraint/type/RegexConstraint.java
  pattern/constraint/type/RelatesConstraint.java
  pattern/constraint/type/SubConstraint.java
  pattern/constraint/type/ValueTypeConstraint.java
  pattern/equivalence/AlphaEquivalence.java
  pattern/variable/ThingVariable.java
  pattern/variable/TypeVariable.java
  reasoner/resolution/ResolverRegistry.java
  reasoner/resolution/answer/Mapping.java
  reasoner/resolution/resolver/ConcludableResolver.java
  reasoner/resolution/resolver/RootResolver.java
  reasoner/resolution/resolver/RuleResolver.java
  test/integration/logic/RuleTest.java
  test/integration/logic/resolvable/UnifyAttributeConcludableTest.java
  test/integration/logic/resolvable/UnifyHasConcludableTest.java
  test/integration/logic/resolvable/UnifyIsaConcludableTest.java
  test/integration/logic/resolvable/UnifyRelationConcludableTest.java
Labels: type: feature

#6049 Disable derivation recording in Resolution
  reasoner/resolution/ResolutionRecorder.java
  reasoner/resolution/ResolverRegistry.java
  reasoner/resolution/framework/ResolutionAnswer.java
  reasoner/resolution/framework/Resolver.java
  reasoner/resolution/resolver/ConcludableResolver.java
  reasoner/resolution/resolver/ResolvableResolver.java
  reasoner/resolution/resolver/RetrievableResolver.java
  reasoner/resolution/resolver/RootResolver.java
  reasoner/resolution/resolver/RuleResolver.java
Labels: priority: high, type: refactor

#6053 Keep the protocol version in sync with Grakn Cluster
  dependencies/graknlabs/repositories.bzl
Labels: type: refactor

#6050 Permit override of played roles in Plays constraints
  dependencies/graknlabs/repositories.bzl
  query/Definer.java
  test/integration/logic/RuleTest.java
Labels: priority: high

#6047 Implement retrievable resolver
  reasoner/resolution/resolver/RetrievableResolver.java
Labels: type: feature

#6052 Rewritten Producers to be thread-safe with a clean algorithm
  common/concurrent/ExecutorService.java
  common/producer/BaseProducer.java
  common/producer/FilteredProducer.java
  common/producer/IterableProducer.java
  common/producer/MappedProducer.java
  common/producer/Producer.java
  common/producer/ProducerIterator.java
  common/producer/Producers.java
  graph/adjacency/impl/ThingAdjacencyImpl.java
  logic/resolvable/Concludable.java
  query/QueryManager.java
  reasoner/Reasoner.java
  reasoner/ReasonerProducer.java
  rocks/BUILD
  rocks/RocksStorage.java
  server/GraknServer.java
  traversal/Traversal.java
  traversal/producer/GraphProducer.java
Labels: priority: blocker, type: bug, type: refactor

#6046 Fixed typos, missing articles + added Oxford commas
  README.md
Labels: type: documentation

#6058 Fix traversal performance caused by not hitting traversal cache
  traversal/Traversal.java
Labels: type: bug

#6056 Add RPC method to retrieve all rules
  dependencies/graknlabs/repositories.bzl
  server/rpc/logic/LogicManagerHandler.java
Labels: priority: medium, type: feature

#6051 Reasoner planning
  logic/resolvable/Concludable.java
  reasoner/ReasonerProducer.java
  reasoner/resolution/Planner.java
  reasoner/resolution/ResolverRegistry.java
  reasoner/resolution/framework/Request.java
  reasoner/resolution/framework/Response.java
  reasoner/resolution/resolver/ConcludableResolver.java
  reasoner/resolution/resolver/RetrievableResolver.java
  reasoner/resolution/resolver/RootResolver.java
  reasoner/resolution/resolver/RuleResolver.java
  test/integration/reasoner/BUILD
  test/integration/reasoner/ResolutionTest.java
  test/integration/reasoner/resolution/PlannerTest.java
Labels: type: feature

#6064 Improve performance of data transactions
  common/exception/ErrorMessage.java
  common/iterator/Iterators.java
  concept/ConceptManager.java
  dependencies/graknlabs/repositories.bzl
  graph/DataGraph.java
  graph/SchemaGraph.java
Labels: type: refactor

#6035 Rule index: fast rule lookup and prevent deleting types in rules
  common/collection/Bytes.java
  common/exception/ErrorMessage.java
  common/test/BUILD
  common/test/Util.java
  concept/type/impl/RelationTypeImpl.java
  concept/type/impl/RoleTypeImpl.java
  concept/type/impl/ThingTypeImpl.java
  concept/type/impl/TypeImpl.java
  graph/SchemaGraph.java
  graph/iid/IndexIID.java
  graph/structure/RuleStructure.java
  graph/structure/impl/RuleStructureImpl.java
  graph/util/Encoding.java
  graph/vertex/impl/TypeVertexImpl.java
  logic/LogicManager.java
  logic/Rule.java
  logic/resolvable/Concludable.java
  rocks/RocksSession.java
  rocks/RocksTransaction.java
  test/behaviour/concept/thing/BUILD
  test/behaviour/concept/thing/ThingSteps.java
  test/behaviour/concept/thing/attribute/AttributeSteps.java
  test/behaviour/concept/thing/attribute/BUILD
  test/behaviour/concept/thing/entity/BUILD
  test/behaviour/concept/thing/entity/EntitySteps.java
  test/behaviour/concept/thing/relation/BUILD
  test/behaviour/concept/thing/relation/RelationSteps.java
  test/behaviour/concept/type/relationtype/BUILD
  test/behaviour/concept/type/relationtype/RelationTypeSteps.java
  test/behaviour/concept/type/thingtype/BUILD
  test/behaviour/concept/type/thingtype/ThingTypeSteps.java
  test/behaviour/connection/transaction/BUILD
  test/behaviour/connection/transaction/TransactionSteps.java
  test/behaviour/graql/BUILD
  test/behaviour/graql/GraqlSteps.java
  test/behaviour/util/BUILD
  test/behaviour/util/Util.java
  test/integration/BasicTest.java
  test/integration/QueryTest.java
  test/integration/logic/BUILD
  test/integration/logic/RuleTest.java
  test/integration/logic/resolvable/UnifyAttributeConcludableTest.java
  test/integration/logic/resolvable/UnifyHasConcludableTest.java
  test/integration/logic/resolvable/UnifyIsaConcludableTest.java
  test/integration/logic/resolvable/UnifyRelationConcludableTest.java
  test/integration/migrator/BUILD
  test/integration/migrator/schema.gql
  test/integration/schema.gql
Labels: priority: high, type: feature

#6067 Fix a concurrency bug in async producer which may result in illegal state exception
  traversal/producer/GraphProducer.java
Labels: type: bug

#6070 Fix Grakn Core distribution for Windows
  BUILD
  dependencies/graknlabs/repositories.bzl
  server/BUILD
Labels: priority: blocker, type: bug

#6071 Encoding enums allocate byte arrays once
  graph/util/Encoding.java
Labels: priority: high, type: refactor

#6059 Add an example query that works under Java 8 but stalls under 11
  test/integration/docs/BUILD
  test/integration/docs/Test1.java
Labels: priority: high, type: bug

#6077 Add prefetch option for queries, which defaults to false for inserts
  common/parameters/Options.java
  dependencies/graknlabs/repositories.bzl
  server/rpc/TransactionRPC.java
  server/rpc/common/RequestReader.java
  server/rpc/query/QueryHandler.java
Labels: priority: high, type: bug, x: do not merge

#6079 Update protocol version
  dependencies/graknlabs/repositories.bzl
Labels: priority: low, type: refactor

#6068 Run reasoner in read transactions when enabled in query options
  Grakn.java
  common/parameters/Context.java
  common/parameters/Options.java
  query/Matcher.java
  query/QueryManager.java
  reasoner/Reasoner.java
  rocks/RocksTransaction.java
  server/rpc/TransactionRPC.java
  server/rpc/common/RequestReader.java
Labels: priority: high, type: feature

#6080 Reenable remote build caching
  .bazelrc
  .grabl/automation.yml
Labels: type: build

#6089 Speed up remote caching by minimizing downloads
  .bazelrc
Labels: priority: high, type: build

#6088 Sessions no longer close when one of their transaction streams ends abruptly
  server/rpc/TransactionStream.java
Labels: priority: medium, type: bug

#6091 Disable remote caching for deploy-artifact job
  .grabl/automation.yml
Labels: priority: blocker, type: bug, type: build

#6086 Fixed issues with Graql delete query
  .grabl/automation.yml
  common/exception/ErrorMessage.java
  concept/thing/impl/RelationImpl.java
  concept/thing/impl/ThingImpl.java
  dependencies/graknlabs/repositories.bzl
  graph/SchemaGraph.java
  pattern/variable/ThingVariable.java
  pattern/variable/VariableRegistry.java
  query/Deleter.java
  query/Inserter.java
  query/common/Util.java
  rocks/RocksStorage.java
  test/behaviour/graql/language/delete/BUILD
Labels: priority: high, type: bug

#6081 Type resolution correctly handles explicitly labelled roles
  logic/tool/TypeResolver.java
  test/integration/logic/TypeResolverTest.java
Labels: type: bug, type: refactor

#6093 Make CI green again
  .grabl/automation.yml
Labels: priority: blocker, type: bug, type: build

#6094 Optimised typeresolver when dealing with attributes
  logic/tool/TypeResolver.java
Labels: type: refactor

#6097 Fix transaction conflict checking exception in statistics counter thread
  graph/DataGraph.java
  rocks/RocksDatabase.java
Labels: type: bug

#6095 Added timeout exception when opening session or transaction
  common/exception/ErrorMessage.java
  rocks/RocksDatabase.java
  rocks/RocksSession.java
Labels: priority: high, type: bug

#6098 Event loop catches all errors
  concurrent/actor/Actor.java
  concurrent/actor/EventLoop.java
  reasoner/resolution/ResolutionRecorder.java
  reasoner/resolution/resolver/ConcludableResolver.java
  reasoner/resolution/resolver/RetrievableResolver.java
  reasoner/resolution/resolver/RootResolver.java
  reasoner/resolution/resolver/RuleResolver.java
Labels: priority: blocker, type: bug

#6099 Optimised key ownership validation at commit time
  concept/thing/impl/ThingImpl.java
Labels: priority: blocker, type: bug

#6054 Reasoner integration
  .grabl/automation.yml
  logic/Rule.java
  logic/resolvable/Concludable.java
  logic/resolvable/Unifier.java
  pattern/Conjunction.java
  reasoner/BUILD
  reasoner/ReasonerProducer.java
  reasoner/resolution/MockTransaction.java
  reasoner/resolution/ResolverRegistry.java
  reasoner/resolution/answer/AnswerState.java
  reasoner/resolution/answer/AnswerStateTest.java
  reasoner/resolution/answer/Mapping.java
  reasoner/resolution/framework/Resolver.java
  reasoner/resolution/resolver/ConcludableResolver.java
  reasoner/resolution/resolver/RetrievableResolver.java
  reasoner/resolution/resolver/RootResolver.java
  reasoner/resolution/resolver/RuleResolver.java
  test/integration/logic/RuleTest.java
  test/integration/reasoner/BUILD
  test/integration/reasoner/ReasonerTest.java
  test/integration/reasoner/ResolutionTest.java
  test/integration/reasoner/resolution/PlannerTest.java
Labels: type: feature

#6101 Reasoner resolvers handle old exhausted messages correctly
  reasoner/ReasonerProducer.java
  reasoner/resolution/resolver/ConcludableResolver.java
  reasoner/resolution/resolver/RetrievableResolver.java
  reasoner/resolution/resolver/RootResolver.java
  reasoner/resolution/resolver/RuleResolver.java
Labels: priority: high, type: bug

#6110 Remove redundant integration docs test
  test/integration/docs/BUILD
  test/integration/docs/Test1.java
Labels: type: refactor

#6106 Correct traversal backtracking through relation scopes
  traversal/iterator/GraphIterator.java
  traversal/procedure/ProcedureEdge.java
Labels: priority: blocker, type: bug

#6104 Run reasoning exclusively when rules are present
  common/exception/ErrorMessage.java
  common/parameters/Options.java
  logic/Rule.java
  logic/resolvable/ConcludableTest.java
  reasoner/Reasoner.java
  reasoner/resolution/resolver/RootResolver.java
  reasoner/resolution/resolver/RuleResolver.java
  test/integration/logic/RuleTest.java
Labels: priority: high, type: refactor
