Repository typedb/typedb, pull requests merged in 2021-07, with the labels that each got.

#6407 Fix TypeQL parser error messages being duplicated
  dependencies/vaticle/repositories.bzl
  server/common/ResponseBuilder.java
Labels: priority: medium, type: bug

#6402 Set/unset abstract checks if already abstract
  concept/type/impl/ThingTypeImpl.java
Labels: priority: medium, type: bug

#6413 Replace next() with first() to ensure resources are closed
  concept/thing/impl/RelationImpl.java
  concept/thing/impl/RoleImpl.java
  concept/type/impl/RoleTypeImpl.java
Labels: priority: medium, type: bug

#6414 Custom base Docker image for TypeDB Server
  BUILD
  WORKSPACE
Labels: priority: medium, type: build

#6415 Prevent SIGSEGV when using a closed RocksIterator
  rocks/RocksIterator.java
Labels: priority: high, type: bug

#6410 Create clear structure of resolver types
  reasoner/resolution/ResolverRegistry.java
  reasoner/resolution/framework/Resolver.java
  reasoner/resolution/resolver/BoundConcludableResolver.java
  reasoner/resolution/resolver/ConcludableResolver.java
  reasoner/resolution/resolver/Coordinator.java
  reasoner/resolution/resolver/ExplainBoundConcludableResolver.java
  reasoner/resolution/resolver/MatchBoundConcludableResolver.java
  reasoner/resolution/resolver/RetrievableResolver.java
Labels: priority: high, type: refactor
