Repository typedb/typedb, pull requests merged in 2021-12, with the labels that each got.

#6488 Remove all default string encodes/decodes
  common/collection/ByteArray.java
  graph/adjacency/impl/TypeAdjacencyImpl.java
  graph/common/Storage.java
  graph/edge/impl/ThingEdgeImpl.java
  graph/edge/impl/TypeEdgeImpl.java
  graph/iid/EdgeIID.java
  graph/iid/IndexIID.java
  graph/iid/VertexIID.java
  graph/structure/impl/RuleStructureImpl.java
  graph/vertex/impl/TypeVertexImpl.java
  migrator/BUILD
  migrator/data/DataImporter.java
Labels: type: bug, priority: blocker

#6495 Update build jobs to use Ubuntu 21.04
  .grabl/automation.yml
Labels: type: build, priority: blocker

#6474 Refactor review
  logic/resolvable/Concludable.java
  pattern/constraint/thing/HasConstraint.java
  pattern/constraint/thing/IsaConstraint.java
  pattern/constraint/thing/RelationConstraint.java
  pattern/constraint/thing/ValueConstraint.java
  pattern/constraint/type/LabelConstraint.java
  pattern/constraint/type/ValueTypeConstraint.java
  pattern/equivalence/AlphaEquivalence.java
  reasoner/ReasonerProducer.java
  reasoner/resolution/framework/Materialiser.java
  reasoner/resolution/framework/Request.java
  reasoner/resolution/framework/Resolver.java
  reasoner/resolution/framework/Response.java
  reasoner/resolution/resolver/BoundConcludableResolver.java
  reasoner/resolution/resolver/BoundConclusionResolver.java
  reasoner/resolution/resolver/CompoundResolver.java
  reasoner/resolution/resolver/ConcludableResolver.java
  reasoner/resolution/resolver/ConclusionResolver.java
  reasoner/resolution/resolver/ConjunctionResolver.java
  reasoner/resolution/resolver/DisjunctionResolver.java
  reasoner/resolution/resolver/RetrievableResolver.java
  reasoner/resolution/resolver/SubsumptiveCoordinator.java
  test/integration/logic/resolvable/AlphaEquivalenceTest.java
Labels: type: refactor, priority: high

#6499 Upgrade grpc to 1.43.0 and netty to 4.1.61.Final
  dependencies/maven/artifacts.snapshot
  dependencies/vaticle/repositories.bzl
Labels: type: build, priority: high

#6490 Implement transaction timeouts
  common/exception/ErrorMessage.java
  common/parameters/Options.java
  dependencies/vaticle/repositories.bzl
  rocks/RocksSession.java
  server/TransactionService.java
  server/common/RequestReader.java
Labels: type: feature, priority: high
