Repository typedb/typedb, pull requests merged in 2021-04, with the labels that each got.

#6277 Add test for cloned labeled variables throwing assertion
  dependencies/graknlabs/repositories.bzl
  logic/resolvable/RetrievableTest.java
Labels: priority: medium, type: refactor

#6281 Upgrade build system and Java
  .bazelrc
  .bazelversion
  dependencies/graknlabs/repositories.bzl
Labels: priority: high, type: build

#6283 Fix failing test-assembly jobs
  .circleci/windows/dependencies.config
  dependencies/graknlabs/repositories.bzl
Labels: priority: high, type: bug, type: build

#6284 Transaction delete-update isolation checks are less aggressive
  graph/DataGraph.java
  graph/Graph.java
  graph/SchemaGraph.java
  graph/common/Storage.java
  graph/structure/impl/RuleStructureImpl.java
  graph/vertex/AttributeVertex.java
  graph/vertex/impl/AttributeVertexImpl.java
  graph/vertex/impl/ThingVertexImpl.java
  graph/vertex/impl/TypeVertexImpl.java
  rocks/RocksStorage.java
  rocks/RocksTransaction.java
  test/integration/BasicTest.java
Labels: priority: blocker, type: bug

#6286 In gRPC, encode Request IDs as bytes, and move 'inferred' to Thing
  dependencies/graknlabs/repositories.bzl
  server/GraknService.java
  server/SessionService.java
  server/TransactionService.java
  server/common/RequestReader.java
  server/common/ResponseBuilder.java
  server/concept/ConceptService.java
  server/concept/ThingService.java
  server/concept/TypeService.java
  server/logic/LogicService.java
  server/logic/RuleService.java
  server/query/QueryService.java
Labels: priority: medium, type: feature, x: do not merge

#6288 Update console artifact due to new protocol
  dependencies/graknlabs/artifacts.bzl
Labels: priority: medium, type: build

#6290 Retrievables connected only by type are separate retrievables
  logic/BUILD
  logic/resolvable/Retrievable.java
  logic/resolvable/RetrievableTest.java
Labels: priority: high, type: refactor

#6289 Remove most internal uses of java Streams
  common/collection/Streams.java
  common/iterator/Iterators.java
  concept/ConceptManager.java
  concept/thing/Attribute.java
  concept/thing/Relation.java
  concept/thing/Thing.java
  concept/thing/impl/AttributeImpl.java
  concept/thing/impl/RelationImpl.java
  concept/thing/impl/ThingImpl.java
  concept/type/AttributeType.java
  concept/type/EntityType.java
  concept/type/RelationType.java
  concept/type/RoleType.java
  concept/type/ThingType.java
  concept/type/Type.java
  concept/type/impl/AttributeTypeImpl.java
  concept/type/impl/EntityTypeImpl.java
  concept/type/impl/RelationTypeImpl.java
  concept/type/impl/RoleTypeImpl.java
  concept/type/impl/ThingTypeImpl.java
  concept/type/impl/TypeImpl.java
  logic/resolvable/Concludable.java
  migrator/DataExporter.java
  migrator/DataImporter.java
  query/Definer.java
  query/common/Util.java
  server/concept/ThingService.java
  server/concept/TypeService.java
  test/behaviour/concept/thing/entity/EntitySteps.java
  test/behaviour/concept/thing/relation/RelationSteps.java
  test/behaviour/concept/type/attributetype/AttributeTypeSteps.java
  test/behaviour/concept/type/relationtype/RelationTypeSteps.java
  test/behaviour/concept/type/thingtype/ThingTypeSteps.java
  test/behaviour/graql/GraqlSteps.java
  test/integration/QueryTest.java
  test/integration/logic/RuleTest.java
  test/integration/reasoner/ExplanationTest.java
Labels: priority: low, type: refactor

#6296 Validate rule value type compatibility and fix attribute materialisation
  common/exception/ErrorMessage.java
  concept/type/AttributeType.java
  dependencies/graknlabs/repositories.bzl
  logic/LogicManager.java
  logic/Rule.java
  logic/resolvable/Concludable.java
  logic/resolvable/Unifier.java
  reasoner/resolution/framework/Resolver.java
Labels: priority: high, type: bug, type: refactor

#6294 At most a single relation is allowed on a thing variable
  common/exception/ErrorMessage.java
  logic/resolvable/ConcludableTest.java
  logic/tool/TypeResolver.java
  pattern/equivalence/AlphaEquivalence.java
  pattern/equivalence/AlphaEquivalenceTest.java
  pattern/variable/ThingVariable.java
  query/Deleter.java
  query/Inserter.java
Labels: priority: high, type: refactor

#6297 Upgrade @graknlabs_dependencies to the latest one
  dependencies/graknlabs/repositories.bzl
Labels: priority: high, type: build

#6298 Update dependency on behaviour repo
  dependencies/graknlabs/repositories.bzl
Labels: priority: medium

#6299 Upgrade @graknlabs_dependencies to the latest one
  dependencies/graknlabs/repositories.bzl
Labels: priority: high, type: build

#6114 Port unification tests from 1.x
  logic/resolvable/Unifier.java
  test/integration/logic/resolvable/UnifyRelationConcludableTest.java
Labels: priority: high, type: feature
