Repository typedb/typedb, pull requests merged in 2022-02, with the labels that each got.

#6515 Fix iterators to recycle sub-iterators correctly
  common/iterator/FlatMappedIterator.java
  traversal/scanner/GraphIterator.java
Labels: type: bug, priority: blocker

#6514 Fix importing of attribute ownerships during migration
  common/exception/ErrorMessage.java
  migrator/data/DataImporter.java
Labels: type: bug, priority: high

#6520 Fix bazel server binary by preparing required directories
  server/BUILD
  server/parameters/ServerSubcommandParser.java
Labels: type: bug, priority: high

#6518 Open 'parameters' and 'logging' packages for extension
  dependencies/vaticle/repositories.bzl
  server/TypeDBServer.java
  server/logging/CoreLogback.java
  server/parameters/CoreConfig.java
  server/parameters/CoreConfigFactory.java
  server/parameters/CoreConfigParser.java
  server/parameters/ServerSubcommand.java
  server/parameters/ServerSubcommandParser.java
  server/parameters/util/Option.java
  server/parameters/util/YAMLParser.java
  server/test/BUILD
  server/test/CoreConfigTest.java
Labels: type: refactor, priority: blocker

#6522 Make partition manager class extendable
  database/CoreDatabase.java
  database/CorePartitionManager.java
  database/RocksStorage.java
  dependencies/vaticle/repositories.bzl
  graph/common/Encoding.java
  graph/common/Storage.java
Labels: type: bug, type: refactor, priority: blocker
