Repository typedb/typedb, pull requests merged in 2022-04, with the labels that each got.

#6536 Update dependency on lang java for better rule validation error message
  dependencies/vaticle/repositories.bzl
Labels: type: bug, priority: low

#6537 Fix session idle timeouts to not occur after session close
  server/SessionService.java
  server/TypeDBServer.java
Labels: type: bug, priority: high

#6539 Fix typos in "unsatisfiable query" error messages
  common/exception/ErrorMessage.java
Labels: type: bug, priority: medium

#6540 Upgrade to Bazel 5
  .bazelversion
  dependencies/vaticle/artifacts.bzl
  dependencies/vaticle/repositories.bzl
  graph/common/Encoding.java
  migrator/data/DataExporter.java
  migrator/data/DataImporter.java
Labels: type: build, priority: blocker

#6541 Clone repository prior to executing 'Bazel install' in CircleCI
  .circleci/config.yml
Labels: type: build, priority: blocker

#6542 Open statistics module for extension
  common/collection/ByteArray.java
  database/CoreDatabase.java
  database/CoreFactory.java
  database/CorePartitionManager.java
  database/CoreSession.java
  database/CoreTransaction.java
  database/RocksStorage.java
Labels: type: refactor, priority: blocker
