Repository typedb/typedb, pull requests merged in 2022-01, with the labels that each got.

#6502 Idempotently finish reasoner producer
  reasoner/ReasonerProducer.java
Labels: type: bug, priority: high

#6503 Allow setting a type as abstract given only indirect instances
  concept/type/AttributeType.java
  concept/type/EntityType.java
  concept/type/RelationType.java
  concept/type/ThingType.java
  concept/type/impl/AttributeTypeImpl.java
  concept/type/impl/EntityTypeImpl.java
  concept/type/impl/RelationTypeImpl.java
  concept/type/impl/ThingTypeImpl.java
  concept/type/impl/TypeImpl.java
  dependencies/vaticle/repositories.bzl
  test/behaviour/concept/type/thingtype/ThingTypeSteps.java
Labels: type: bug, priority: high

#6504 Utilise IID type information in type inference
  logic/tool/TypeInference.java
  test/integration/logic/TypeInferenceTest.java
Labels: type: feature, priority: high

#6509 Update @vaticle_dependencies
  .grabl/automation.yml
  BUILD
  dependencies/vaticle/repositories.bzl
Labels: type: build, priority: high

#6513 Guarantee 'match' query answer uniqueness
  traversal/procedure/GraphProcedure.java
Labels: type: bug, priority: high
