Repository typedb/typedb, pull requests merged in 2022-11, with the labels that each got.

#6676 Migrate to Factory
  .factory/automation.yml
  README.md
  dependencies/vaticle/repositories.bzl
Labels: domain: build, priority: blocker

#6678 Only check key uniqueness within exact type
  concept/thing/impl/ThingImpl.java
  dependencies/vaticle/repositories.bzl
Labels: type: feature, priority: high, domain: server

#6685 Bump dependencies, updated factory CI instructions
  .factory/automation.yml
  dependencies/vaticle/repositories.bzl
Labels: domain: build, priority: blocker

#6689 Validate directories on bootup
  common/exception/ErrorMessage.java
  database/CoreDatabase.java
Labels: type: refactor, priority: medium, domain: server

#6691 Fix isolation manager race condition
  database/CoreDatabase.java
Labels: type: bug, priority: blocker, domain: server

#6692 Improve write performance by removing persisted statistics version
  database/CoreDatabase.java
  database/CoreTransaction.java
  encoding/key/StatisticsKey.java
  graph/ThingGraph.java
  traversal/planner/GraphPlanner.java
Labels: type: refactor, priority: blocker, domain: storage

#6693 Type inference differentiates illegal and queries with no answer
  common/exception/ErrorMessage.java
  logic/LogicCache.java
  logic/Rule.java
  logic/tool/TypeInference.java
  pattern/Conjunction.java
  reasoner/Reasoner.java
  test/integration/logic/RuleTest.java
Labels: type: refactor, priority: blocker, domain: server

#6694 Background statistics correct handles exceptions gracefully
  database/CoreDatabase.java
Labels: type: bug

#6700 Fix the overwriting of owns edges
  concept/type/impl/ThingTypeImpl.java
  graph/edge/impl/TypeEdgeImpl.java
Labels: priority: blocker, domain: server

#6677 Disjunctions in rules
  common/exception/ErrorMessage.java
  dependencies/vaticle/repositories.bzl
  logic/LogicManager.java
  logic/Rule.java
  pattern/Disjunction.java
  reasoner/controller/AbstractController.java
  reasoner/controller/ConcludableController.java
  reasoner/controller/ConclusionController.java
  reasoner/controller/ConditionController.java
  reasoner/controller/ConjunctionController.java
  reasoner/controller/DisjunctionController.java
  reasoner/controller/MaterialisationController.java
  reasoner/controller/NegationController.java
  reasoner/controller/NestedConjunctionController.java
  reasoner/controller/NestedDisjunctionController.java
  reasoner/controller/RetrievableController.java
  reasoner/controller/RootConjunctionController.java
  reasoner/controller/RootDisjunctionController.java
  reasoner/planner/AnswerCountEstimator.java
  reasoner/planner/ConjunctionGraph.java
  reasoner/planner/ReasonerPlanner.java
  reasoner/planner/RecursivePlanner.java
  reasoner/processor/AbstractProcessor.java
  reasoner/processor/AbstractRequest.java
  test/behaviour/reasoner/verification/BoundPattern.java
  test/behaviour/reasoner/verification/ForwardChainingMaterialiser.java
  test/behaviour/reasoner/verification/SoundnessVerifier.java
  test/integration/logic/resolvable/UnifyRelationConcludableTest.java
  test/integration/reasoner/planner/ReasonerPlannerTest.java
Labels: type: feature, domain: reasoner

#6701 Unset overriddes when replacing pre-existing type edges
  concept/type/impl/RelationTypeImpl.java
  concept/type/impl/ThingTypeImpl.java
  graph/edge/TypeEdge.java
  graph/edge/impl/TypeEdgeImpl.java
Labels: priority: blocker, domain: server

#6703 Only let MultiPlanner spawn async2 futures
  traversal/planner/MultiPlanner.java
Labels: type: bug, priority: high, domain: traversal

#6698 Apply naming conventions to docker deployment targets
  .factory/automation.yml
  BUILD
  deployment.bzl
Labels: type: refactor, domain: build, priority: medium

#6705 Planning and statistics are logged on TRACE
  database/CoreDatabase.java
  traversal/planner/GraphPlanner.java
Labels: type: refactor, priority: medium

#6704 Simplify isolation manager
  database/CoreDatabase.java
Labels: type: bug, priority: high, domain: server

#6702 Avoid division by zero in reasoner planner
  reasoner/planner/AnswerCountEstimator.java
  reasoner/planner/RecursivePlanner.java
Labels: domain: reasoner

#6706 Parallelise rule validation
  logic/LogicManager.java
Labels: type: feature, priority: high, domain: reasoner

#6707 Optimise traversal over non-retrieved variables
  traversal/scanner/GraphIterator.java
Labels: priority: high, domain: traversal
