Repository typedb/typedb, pull requests merged in 2022-06, with the labels that each got.

#6567 Update @vaticle_behaviour
  dependencies/vaticle/repositories.bzl
Labels: type: build

#6546 Rewrite query engine to leverage data sortedness
  common/iterator/sorted/BaseForwardableIterator.java
  common/iterator/sorted/IntersectForwardableIterator.java
  common/iterator/sorted/MappedSortedIterator.java
  common/iterator/sorted/SortedIterator.java
  common/iterator/sorted/SortedIterators.java
  graph/vertex/ThingVertex.java
  graph/vertex/TypeVertex.java
  graph/vertex/Vertex.java
  graph/vertex/impl/ThingVertexImpl.java
  graph/vertex/impl/TypeVertexImpl.java
  pattern/constraint/thing/RelationConstraint.java
  test/integration/traversal/TraversalTest.java
  traversal/common/Identifier.java
  traversal/graph/TraversalEdge.java
  traversal/graph/TraversalVertex.java
  traversal/planner/GraphPlanner.java
  traversal/planner/PlannerEdge.java
  traversal/planner/PlannerVertex.java
  traversal/predicate/Predicate.java
  traversal/predicate/PredicateArgument.java
  traversal/predicate/PredicateOperator.java
  traversal/procedure/CombinationProcedure.java
  traversal/procedure/GraphProcedure.java
  traversal/procedure/ProcedureEdge.java
  traversal/procedure/ProcedureVertex.java
  traversal/procedure/VertexProcedure.java
  traversal/scanner/CombinationFinder.java
  traversal/scanner/GraphIterator.java
  traversal/scanner/RelationIterator.java
  traversal/structure/Structure.java
Labels: type: feature, priority: high

#6570 Improve incompatible data version error message
  common/exception/ErrorMessage.java
  database/CoreDatabase.java
  test/integration/database/DatabaseTest.java
Labels: priority: low

#6559 Refactor Reactives to remove Operators abstraction
  reasoner/controller/ConcludableController.java
  reasoner/controller/ConclusionController.java
  reasoner/controller/ConditionController.java
  reasoner/controller/ConjunctionController.java
  reasoner/controller/DisjunctionController.java
  reasoner/controller/MaterialisationController.java
  reasoner/controller/NegationController.java
  reasoner/controller/NestedConjunctionController.java
  reasoner/controller/RetrievableController.java
  reasoner/controller/RootConjunctionController.java
  reasoner/processor/reactive/PoolingStream.java
  reasoner/processor/reactive/Source.java
  reasoner/processor/reactive/TransformationStream.java
  reasoner/processor/reactive/common/Operator.java
  reasoner/processor/reactive/common/PublisherDelegate.java
Labels: type: refactor, priority: medium

#6594 Improve negative-cycle detection during rule-validation
  logic/LogicManager.java
Labels: type: bug, priority: medium, domain: reasoner

#6600 Pass conjunction bounds to reasoner's planner
  reasoner/controller/ConditionController.java
  reasoner/controller/ConjunctionController.java
  reasoner/controller/NestedConjunctionController.java
  reasoner/controller/RootConjunctionController.java
Labels: type: bug, priority: medium, domain: reasoner

#6598 Correctly add RocksDB JAR to the distribution
  server/BUILD
Labels: type: bug, domain: build, priority: high

#6595 Fix erroneous session timeouts
  server/SessionService.java
Labels: type: bug, priority: high
