Repository typedb/typedb, pull requests merged in 2023-12, with the labels that each got.

#6951 Update entry point runner for better UX
  dependencies/vaticle/artifacts.bzl
  dependencies/vaticle/repositories.bzl
Labels: type: refactor, domain: build

#6953 Update assembly tests to use new console flags
  test/assembly/AssemblyTest.java
  test/assembly/DockerTest.java
Labels: type: bug, priority: blocker

#6955 Update dependencies: rules_rust 0.31, updated typedb-common runners
  dependencies/vaticle/repositories.bzl
Labels: type: feature, priority: blocker

#6956 Fetch query can infer fetched attributes
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/PULL_REQUEST_TEMPLATE.md
  common/parameters/Context.java
  concept/answer/ConceptMap.java
  dependencies/vaticle/repositories.bzl
  query/Fetcher.java
  query/Getter.java
  query/Inserter.java
  reasoner/controller/RootConjunctionController.java
  reasoner/controller/RootDisjunctionController.java
Labels: type: bug, priority: medium

#6957 Update Console artifact: Cloud connection rename
  dependencies/vaticle/artifacts.bzl
Labels: type: refactor, priority: blocker

#6961 Fetch nulls
  concept/answer/ReadableConceptTree.java
  dependencies/vaticle/repositories.bzl
  server/common/ResponseBuilder.java
Labels: type: bug, priority: blocker, domain: server
