Repository typedb/typedb, pull requests merged in 2023-01, with the labels that each got.

#6720 Open import-export modules for extension
  migrator/CoreMigratorClient.java
  server/TypeDBServer.java
  server/parameters/CoreConfigFactory.java
  server/parameters/CoreSubcommand.java
  server/parameters/CoreSubcommandParser.java
  server/parameters/util/OptionParser.java
  server/test/BUILD
  server/test/parameters/CoreConfigTest.java
  server/test/parameters/config/config-invalid-logger-output.yml
  server/test/parameters/config/config-minimal-abs-path.yml
  server/test/parameters/config/config-missing-data.yml
  server/test/parameters/config/config-missing-debugger.yml
  server/test/parameters/config/config-unrecognised-option.yml
  server/test/parameters/config/config-wrong-path-type.yml
  test/integration/migrator/BUILD
  test/integration/migrator/MigratorTest.java
Labels: type: refactor, priority: high, domain: server

#6729 Update test instructions
  test/behaviour/typeql/explanation/language/LanguageTest.java
  test/behaviour/typeql/explanation/reasoner/ReasonerTest.java
Labels: type: refactor, priority: low, domain: documentation

#6730 Add missing ErrorMessage parameters for UNSUPPORTED_OPERATION
  concept/ConceptManager.java
Labels: type: bug

#6731 Update to error messages for illegal pattern matches
  common/exception/ErrorMessage.java
Labels: type: refactor

#6722 Update kotlin dependencies
  WORKSPACE
  dependencies/maven/artifacts.snapshot
  dependencies/vaticle/repositories.bzl
Labels: type: refactor, domain: build, priority: high

#6718 Update brew formula
  config/brew/typedb.rb
Labels: type: refactor, domain: build, priority: low

#6733 Short-cut rules where possible & relax reasoner planner orderings
  reasoner/controller/ConcludableController.java
  reasoner/planner/ReasonerPlanner.java
  reasoner/planner/RecursivePlanner.java
Labels: type: bug, domain: reasoner

#6735 Add transitive dependency on netty-transport to the concurrent package
  concurrent/BUILD
  dependencies/maven/artifacts.bzl
  dependencies/maven/artifacts.snapshot
  dependencies/vaticle/repositories.bzl
  server/BUILD
Labels: domain: build, priority: high
