Repository typedb/typedb, pull requests merged in 2023-02, with the labels that each got.

#6743 Refactor statistics corrector module to allow lazy initialisation
  database/CoreDatabase.java
Labels: type: refactor, priority: blocker, domain: server

#6740 Optimised relation unification performance
  logic/resolvable/Concludable.java
Labels: type: bug, domain: reasoner

#6737 Port reasoner benchmark from version 1.8
  reasoner/BUILD
  test/benchmark/BUILD
  test/benchmark/BenchmarkBig.java
  test/benchmark/BenchmarkSmall.java
  test/benchmark/RuleScaling.java
  test/benchmark/Util.java
  test/benchmark/generation/DiagonalGraph.java
  test/benchmark/generation/PathTreeGraph.java
  test/benchmark/generation/TransitivityChainGraph.java
  test/benchmark/generation/TransitivityMatrixGraph.java
  test/benchmark/resources/diagonalTest.tql
  test/benchmark/resources/linearTransitivity.tql
  test/benchmark/resources/multiJoin.tql
  test/benchmark/resources/pathTest.tql
  test/benchmark/resources/quadraticTransitivity.tql
Labels: type: feature, domain: reasoner
