Repository typedb/typedb, pull requests merged in 2023-07, with the labels that each got.

#6832 Implement native tests for Mac arm64
  .bazelversion
  .circleci/config.yml
  dependencies/vaticle/repositories.bzl
  test/integration/logic/TypeInferenceTest.java
  test/integration/logic/resolvable/AlphaEquivalenceTest.java
  test/integration/logic/resolvable/UnifyAttributeConcludableTest.java
  test/integration/logic/resolvable/UnifyHasConcludableTest.java
  test/integration/logic/resolvable/UnifyIsaConcludableTest.java
  test/integration/logic/resolvable/UnifyRelationConcludableTest.java
  test/integration/logic/resolvable/Util.java
Labels: type: feature, priority: blocker, domain: server

#6834 Update SpeeDB to 2.4.1.3 to support native Linux ARM64 deployments
  .circleci/config.yml
  dependencies/maven/artifacts.snapshot
  dependencies/vaticle/repositories.bzl
Labels: type: refactor, domain: build, priority: blocker, domain: server

#6835 Allow TypeDB migrator to operate over an empty database
  TypeDB.java
  common/exception/ErrorMessage.java
  database/CoreDatabase.java
  migrator/database/DatabaseImporter.java
Labels: type: feature, domain: server

#6837 Fix Windows x86-64 distribution
  .circleci/config.yml
  .circleci/windows/dependencies.config
  dependencies/maven/artifacts.snapshot
  dependencies/vaticle/repositories.bzl
Labels: domain: build, priority: blocker

#6836 Add RPC logging for session and transaction creation
  common/exception/ErrorMessage.java
  server/SessionService.java
  server/TypeDBService.java
Labels: type: feature, priority: medium, domain: server

#6842 Fix server hang-ups during shutdown
  common/exception/ErrorMessage.java
  common/exception/TypeDBCheckedException.java
  reasoner/controller/ConjunctionController.java
  server/TypeDBServer.java
Labels: type: bug, priority: blocker

#6846 Relation variable name in rule 'then' must not be present.
  dependencies/vaticle/repositories.bzl
Labels: type: bug, priority: high

#6853 Bump dependencies for typedb-enterprise encryption improvements
  dependencies/maven/artifacts.snapshot
  dependencies/vaticle/repositories.bzl
  test/behaviour/debug/BUILD
  test/behaviour/util/BUILD
Labels: domain: build

#6850 Expose number of outstanding tasks in ActorExecutor
  concurrent/actor/ActorExecutor.java
Labels: type: feature, domain: server
