Repository typedb/typedb, pull requests merged in 2024-10, with the labels that each got.

#7181 Add BDD test for pipeline modifiers
  compiler/BUILD
  compiler/expression/block_compiler.rs
  dependencies/vaticle/repositories.bzl
  ir/program/modifier.rs
  query/annotation.rs
  query/error.rs
  tests/behaviour/query/language/BUILD
  tests/behaviour/query/language/modifiers.rs
  tests/behaviour/steps/query/typeql.rs
Labels: domain: tests

#7184 Bump TypeQL to 2.28.6
  dependencies/vaticle/repositories.bzl
Labels: domain: build

#7185 Update GitHub urls to reflect renaming the GitHub organisation
  .factory/automation.yml
  common/diagnostics/Diagnostics.java
  config/brew/typedb.rb
  dependencies/vaticle/repositories.bzl
  pattern/Conjunction.java
  pattern/Disjunction.java
Labels: domain: build

#7183 Release 2.29.0
  RELEASE_NOTES_LATEST.md
  VERSION
  dependencies/maven/artifacts.snapshot
  dependencies/vaticle/artifacts.bzl
  dependencies/vaticle/repositories.bzl
Labels: domain: build

#7187 Bump circleci windows orb
  .circleci/config.yml
Labels: domain: build

#7188 Update github org to typedb
  deployment.bzl
Labels: domain: build

#7191 Update docker image to have both x86_64 and arm64 versions
  .factory/automation.yml
  BUILD
  WORKSPACE
  docker/BUILD
  docker/images.bzl
  test/assembly/BUILD
Labels: type: feature, priority: blocker

#7193 Prepare release 2.29.1
  RELEASE_NOTES_LATEST.md
  VERSION
Labels: domain: build, priority: blocker

#7195 Fix docker assembly test
  test/assembly/BUILD
  test/assembly/DockerTest.java
Labels: domain: tests

#7194 Merge for 2.29.1 release
  .factory/automation.yml
  BUILD
  RELEASE_NOTES_LATEST.md
  VERSION
  WORKSPACE
  docker/BUILD
  docker/images.bzl
  test/assembly/BUILD
  test/assembly/DockerTest.java
Labels: x: do not squash, domain: build, priority: high

#7197 Refactor executor package in preparation for functions
  compiler/match_/instructions/mod.rs
  compiler/match_/planner/mod.rs
  compiler/match_/planner/pattern_plan.rs
  executor/instruction/iterator.rs
  executor/instruction/mod.rs
  executor/lib.rs
  executor/match_executor.rs
  executor/pattern_executor.rs
  executor/program_executors.rs
  executor/tests/execute_comparison_check.rs
  executor/tests/execute_has.rs
  executor/tests/execute_isa.rs
  executor/tests/execute_links.rs
  executor/tests/execute_select.rs
Labels: domain: executor

#7198 Enable connection BDDs in CI
  .factory/automation.yml
  dependencies/vaticle/repositories.bzl
  tests/behaviour/steps/connection/mod.rs
  tests/behaviour/steps/connection/transaction.rs
  tests/behaviour/steps/query/typeql.rs
Labels: domain: tests

#7202 Update function type inference for pipelines
  compiler/annotation/function.rs
  compiler/annotation/mod.rs
  compiler/annotation/pipeline.rs
  compiler/annotation/type_inference.rs
  compiler/annotation/type_seeder.rs
  function/function_manager.rs
  ir/pipeline/function.rs
  main.rs
Labels: domain: language

#7203 Function compilation
  compiler/BUILD
  compiler/annotation/expression/block_compiler.rs
  compiler/annotation/fetch.rs
  compiler/annotation/function.rs
  compiler/annotation/mod.rs
  compiler/annotation/pipeline.rs
  compiler/annotation/type_inference.rs
  compiler/annotation/type_seeder.rs
  compiler/executable/function.rs
  compiler/executable/pipeline.rs
  ir/pipeline/function.rs
  ir/translation/function.rs
  main.rs
Labels: domain: executor

#7209 Refactor function type inference
  compiler/annotation/fetch.rs
  compiler/annotation/function.rs
  compiler/annotation/type_inference.rs
  function/function.rs
  function/function_cache.rs
  function/function_manager.rs
  ir/pipeline/function_signature.rs
Labels: domain: server

#7210 Function compilation preparation & trivial plan implementation
  compiler/annotation/function.rs
  compiler/annotation/match_inference.rs
  compiler/executable/fetch/executable.rs
  compiler/executable/function.rs
  compiler/executable/match_/planner/function_plan.rs
  compiler/executable/match_/planner/mod.rs
  compiler/executable/match_/planner/plan.rs
  compiler/executable/match_/planner/vertex/mod.rs
  compiler/executable/pipeline.rs
  executor/tests/BUILD
  executor/tests/execute_function.rs
  ir/pipeline/mod.rs
  ir/translation/function.rs
  ir/translation/mod.rs
  query/query_manager.rs
Labels: domain: executor

#7205 Disjunction support
  answer/variable_value.rs
  compiler/annotation/match_inference.rs
  compiler/annotation/pipeline.rs
  compiler/annotation/type_seeder.rs
  compiler/executable/insert/executable.rs
  compiler/executable/match_/instructions/mod.rs
  compiler/executable/match_/instructions/type_.rs
  compiler/executable/match_/planner/match_executable.rs
  compiler/executable/match_/planner/mod.rs
  compiler/executable/match_/planner/plan.rs
  compiler/executable/match_/planner/vertex/constraint.rs
  compiler/executable/match_/planner/vertex/mod.rs
  compiler/executable/match_/planner/vertex/variable.rs
  compiler/executable/pipeline.rs
  compiler/executable/reduce.rs
  compiler/lib.rs
  concept/thing/statistics.rs
  concept/thing/thing_manager/validation/mod.rs
  concept/thing/thing_manager/validation/operation_time_validation.rs
  concept/type_/type_manager.rs
  concept/type_/type_manager/validation/mod.rs
  concept/type_/type_manager/validation/operation_time_validation.rs
  encoding/value/timezone.rs
  executor/batch.rs
  executor/instruction/constant_executor.rs
  executor/instruction/function_call_binding_executor.rs
  executor/instruction/has_executor.rs
  executor/instruction/has_reverse_executor.rs
  executor/instruction/isa_executor.rs
  executor/instruction/isa_reverse_executor.rs
  executor/instruction/iterator.rs
  executor/instruction/links_executor.rs
  executor/instruction/links_reverse_executor.rs
  executor/instruction/mod.rs
  executor/instruction/owns_executor.rs
  executor/instruction/owns_reverse_executor.rs
  executor/instruction/plays_executor.rs
  executor/instruction/plays_reverse_executor.rs
  executor/instruction/relates_executor.rs
  executor/instruction/relates_reverse_executor.rs
  executor/instruction/sub_executor.rs
  executor/instruction/sub_reverse_executor.rs
  executor/instruction/tuple.rs
  executor/instruction/type_list_executor.rs
  executor/lib.rs
  executor/pattern_executor.rs
  executor/pipeline/modifiers.rs
  executor/row.rs
  executor/step_executors.rs
  executor/tests/compile_execute.rs
  executor/tests/execute_comparison_check.rs
  executor/tests/execute_has.rs
  executor/tests/execute_isa.rs
  executor/tests/execute_links.rs
  executor/tests/execute_select.rs
  ir/pattern/conjunction.rs
  ir/pattern/constraint.rs
  storage/recovery/commit_recovery.rs
  storage/snapshot/lock.rs
  tests/behaviour/steps/params.rs
Labels: type: feature, type: refactor, priority: blocker, domain: language

#7222 Fix and add to CI concept BDD tests
  .factory/automation.yml
  concept/thing/thing_manager/validation/mod.rs
  database/transaction.rs
  dependencies/vaticle/repositories.bzl
  tests/behaviour/steps/connection/transaction.rs
Labels: domain: tests

#7224 Implement tabling machinery for cyclic functions
  compiler/annotation/function.rs
  compiler/executable/fetch/executable.rs
  compiler/executable/function.rs
  compiler/executable/match_/planner/function_plan.rs
  compiler/executable/match_/planner/mod.rs
  compiler/executable/match_/planner/plan.rs
  compiler/executable/match_/planner/vertex/mod.rs
  compiler/executable/pipeline.rs
  executor/error.rs
  executor/match_executor.rs
  executor/pipeline/match_.rs
  executor/read/mod.rs
  executor/read/nested_pattern_executor.rs
  executor/read/pattern_executor.rs
  executor/read/step_executor.rs
  executor/read/tabled_call_executor.rs
  executor/read/tabled_functions.rs
  executor/row.rs
  executor/tests/compile_execute.rs
  executor/tests/execute_function.rs
  executor/tests/execute_has.rs
  executor/tests/execute_isa.rs
  executor/tests/execute_links.rs
  executor/tests/execute_select.rs
  ir/pattern/conjunction.rs
  ir/pattern/constraint.rs
  ir/pattern/disjunction.rs
  ir/pattern/negation.rs
Labels: type: feature

#7226 Functions have their own parameter registry
  compiler/annotation/function.rs
  compiler/annotation/type_seeder.rs
  compiler/executable/function.rs
  executor/read/nested_pattern_executor.rs
  executor/read/pattern_executor.rs
  executor/read/step_executor.rs
  executor/read/tabled_functions.rs
  executor/tests/execute_function.rs
Labels: type: bug, domain: reasoner

#7225 Prepare release 3.0.0 alpha 7
  .factory/automation.yml
  RELEASE_NOTES_LATEST.md
  VERSION
  dependencies/vaticle/artifacts.bzl
Labels: domain: build

#7229 Update many unit & integration tests & enable in CI
  .factory/automation.yml
  compiler/annotation/mod.rs
  compiler/annotation/type_inference.rs
  compiler/annotation/type_seeder.rs
  concept/BUILD
  database/BUILD
  durability/BUILD
  executor/BUILD
  executor/tests/execute_comparison_check.rs
  executor/tests/execute_function.rs
  executor/tests/execute_has.rs
  executor/tests/execute_isa.rs
  executor/tests/execute_links.rs
  executor/tests/execute_select.rs
  ir/lib.rs
  ir/pattern/constraint.rs
  ir/translation/constraints.rs
  query/BUILD
  storage/benches/BUILD
  storage/storage.rs
Labels: domain: tests

#7230 Is constraint
  answer/variable_value.rs
  common/lending_iterator/higher_order.rs
  compiler/annotation/fetch.rs
  compiler/annotation/type_inference.rs
  compiler/annotation/type_seeder.rs
  compiler/executable/delete/executable.rs
  compiler/executable/insert/type_check.rs
  compiler/executable/match_/instructions/mod.rs
  compiler/executable/match_/planner/plan.rs
  compiler/executable/match_/planner/vertex/mod.rs
  dependencies/vaticle/repositories.bzl
  executor/instruction/is_executor.rs
  executor/instruction/iterator.rs
  executor/instruction/mod.rs
  executor/tests/compile_execute.rs
  executor/tests/execute_comparison_check.rs
  executor/tests/execute_expression.rs
  executor/tests/execute_function.rs
  executor/tests/execute_has.rs
  executor/tests/execute_isa.rs
  executor/tests/execute_links.rs
  executor/tests/execute_select.rs
  executor/tests/writes.rs
  ir/lib.rs
  ir/pattern/constraint.rs
  ir/pipeline/block.rs
  ir/pipeline/mod.rs
  ir/tests/pattern.rs
  ir/tests/pipeline.rs
  ir/translation/constraints.rs
  ir/translation/expression.rs
  ir/translation/fetch.rs
  ir/translation/literal.rs
  ir/translation/mod.rs
  ir/translation/pipeline.rs
  ir/translation/writes.rs
Labels: type: feature, priority: high, domain: executor, domain: language
