Repository typedb/typedb, pull requests merged in 2024-03, with the labels that each got.

#6995 Rename TypeDB Enterprise to TypeDB Cloud
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  README.md
  common/exception/ErrorMessage.java
  encoding/Encoding.java
  tool/runner/Util.java
Labels: domain: server

#6981 Redesign schema modification capabilities
  common/exception/ErrorMessage.java
  concept/type/ThingType.java
  concept/type/impl/AttributeTypeImpl.java
  concept/type/impl/EntityTypeImpl.java
  concept/type/impl/RelationTypeImpl.java
  concept/type/impl/RoleTypeImpl.java
  concept/type/impl/ThingTypeImpl.java
  concept/validation/DeclarationValidation.java
  concept/validation/SubtypeValidation.java
  dependencies/vaticle/repositories.bzl
  graph/adjacency/impl/TypeAdjacencyImpl.java
  graph/edge/impl/TypeEdgeImpl.java
  test/behaviour/concept/validation/data/BUILD
  test/behaviour/concept/validation/data/DataValidationTest.java
  test/behaviour/concept/validation/migration/BUILD
  test/behaviour/concept/validation/migration/MigrationTest.java
  test/behaviour/concept/validation/schema/BUILD
  test/behaviour/concept/validation/schema/SchemaValidationTest.java
Labels: type: feature, x: do not merge

#7006 Disable monitoring in assembly tests
  test/assembly/AssemblyTest.java
Labels: type: bug, priority: blocker, domain: server

#7010 Merge release branch back to development after 2.27.0-rc0
  .factory/automation.yml
  BUILD
  dependencies/maven/artifacts.snapshot
  dependencies/vaticle/artifacts.bzl
Labels: domain: build

#7009 Add snapshot test to delete reinserted key
  storage/tests/test_snapshot.rs
Labels: domain: storage

#7001 Enable criterion flamegraphs
  storage/benches/BUILD
  storage/benches/bench_mvcc_storage.rs
Labels: domain: storage

#7016 Disable using type information from IID in type inference
  concept/thing/Thing.java
  dependencies/vaticle/repositories.bzl
  logic/tool/TypeInference.java
  test/behaviour/query/TypeQLSteps.java
  test/integration/logic/TypeInferenceTest.java
Labels: type: refactor, priority: blocker, domain: traversal
