Repository typedb/typedb, pull requests merged in 2024-05, with the labels that each got.

#7055 Fix bug when isolation manager finds & validates against concurrent windows
  storage/isolation_manager.rs
Labels: type: bug, domain: storage

#7058 Fix generics on ReadableType trait
  concept/thing/entity.rs
  concept/type_/type_cache.rs
  concept/type_/type_manager.rs
  concept/type_/type_reader.rs
Labels: domain: storage

#7063 Refactor type cache with templates
  concept/type_/type_cache.rs
  concept/type_/type_cache/kind_cache.rs
  concept/type_/type_cache/mod.rs
  concept/type_/type_cache/selection.rs
  concept/type_/type_cache/type_cache.rs
  concept/type_/type_manager.rs
  concept/type_/type_reader.rs
Labels: type: refactor

#7068 Turn off statistics reporting in CI
  test/assembly/AssemblyTest.java
  test/assembly/DockerTest.java
  test/deployment/AptTest.java
  test/integration/server/ParametersTest.java
Labels: priority: high, domain: tests
