Repository typedb/typedb, pull requests merged in 2024-11, with the labels that each got.

#7234 Refactor after basic functions
  executor/pipeline/stage.rs
  executor/read/collecting_stage_executor.rs
  executor/read/control_instruction.rs
  executor/read/immediate_executor.rs
  executor/read/mod.rs
  executor/read/nested_pattern_executor.rs
  executor/read/pattern_executor.rs
  executor/read/step_executor.rs
  executor/read/stream_modifier.rs
  executor/read/tabled_functions.rs
  executor/row.rs
Labels: type: refactor, domain: executor

#7236 Simplify attribute encoding
  .factory/automation.yml
  concept/thing/attribute.rs
  concept/thing/entity.rs
  concept/thing/mod.rs
  concept/thing/object.rs
  concept/thing/relation.rs
  concept/thing/thing_manager.rs
  concept/thing/value_struct.rs
  concept/type_/attribute_type.rs
  concept/type_/type_manager/validation/operation_time_validation.rs
  encoding/encoding.rs
  encoding/graph/common/value_hasher.rs
  encoding/graph/thing/edge.rs
  encoding/graph/thing/mod.rs
  encoding/graph/thing/vertex_attribute.rs
  encoding/graph/thing/vertex_generator.rs
  encoding/layout/prefix.rs
  encoding/tests/test_attribute_vertex.rs
  encoding/value/boolean_bytes.rs
  encoding/value/date_bytes.rs
  encoding/value/date_time_bytes.rs
  encoding/value/date_time_tz_bytes.rs
  encoding/value/decimal_bytes.rs
  encoding/value/double_bytes.rs
  encoding/value/duration_bytes.rs
  encoding/value/long_bytes.rs
  encoding/value/string_bytes.rs
  encoding/value/value_struct.rs
  encoding/value/value_type.rs
  executor/pipeline/fetch.rs
  executor/tests/writes.rs
  tests/behaviour/steps/concept/thing/has.rs
  tests/behaviour/steps/query/typeql.rs
Labels: type: refactor, priority: high, domain: storage

#7239 Ensure sorted join executor respects selected outputs
  executor/lib.rs
  executor/read/immediate_executor.rs
  executor/read/pattern_executor.rs
  executor/read/step_executor.rs
Labels: type: bug, priority: high, domain: executor

#7238 Fix outputs from earlier disjunction branches affecting later branches
  compiler/executable/match_/planner/mod.rs
  compiler/executable/match_/planner/plan.rs
Labels: type: bug, domain: executor

#7252 Fix disjunction inputs when lowering
  compiler/executable/match_/planner/mod.rs
  compiler/executable/match_/planner/plan.rs
Labels: domain: executor

#7249 Variable position fix
  compiler/executable/match_/planner/mod.rs
  compiler/executable/match_/planner/plan.rs
  compiler/executable/pipeline.rs
Labels: type: bug, domain: executor

#7241 Introduce naive retries for suspended function calls
  executor/match_executor.rs
  executor/read/control_instruction.rs
  executor/read/mod.rs
  executor/read/pattern_executor.rs
  executor/read/tabled_call_executor.rs
  executor/read/tabled_functions.rs
  executor/tests/BUILD
  executor/tests/execute_function.rs
Labels: type: feature, domain: reasoner

#7258 Disable variables of category value being narrow-able to attribute
  compiler/annotation/type_seeder.rs
  compiler/executable/match_/planner/plan.rs
  ir/pattern/constraint.rs
  ir/pattern/variable_category.rs
  ir/pipeline/block.rs
Labels: domain: language

#7265 Reintroduce deploy-github job
  .circleci/config.yml
  RELEASE_TEMPLATE.md
Labels: domain: build

#7264 IID constraint
  Cargo.lock
  common/bytes/byte_array.rs
  common/error/Cargo.toml
  common/structural_equality/BUILD
  common/structural_equality/Cargo.toml
  common/structural_equality/structural_equality.rs
  common/structural_equality/typeql_structural_equality.rs
  compiler/Cargo.toml
  compiler/annotation/type_seeder.rs
  compiler/executable/delete/executable.rs
  compiler/executable/insert/type_check.rs
  compiler/executable/match_/instructions/mod.rs
  compiler/executable/match_/instructions/thing.rs
  compiler/executable/match_/planner/mod.rs
  compiler/executable/match_/planner/plan.rs
  compiler/executable/match_/planner/vertex/constraint.rs
  concept/thing/thing_manager.rs
  database/Cargo.toml
  dependencies/typedb/repositories.bzl
  encoding/graph/thing/mod.rs
  encoding/graph/thing/vertex_attribute.rs
  encoding/graph/thing/vertex_object.rs
  encoding/value/value_struct.rs
  executor/BUILD
  executor/Cargo.toml
  executor/instruction/has_executor.rs
  executor/instruction/has_reverse_executor.rs
  executor/instruction/iid_executor.rs
  executor/instruction/is_executor.rs
  executor/instruction/isa_executor.rs
  executor/instruction/isa_reverse_executor.rs
  executor/instruction/iterator.rs
  executor/instruction/mod.rs
  executor/instruction/plays_executor.rs
  executor/instruction/plays_reverse_executor.rs
  executor/instruction/relates_reverse_executor.rs
  function/Cargo.toml
  ir/BUILD
  ir/Cargo.toml
  ir/pattern/constraint.rs
  ir/pattern/mod.rs
  ir/pipeline/mod.rs
  ir/translation/constraints.rs
  query/Cargo.toml
  server/Cargo.toml
  tests/behaviour/steps/Cargo.toml
  tests/behaviour/steps/query/typeql.rs
  tests/behaviour/steps/query_answer_context.rs
Labels: type: feature, priority: high, domain: executor, domain: language

#7268 Frugal type seeder
  compiler/annotation/match_inference.rs
  compiler/annotation/type_seeder.rs
Labels: domain: language

#7254 Guarantee transaction causality
  Cargo.lock
  common/error/Cargo.toml
  common/structural_equality/Cargo.toml
  compiler/Cargo.toml
  compiler/annotation/type_seeder.rs
  compiler/executable/match_/planner/vertex/mod.rs
  concept/benches/bench_thing_write.rs
  concept/thing/statistics.rs
  database/Cargo.toml
  database/database.rs
  encoding/graph/thing/vertex_attribute.rs
  executor/Cargo.toml
  function/Cargo.toml
  ir/Cargo.toml
  query/Cargo.toml
  query/benches/bench_insert_queries.rs
  query/benches/bench_insert_queries_multithreaded.rs
  resource/constants.rs
  server/Cargo.toml
  storage/isolation_manager.rs
  storage/storage.rs
  storage/tests/test_isolation.rs
  storage/tests/test_mvcc.rs
  storage/tests/test_recovery.rs
  tests/behaviour/steps/Cargo.toml
Labels: domain: storage

#7271 TLS In-flight encryption
  BUILD
  Cargo.lock
  Cargo.toml
  main.rs
  resource/constants.rs
  server/BUILD
  server/Cargo.toml
  server/parameters/cli.rs
  server/parameters/config.rs
  server/parameters/mod.rs
  server/typedb.rs
Labels: type: feature, priority: high, domain: server

#7269 Optimisations from typeql
  Cargo.lock
  common/error/Cargo.toml
  common/structural_equality/Cargo.toml
  common/structural_equality/typeql_structural_equality.rs
  compiler/Cargo.toml
  compiler/annotation/function.rs
  database/Cargo.toml
  dependencies/typedb/repositories.bzl
  executor/Cargo.toml
  executor/tests/execute_function.rs
  function/Cargo.toml
  function/function.rs
  function/function_manager.rs
  ir/Cargo.toml
  ir/lib.rs
  ir/pipeline/function_signature.rs
  ir/pipeline/mod.rs
  ir/translation/constraints.rs
  ir/translation/expression.rs
  ir/translation/fetch.rs
  ir/translation/function.rs
  ir/translation/mod.rs
  ir/translation/tokens.rs
  query/Cargo.toml
  query/definable_resolution.rs
  query/define.rs
  query/redefine.rs
  query/undefine.rs
  server/Cargo.toml
  tests/behaviour/steps/Cargo.toml
Labels: type: refactor, domain: language

#7272 Validate user input to the 'user repository' module
  Cargo.lock
  server/authenticator.rs
  server/service/typedb_service.rs
  system/BUILD
  system/Cargo.toml
  system/repositories.rs
  system/util.rs
  user/errors.rs
  user/lib.rs
  user/user_manager.rs
Labels: type: bug, priority: high, domain: server

#7273 Hide the system database
  database/database.rs
  database/database_manager.rs
  system/lib.rs
Labels: type: bug, priority: high, domain: server
