Repository typedb/typedb, pull requests merged in 2024-02, with the labels that each got.

#6983 Fix commit-time cleanup of chains of empty relations
  concept/ConceptManager.java
  concept/thing/impl/RelationImpl.java
  dependencies/vaticle/repositories.bzl
Labels: type: bug, priority: high, domain: server

#6984 Fix bug when overriding committed role-types with newly defined role-types
  dependencies/vaticle/repositories.bzl
  graph/edge/impl/TypeEdgeImpl.java
  test/behaviour/query/TypeQLSteps.java
Labels: type: bug, domain: server

#6988 Fix schema export of overridden plays edge
  concept/type/impl/ThingTypeImpl.java
Labels: type: bug

#6990 Add flag to config to easily enable or disable loggers
  server/logging/CoreLogback.java
  server/parameters/CoreConfig.java
  server/parameters/CoreConfigParser.java
  server/parameters/config.yml
  server/test/parameters/config/config-invalid-logger-output.yml
  server/test/parameters/config/config-minimal-abs-path.yml
  server/test/parameters/config/config-missing-debugger.yml
Labels: type: refactor
