Repository typedb/typedb, pull requests merged in 2025-03, with the labels that each got.

#7378 Allow abstract relation types having zero role types.
  compiler/executable/match_/planner/plan.rs
  concept/type_/relation_type.rs
  concept/type_/type_manager.rs
  concept/type_/type_manager/validation/commit_time_validation.rs
  concept/type_/type_manager/validation/mod.rs
  concept/type_/type_manager/validation/operation_time_validation.rs
  dependencies/typedb/repositories.bzl
  tests/behaviour/steps/concept/type_/relation_type.rs
Labels: type: bug, type: feature, domain: server

#7377 Allow multiple expression assignments in different branches
  compiler/annotation/expression/block_compiler.rs
  compiler/annotation/expression/compiled_expression.rs
  compiler/annotation/expression/mod.rs
  compiler/annotation/pipeline.rs
  compiler/executable/match_/planner/mod.rs
  compiler/executable/match_/planner/plan.rs
  dependencies/typedb/repositories.bzl
  executor/tests/execute_function.rs
Labels: domain: language

#7382 Update dependencies for 3.1
  Cargo.lock
  Cargo.toml
  common/error/Cargo.toml
  common/structural_equality/Cargo.toml
  compiler/Cargo.toml
  concept/Cargo.toml
  database/Cargo.toml
  database/tools/Cargo.toml
  dependencies/typedb/repositories.bzl
  diagnostics/Cargo.toml
  encoding/Cargo.toml
  executor/Cargo.toml
  function/Cargo.toml
  ir/Cargo.toml
  query/Cargo.toml
  server/Cargo.toml
  storage/Cargo.toml
  system/Cargo.toml
  tests/behaviour/steps/Cargo.toml
  user/Cargo.toml
Labels: domain: build, priority: high

#7381 Implement put stage
  .factory/automation.yml
  BUILD
  compiler/annotation/mod.rs
  compiler/annotation/pipeline.rs
  compiler/executable/delete/executable.rs
  compiler/executable/insert/executable.rs
  compiler/executable/insert/mod.rs
  compiler/executable/mod.rs
  compiler/executable/pipeline.rs
  compiler/executable/put/mod.rs
  compiler/executable/update/executable.rs
  dependencies/typedb/repositories.bzl
  executor/batch.rs
  executor/pipeline/insert.rs
  executor/pipeline/match_.rs
  executor/pipeline/mod.rs
  executor/pipeline/pipeline.rs
  executor/pipeline/put.rs
  executor/pipeline/stage.rs
  executor/pipeline/update.rs
  executor/read/step_executor.rs
  executor/row.rs
  executor/tests/writes.rs
  ir/lib.rs
  ir/pattern/constraint.rs
  ir/translation/function.rs
  ir/translation/pipeline.rs
  ir/translation/writes.rs
  resource/constants.rs
  tests/behaviour/query/language/BUILD
  tests/behaviour/query/language/put.rs
Labels: domain: executor

#7375 Fix erroneously selected named variables
  Cargo.lock
  answer/lib.rs
  answer/variable.rs
  answer/variable_value.rs
  common/error/error.rs
  common/logger/logger.rs
  compiler/annotation/expression/block_compiler.rs
  compiler/annotation/expression/mod.rs
  compiler/annotation/pipeline.rs
  compiler/annotation/type_seeder.rs
  compiler/executable/function/executable.rs
  compiler/executable/function/recursion_analyser.rs
  compiler/executable/match_/planner/match_executable.rs
  compiler/executable/match_/planner/mod.rs
  compiler/executable/match_/planner/plan.rs
  compiler/executable/match_/planner/vertex/constraint.rs
  compiler/executable/match_/planner/vertex/mod.rs
  compiler/executable/pipeline.rs
  compiler/tests/transformation.rs
  dependencies/typedb/repositories.bzl
  executor/instruction/mod.rs
  executor/pipeline/fetch.rs
  executor/pipeline/pipeline.rs
  executor/read/pattern_executor.rs
  executor/read/tabled_functions.rs
  executor/tests/compile_execute.rs
  executor/write/write_instruction.rs
  function/function_manager.rs
  ir/lib.rs
  ir/pattern/conjunction.rs
  ir/pattern/constraint.rs
  ir/pattern/disjunction.rs
  ir/pattern/mod.rs
  ir/pattern/negation.rs
  ir/pattern/nested_pattern.rs
  ir/pattern/optional.rs
  ir/pipeline/block.rs
  ir/pipeline/function.rs
  ir/translation/constraints.rs
  ir/translation/function.rs
  ir/translation/pipeline.rs
  resource/constants.rs
  tests/behaviour/steps/BUILD
  tests/behaviour/steps/Cargo.toml
  tests/behaviour/steps/lib.rs
  tests/behaviour/steps/query/typeql.rs
Labels: type: bug, priority: blocker, domain: language

#7397 Filter out unnamed variables in expected variable positions of Put stages
  compiler/executable/insert/executable.rs
  compiler/executable/put/mod.rs
  compiler/executable/update/executable.rs
Labels: type: bug, domain: executor

#7398 Make TypeDB logo configurable
  Cargo.lock
  main.rs
  server/server.rs
  tests/behaviour/steps/BUILD
  tests/behaviour/steps/Cargo.toml
  tests/behaviour/steps/connection/mod.rs
Labels: type: refactor, priority: high, domain: server

#7403 Fix write transactions left open and blocking other transactions after receiving errors
  server/service/transaction_service.rs
  tests/behaviour/steps/connection/mod.rs
Labels: type: bug, priority: high, domain: server

#7404 Handle assignment to anonymous variables
  compiler/executable/match_/planner/match_executable.rs
  compiler/executable/match_/planner/mod.rs
  compiler/executable/match_/planner/plan.rs
  executor/read/nested_pattern_executor.rs
  executor/read/tabled_call_executor.rs
  executor/row.rs
  executor/tests/execute_function.rs
  tests/behaviour/steps/query/typeql.rs
Labels: type: bug, priority: blocker

#7399 Simplify Batch by letting Vec do the work
  executor/batch.rs
  executor/pipeline/insert.rs
  executor/pipeline/mod.rs
  executor/pipeline/put.rs
  executor/pipeline/stage.rs
  executor/read/collecting_stage_executor.rs
  executor/reduce_executor.rs
  resource/constants.rs
Labels: type: refactor, domain: executor

#7409 Optimize unique constraints operation time checks for write queries
  common/iterator/mod.rs
  concept/thing/attribute.rs
  concept/thing/thing_manager/validation/operation_time_validation.rs
  dependencies/typedb/repositories.bzl
Labels: type: bug, priority: high, domain: server

#7411 Fix incorrect set of input variables to nested patterns
  compiler/executable/match_/planner/mod.rs
  compiler/executable/match_/planner/plan.rs
  concept/thing/attribute.rs
  dependencies/typedb/repositories.bzl
Labels: type: bug, priority: blocker, domain: language

#7414 Extend Docker OS support and reduce TypeDB Docker image size
  BUILD
  docker/BUILD
  docker/images.bzl
Labels: type: bug, domain: build, priority: high
