Repository typedb/typedb, pull requests merged in 2025-09, with the labels that each got.

#7566 Lock attributes on updating connections
  compiler/annotation/match_inference.rs
  compiler/executable/match_/planner/mod.rs
  compiler/executable/match_/planner/plan.rs
  concept/thing/attribute.rs
  concept/thing/entity.rs
  concept/thing/mod.rs
  concept/thing/object.rs
  concept/thing/relation.rs
  concept/thing/thing_manager.rs
  concept/type_/attribute_type.rs
  concept/type_/role_type.rs
  database/database_manager.rs
  database/migration/database_importer.rs
  database/transaction.rs
  ir/translation/function.rs
  query/query_manager.rs
  storage/durability_client.rs
  storage/keyspace/mod.rs
Labels: priority: blocker, domain: storage

#7587 Make state initialisation and loading extensible
  database/database_manager.rs
  server/lib.rs
  server/service/grpc/transaction_service.rs
  server/service/grpc/typedb_service.rs
  server/service/http/typedb_service.rs
  server/state.rs
  server/system_init.rs
  system/concepts.rs
  system/lib.rs
  system/util.rs
  user/lib.rs
  user/user_manager.rs
Labels: type: bug, type: refactor, priority: high

#7590 Reenable Sentry crash reporting
  concept/type_/annotation.rs
  concept/type_/type_manager/validation/operation_time_validation.rs
  executor/read/stream_modifier.rs
  main.rs
Labels: type: bug, priority: high, domain: server
