Repository typedb/typedb, pull requests merged in 2025-02, with the labels that each got.

#7331 Remove cardinalities operation time validation
  Cargo.lock
  common/iterator/mod.rs
  concept/thing/statistics.rs
  concept/thing/thing_manager.rs
  concept/thing/thing_manager/validation/commit_time_validation.rs
  concept/type_/annotation.rs
  concept/type_/constraint.rs
  concept/type_/type_manager/validation/commit_time_validation.rs
  concept/type_/type_manager/validation/mod.rs
  concept/type_/type_manager/validation/operation_time_validation.rs
  dependencies/typedb/repositories.bzl
  encoding/graph/thing/mod.rs
  encoding/graph/thing/vertex_attribute.rs
  encoding/graph/thing/vertex_object.rs
  encoding/layout/prefix.rs
  executor/BUILD
  executor/Cargo.toml
  executor/instruction/mod.rs
  executor/pipeline/fetch.rs
Labels: type: bug, priority: high, domain: server

#7339 Include deleted concepts in structural equality for delete stage
  ir/translation/pipeline.rs
Labels: type: bug, domain: executor

#7343 Activate diagnostics reporting for the Docker image
  BUILD
  docker/BUILD
Labels: domain: build, domain: server

#7340 Fix getting annotations when argument is not referenced in body
  compiler/annotation/function.rs
  dependencies/typedb/repositories.bzl
  ir/translation/function.rs
Labels: type: bug, domain: language

#7336 Checkpoint databases at regular intervals
  common/concurrency/interval_runner.rs
  compiler/annotation/type_seeder.rs
  database/database.rs
  database/database_manager.rs
  executor/tests/execute_comparison_check.rs
  ir/translation/function.rs
  resource/constants.rs
Labels: type: feature, priority: high, domain: storage

#7346 Introduce multi-staged server termination
  server/service/transaction_service.rs
  server/service/typedb_service.rs
  server/typedb.rs
Labels: type: bug, type: feature, priority: high, domain: server

#7347 Avoid persisting empty statistics deltas
  concept/thing/statistics.rs
Labels: type: bug, priority: high

#7345 Database debug tools
  Cargo.lock
  Cargo.toml
  common/bytes/byte_array.rs
  common/error/Cargo.toml
  common/structural_equality/Cargo.toml
  compiler/Cargo.toml
  concept/Cargo.toml
  concept/thing/statistics.rs
  concept/type_/attribute_type.rs
  concept/type_/entity_type.rs
  concept/type_/object_type.rs
  concept/type_/relation_type.rs
  concept/type_/role_type.rs
  database/Cargo.toml
  database/tools/BUILD
  database/tools/Cargo.toml
  database/tools/read-wal.rs
  database/tools/replay-wal.rs
  dependencies/typedb/repositories.bzl
  diagnostics/Cargo.toml
  encoding/Cargo.toml
  encoding/graph/type_/vertex.rs
  encoding/layout/prefix.rs
  executor/Cargo.toml
  function/Cargo.toml
  ir/Cargo.toml
  query/Cargo.toml
  server/Cargo.toml
  storage/Cargo.toml
  storage/isolation_manager.rs
  storage/keyspace/keyspace.rs
  storage/snapshot/write.rs
  system/Cargo.toml
  tests/behaviour/steps/Cargo.toml
  user/Cargo.toml
Labels: type: feature, priority: medium

#7352 Introduce brew and apt deployment
  .circleci/config.yml
  BUILD
  WORKSPACE
  binary/BUILD
  binary/typedb.service
  config/brew/typedb.rb
  dependencies/typedb/repositories.bzl
Labels: domain: build

#7355 Add setup_remote_docker step to docker deployment jobs
  .circleci/config.yml
Labels: domain: build

#7344 Let attribute supertypes be not abstract and fix independent attributes behavior
  common/concurrency/interval_runner.rs
  concept/tests/test_statistics.rs
  concept/thing/attribute.rs
  concept/thing/entity.rs
  concept/thing/object.rs
  concept/thing/relation.rs
  concept/thing/thing_manager.rs
  concept/thing/thing_manager/validation/mod.rs
  concept/thing/thing_manager/validation/operation_time_validation.rs
  concept/type_/type_manager.rs
  concept/type_/type_manager/validation/mod.rs
  concept/type_/type_manager/validation/operation_time_validation.rs
  concept/type_/type_manager/validation/validation.rs
  dependencies/typedb/repositories.bzl
  executor/instruction/isa_executor.rs
  executor/instruction/isa_reverse_executor.rs
  storage/snapshot/write.rs
  tests/behaviour/concept/migration/BUILD
  tests/behaviour/concept/migration/function.rs
  tests/behaviour/steps/concept/thing/has.rs
  tests/behaviour/steps/concept/thing/relation.rs
  tests/behaviour/steps/query/typeql.rs
Labels: type: bug, type: feature, priority: high, domain: server

#7365 Enable functions in write pipelines
  compiler/annotation/match_inference.rs
  compiler/annotation/type_seeder.rs
  dependencies/typedb/repositories.bzl
  executor/pipeline/pipeline.rs
  executor/tests/execute_function.rs
  function/function_manager.rs
  query/query_manager.rs
Labels: domain: executor, domain: reasoner

#7368 Introduce docker snapshot jobs
  .circleci/config.yml
  BUILD
  deployment.bzl
  docker/BUILD
Labels: domain: build

#7370 Allow duration literals without date component
  Cargo.lock
  Cargo.toml
  common/error/Cargo.toml
  common/structural_equality/Cargo.toml
  compiler/Cargo.toml
  concept/Cargo.toml
  database/Cargo.toml
  dependencies/typedb/repositories.bzl
  diagnostics/Cargo.toml
  encoding/Cargo.toml
  executor/Cargo.toml
  function/Cargo.toml
  ir/Cargo.toml
  ir/translation/literal.rs
  query/Cargo.toml
  server/Cargo.toml
  storage/Cargo.toml
  system/Cargo.toml
  tests/behaviour/steps/Cargo.toml
  user/Cargo.toml
Labels: type: bug, priority: blocker, domain: language

#7372 Handle zero-length rows in batch
  executor/batch.rs
Labels: type: bug, priority: blocker, domain: executor

#7329 Resolve ambiguity in duration arithmetic
  encoding/value/duration_value.rs
Labels: type: bug, priority: blocker, domain: language

#7374 Avoid writing tombstones for temporary relation indices
  Cargo.toml
  concept/thing/thing_manager.rs
  dependencies/typedb/repositories.bzl
Labels: type: bug, priority: blocker, domain: server

#7373 Implement like & contains comparators
  Cargo.lock
  Cargo.toml
  common/bytes/Cargo.toml
  common/concurrency/Cargo.toml
  common/error/error.rs
  common/primitive/Cargo.toml
  common/structural_equality/Cargo.toml
  compiler/executable/match_/planner/plan.rs
  concept/Cargo.toml
  database/Cargo.toml
  database/tools/Cargo.toml
  dependencies/typedb/repositories.bzl
  diagnostics/Cargo.toml
  durability/Cargo.toml
  encoding/Cargo.toml
  executor/BUILD
  executor/Cargo.toml
  executor/instruction/mod.rs
  ir/BUILD
  ir/Cargo.toml
  ir/lib.rs
  ir/pattern/constraint.rs
  query/Cargo.toml
  server/Cargo.toml
  storage/Cargo.toml
  system/Cargo.toml
  tests/behaviour/steps/Cargo.toml
Labels: domain: language
